LLK/scratch-gui

src/components/green-flag/green-flag.jsx, src/components/stop-all/stop-all.jsx, src/containers/blocks.jsx, src/containers/green-flag.jsx, src/containers/stop-all.jsx
Requires https://github.com/LLK/scratch-vm/pull/348
For now this uses the CSS `filter` property to crudely "highlight" for the active state. This is a temporary solution until we have a real design for the active states.
=> Glow flag/stop button when scripts are running

package.json, src/containers/stage.jsx
this pr depends on a pr to the vm and to the blocks
=> add audio engine

src/lib/libraries/backdrops.json
Backdrops.json
Useful to solving [this issue.](https://github.com/LLK/scratch-gui/issues/36)  
Adds the correct sizes of images in the backdrops library
Because it allows you to display backdrops for a playtest
I didn't add new testing
=> Adding Data to backdrop.json

src/components/box/box.css, src/components/green-flag/green-flag.css
Resolves https://github.com/LLK/scratch-gui/issues/42 and some design features in https://github.com/LLK/scratch-gui/issues/1
Before:
After:
Two steps forward in design.
=> Design Changes

src/containers/blocks.jsx
_Tiny bit of #1_
_Change some colors to match design in #1_
_Just a little closer._
=> Change ScratchBlocks Colors to match concept colors from #1

src/containers/blocks.jsx
_Tiny bit of #1_
_Darkens insertion marker so you can see it._
_Make the insertion marker usable._
=> Make Insertion Marker Visible

src/containers/gui.jsx
_#41_
_Make 30TPS on by default._
_For compatibility testing._
=> Make Compatibility Mode on By Default

src/index.ejs, webpack.config.js
=> Supply viewport metadata for retina displays

package.json
=> chore(package): update postcss-loader to version 1.3.1

src/lib/libraries/sprites.json
Resolves GH-137
- Moves letters / numbers to the top of the sprite library (above "Abby")
- Prep for "Animate Your Name" playtest
=> Move letters / numbers to top of the sprite library

src/lib/blocks.js
Saving with my editor also got rid of some stray whitespace.
=> Fix no-var warnings

src/containers/stage.jsx
Matches 2.0 for when sprites should be picked up.
Perform a pick on the renderer and transform the returned drawable if any to a target id. If that target id is not the stage, begin updating the sprite position based on the mouse coordinates.
The behavior in the editor where sprites may be dragged outside of the stage, and their positions are only updated if dropped inside the stage will come in a subsequent PR.
Thanks to @fsih for helping get started with this.
Resolves #66 
/cc @lifeinchords @cwillisf @thisandagain @carljbowman
=> Implement drag and drop for sprites on the stage

src/lib/blocks.js
_Part of LLK/scratch-blocks#749_
_Fixes them not displaying_
=> Fix sprites in drop-down

src/components/sprite-info/sprite-info.css, src/components/sprite-info/sprite-info.jsx
Fixes #156 + refactored classnames to style guide conventions
=> SpriteInfo: Radio Buttons Toggles + Better Classnames

src/containers/backdrop-library.jsx, src/containers/costume-library.jsx
Uses https://github.com/LLK/scratch-vm/pull/514 to fix backdrop and costume adding. 
Fixes https://github.com/LLK/scratch-gui/issues/281
=> Fix backdrop and costume loading from libraries

src/containers/costume-tab.jsx
Fixes https://github.com/LLK/scratch-gui/issues/289
=> Use backdrop library in costume tab

src/containers/sound-library.jsx
Fixes https://github.com/LLK/scratch-gui/issues/286 by using the new storage system to load and play sounds. Also uses the new `addSound` API to correctly load sounds into the vm's audio engine (which is different from the sound libraries audio engine). 
Depends on https://github.com/LLK/scratch-vm/pull/516
=> Use decodeSound and scratch storage for loading sounds

src/components/asset-panel/selector.jsx, src/components/sprite-selector-item/sprite-selector-item.jsx, src/components/sprite-selector/sprite-selector.jsx, src/components/target-pane/target-pane.jsx, src/containers/costume-tab.jsx
Towards LLK/scratch-vm#515, #279
Requires LLK/scratch-vm#517
=> Fix costume loading in sprite info pane and costumes tab

.gitattributes, .travis.yml, package.json, webpack.config.js
This change ensures that line endings, Travis CI settings, and source map settings are similar to other Scratch 3.0 repositories. These were previously part of #262.
=> Standardize settings

src/components/sprite-info/sprite-info.css, src/components/sprite-info/sprite-info.jsx, src/components/sprite-selector/sprite-selector.jsx, src/components/target-pane/target-pane.jsx, src/containers/sprite-info.jsx, src/containers/target-pane.jsx
Fixes https://github.com/LLK/scratch-gui/issues/314
Replace the Draggable field with a simple rotation field.
See https://github.com/LLK/scratch-gui/issues/314
=> Replace draggable with direction input

src/index.jsx
Otherwise the VM can't JSON.load it.
Fix for issue introduced in #325
=> Stringify project data

package.json, src/components/asset-panel/selector.jsx, src/components/button/button.css, src/components/button/button.jsx, src/components/load-button/load-button.css, src/components/load-button/load-button.jsx, src/components/menu-bar/menu-bar.jsx, src/components/sprite-selector/sprite-selector.jsx, src/components/target-pane/target-pane.jsx, src/containers/load-button.jsx, src/containers/save-button.jsx, src/containers/sprite-selector-item.jsx, src/containers/stage-selector.jsx, src/lib/vm-listener-hoc.jsx, src/reducers/gui.js, src/reducers/vm.js
Requires #339.  Isolated diff: https://github.com/rschamp/scratch-gui/compare/feature/serialization...feature/save-load
Use the de/serialization features of the VM to allow downloading and loading project JSON.
=> Add Save and Load buttons

src/lib/blocks.js
_Fixes #150_
_Updates Menus on Click_
_So menus are always up to date when you open them_
=> Update Dropdown Menus On Click

src/components/asset-panel/selector.css
=> Keeps categories pane a fixed width, to match tabs

README.md
Full exposition here: https://github.com/LLK/scratch-gui/wiki/Publishing-to-GitHub-Pages
=> Add instructions for publishing to the README

package.json, src/components/asset-panel/selector.jsx, src/containers/costume-tab.jsx, src/containers/sound-tab.jsx, src/index.jsx
First part of #477 
Bring in react-intl and demonstrate use of FormatMessage and defineMessages in costume-tab and sound-tab.
=> Localize first elements

src/components/box/box.jsx
Just creating documentation for the Box UI component. I'm making a pass at documenting all the UI components
=> Documentation for the inputs of the box component

package.json
=> chore(package): update react-modal to version 2.2.1

.gitignore, languages.json, package.json, scripts/generate-locale-messages.js
Just look at the last commit, the others are pre-requisites for this one.
The main update is `scripts/generate-locale-messages.js`.
=> Gh509 combine translations

package.json, src/index.jsx, src/lib/intl.jsx, src/reducers/gui.js, src/reducers/intl.js
This PR integrates react-intl with redux. Sets up what's needed for language switching.
=> Integrate intl redux

package.json
Does what a previous greenkeeper PR was supposed to do, update webpack to 3.0+
It doesn't change anything, just needed to update some other dependencies.
=> Update webpack and related packages

src/components/audio-trimmer/audio-trimmer.jsx, src/components/meter/meter.jsx, src/components/record-modal/recording-step.jsx, src/containers/audio-trimmer.jsx, src/lib/audio/audio-buffer-player.js, src/lib/audio/audio-effects.js, src/lib/audio/effects/robot-effect.js, src/lib/audio/shared-audio-context.js, src/lib/blocks.js, src/lib/monitor-adapter.js, src/lib/opcode-labels.js, test/helpers/selenium-helpers.js, test/unit/util/audio-util.test.js
Fixes all the lint warnings except the `@todo` comments. Including a bug!
We are going to get stricter about lint warnings, so wanted to fix these easy ones in advance. 
Check out the lint log!
=> Fix all lint warnings except todo comments (including a bug!)

package.json
=> chore(package): update react-draggable to version 3.0.2

package.json
Resolves https://github.com/LLK/scratch-gui/issues/681
Update eslint
=> Update to eslint 4.7.1

package.json
Temporarily remove integration test so that we can deploy.
Regarding #727
=> Remove integration test

.travis.yml
Currently, not super duper useful for it to be there but we should get this in place anyway.
=> Publish to NPM

.tx/config, scripts/generate-locale-messages.js, src/components/gui/gui.jsx, src/components/sound-editor/sound-editor.jsx, src/components/sprite-selector-item/sprite-selector-item.jsx, src/components/sprite-selector/sprite-selector.jsx, src/components/stage-selector/stage-selector.jsx, src/components/turbo-mode/turbo-mode.jsx, src/containers/costume-tab.jsx, src/containers/sound-tab.jsx, src/locale.js
#669 
revised string ids for localization according to our new convention. See specific comments/questions below.
=> updating string ids to follow convention

.travis.yml, package.json, test/helpers/enzyme-setup.js, test/unit/containers/sound-editor.test.jsx, test/unit/util/project-loader-hoc.test.jsx
Updates all the required packages for react 16!
Fixes the tests that broke when updating to enzyme 3. They had to do with updating component props.
=> Update to react 16!

src/components/sprite-selector-item/sprite-selector-item.jsx, src/components/sprite-selector/sprite-selector.jsx, src/components/target-pane/target-pane.jsx, src/containers/sprite-selector-item.jsx, src/containers/target-pane.jsx
Adds sprite duplication to right click menu. Depends on https://github.com/LLK/scratch-vm/pull/676
=> Add duplicate option for sprite selector menu

package.json, src/components/asset-panel/asset-panel.jsx, src/containers/costume-tab.jsx, src/reducers/gui.js
https://github.com/LLK/scratch-gui/issues/78
(the vector paint editor check box)
Add in-progress vector paint editor
More art in the world
=> Add paint editor

package.json
Resolves https://github.com/LLK/scratch-gui/issues/751, which was actually wrong about the failure. Chromedriver versions have since been pinned, and this update seems to work fine.
=> Update to chromedriver 2.33.1

src/lib/make-toolbox-xml.js
Resolves https://github.com/LLK/scratch-gui/issues/814
Add separators to the XML to chunk the blocks a là 2.0
=> Add block chunking to toolbox xml

src/components/question/question.css, src/components/question/question.jsx, src/components/stage/stage.jsx, src/containers/question.jsx, src/containers/stage.jsx, src/lib/make-toolbox-xml.js
GUI part of ask/answer block implementation
Listen to the `QUESTION` events, create and manage the question/answer inputs, and submit user input to the VM through the `ANSWER` event.
=> Wire up ask/answer components to the stage

.travis.yml
Fixes https://github.com/travis-ci/travis-ci/issues/8836
If the build passes, it worked.
=> Try fixing travis permissions problem for chrome

src/lib/default-project/project.json, src/lib/libraries/sprites.json, test/integration/test.js
#1022
Renames the default "meow" sound to "Meow"
Fixes naming inconsistency
I changed the integration test accordingly
=> Renamed meow sound to Meow

package.json
=> Update paint dependency to get hotfix for eyedropper

package.json
Deploy paint editor hotfix to master https://github.com/LLK/scratch-paint/pull/229
Sorry this is a bit messier a process than I'd like it to be in the future.
=> Merge paint editor fix to master

src/components/blocks/blocks.css, src/lib/make-toolbox-xml.js, test/integration/test.js
Resolves https://github.com/LLK/scratch-gui/issues/1096
Change "More" to "My Blocks". 
Updated tests.
=> Change "More" category to "My Blocks.

src/components/custom-procedures/custom-procedures.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1098
=> Change modal title to "Make a Block"

src/lib/make-toolbox-xml.js, test/integration/examples.test.js, test/integration/test.js
Closes https://github.com/LLK/scratch-gui/issues/1094
This part of the GUI hasn't been prepared for localization yet, and I didn't change that.
=> Change category name from "Data" to "Variables"

src/lib/default-project/project.json, test/integration/test.js
Closes https://github.com/LLK/scratch-gui/issues/1110
Add "count" as a (global) variable to the default project.
Added a check for this to the integration test dealing with variables.
=> Add default "count" variable

src/components/forms/input.css, src/components/sprite-info/sprite-info.css, src/components/sprite-info/sprite-info.jsx, src/components/sprite-selector/sprite-selector.jsx, src/components/target-pane/target-pane.jsx, src/containers/sprite-info.jsx, src/containers/target-pane.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1064
=> Add size and remove rotation style from sprite info area.

src/components/custom-procedures/custom-procedures.css, src/components/custom-procedures/custom-procedures.jsx, src/containers/custom-procedures.jsx
=> Adds "run without screen refresh" to block editor.

src/lib/make-toolbox-xml.js
Final GUI part of LLK/scratch-blocks#1317
Add new layer blocks to toolbox XML.
Depends on https://github.com/LLK/scratch-vm/pull/880
=> Add new layer blocks to toolbox xml

src/components/sprite-info/icon--x.svg, src/components/sprite-info/icon--y.svg
Resolves https://github.com/LLK/scratch-gui/issues/1156
Updates to new icons
=> Update to new XY icons

src/lib/default-project/project.json, test/integration/test.js
Resolves GH-1162
Changes the default variable name from "count" to "my variable"
See GH-1162
=> Change default variable name to 'my variable'. 

.travis.yml
Publishes master branch builds to an S3 bucket for the preview release.
=> Set up S3 deployment

src/lib/libraries/sounds.json
Add 100 new sounds to the library, in a variety of themes including games, space, animals, sports, wacky, etc. The new sounds are merged alphabetically into the existing set of sounds.
We've collected these sounds from [freesound](freesound.org), [archive.org](archive.org), Youtube's [audio library](https://www.youtube.com/audiolibrary/soundeffects), and Adobe's [audition collection](https://offers.adobe.com/en/na/audition/offers/audition_dlc/AdobeAuditionDLCSFX.html).
All the sounds are either public domain, or licensed in a way that allows us to reuse them, such as a CC license. (see attribution, below).
This is progress toward an update of the contents of the sound library, improving its overall quality , diversity, usefulness, and ability to support and inspire creative projects. …
=> Add 100 new sounds to library

src/index.ejs
I created the project in the wrong place, oops.
=> Fix new Sentry DSN

package.json
=> chore(package): update scratch-render to version 0.1.0-prerelease.1516772701

src/components/preview-modal/preview-modal.jsx
=> Revert "Remove tooltip from Try It button. (Fixes #1260)"

src/components/forms/input.jsx, src/components/sprite-info/sprite-info.css, src/components/sprite-info/sprite-info.jsx, src/css/typography.css
Fix https://github.com/LLK/scratch-gui/issues/1349
Previous PR broke non-text inputs
=> Fix input css to apply only to text fields

src/lib/opcode-labels.js
[Lists appear as Variables](https://github.com/LLK/scratch-gui/issues/1016)
Monitor should show the list's name.
Monitor should show the list's name
Sorry
=> Monitor should show the list's name

src/lib/libraries/sounds.json
=> Revert "Remove duplicate computer beeps"

package.json, webpack.config.js
Wrapping up all the recent greenkeeper updates into one
=> Greenkeeper updates 2 22 18

src/containers/costume-tab.jsx, src/lib/blocks.js
Use target.getCostumes() instead of target.sprite.costumes, in preparation to make sprite.costumes private
=> Update gui to use getter for target costumes

src/containers/import-modal.jsx
Resolves #1535
Allow http urls in import modal.
Issue #1535
=> Allow http url in import modal

package.json
A couple of greenkeeper PRs pulled into one
=> Update deps 3/6

src/lib/libraries/costumes.json, src/lib/libraries/sounds.json, src/lib/libraries/sprites.json
GH-1355 
GH-1437 
GH-1442 
GH-1507
Makes a number of small changes to the sprite library (including removing all "c" costumes from the musical instrument sprites).
=> Minor fixes to sprite library

.travis.yml, test/helpers/selenium-helper.js
Following the instructions https://developers.google.com/web/updates/2017/04/headless-chrome
I'm trying to see if this will allow for more stable tests and/or faster integration tests. I'm submitting this PR to test it on travis. It actually works with no additional changes locally, which is kind of remarkable!
=> Try using headless chrome for integration tests

src/containers/costume-tab.jsx, src/containers/target-pane.jsx, src/lib/vm-listener-hoc.jsx
Fixes some warnings about unused props
=> Clean up some unused prop warnings

src/containers/backdrop-library.jsx, src/containers/costume-library.jsx, src/containers/costume-tab.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1475
=> Costume tab detects added costume and switches to the current costume of the edit target

.travis.yml
Resolves https://github.com/LLK/scratch-gui/issues/1681
Updates the travis.yml to run the tests/build with node 8
=> Updates the travis.yml to run the tests/build with node 8

src/components/stage-selector/stage-selector.css, src/components/stage-selector/stage-selector.jsx
Visually reviewed by @carljbowman already
Before:
After:
=> Make the stage thumbnail match the comps

src/components/sprite-selector/sprite-selector.jsx, src/components/stage-selector/stage-selector.jsx
Resolves #1744
Title says it all.
#1744
=> Remove camera upload options from sprite and backdrop selectors.

package.json
=> Update VM manually in package json

src/components/sprite-selector/sprite-selector.jsx, src/components/stage-selector/stage-selector.jsx, src/containers/backdrop-library.jsx, src/containers/costume-library.jsx, src/containers/costume-tab.jsx, src/containers/extension-library.jsx, src/containers/sound-library.jsx, src/containers/sound-tab.jsx, src/containers/sprite-library.jsx, test/integration/costumes.test.js, test/integration/sounds.test.js
Resolves GH-1759
- Changes language in selectors from "X Library" to "Choose a X"
- Changes library titles to be "Choose a X"
- More explicit user prompt and removes the concept of a "library" which feels superficial / unnessessary
- Test coverage updated to reflect changes
/cc @ntlrsk
=> Adjust language in selectors and libraries

package.json
=> Update vm to include video motion fixes for other browsers

package.json
=> Update vm to include fixes for video transparency

src/lib/libraries/costumes.json, src/lib/libraries/sprites.json
=> Resolve issue with costume Button 4-b

src/lib/make-toolbox-xml.js, test/integration/blocks.test.js
=> Adjustments to string operator default arguments

src/lib/make-toolbox-xml.js
=> Reorder and add default arguments to gt, lt, eq blocks

package.json
Reverts LLK/scratch-gui#1829, bringing the bitmap paint editor out so we can deploy, i'll bring it back after
=> Revert bitmap paint editor PR for now

package.json
=> Update the vm to include fixes for downloading imported sounds

package.json
=> Bring in the latest bitmap editor from scratch-paint

src/components/filter/filter.css, src/components/library/library.css
This way you can click anywhere to gain focus.
Demo: https://rschamp.github.io/scratch-gui/bugfix/search-height/
=> Make the library filter input full height

src/components/library/library.jsx
=> Search name and tags while filtering

src/components/library/library.css, src/components/library/library.jsx
=> [Master] Account for filter bar in library grid height

src/components/filter/filter.css, src/components/library/library.css
=> [Master] Make the library filter input full height

src/components/gui/gui.jsx, src/components/import-modal/import-modal.css, src/components/import-modal/import-modal.jsx, src/components/preview-modal/preview-modal.css, src/components/preview-modal/preview-modal.jsx, src/containers/gui.jsx, src/containers/import-modal.jsx, src/containers/preview-modal.jsx, src/reducers/modals.js, test/integration/project-loading.test.js
This reverts commit 29d5619d936d30eea9ca601f6d052aad108ca0d3.
Returns the preview modal to the state where it still has the "import from 2.0" button. These changes will be delayed a week.
=> Revert "Updates to preview modal for release (#1864)"

package.json
=> chore(package): update chromedriver to version 2.38.2

src/components/gui/gui.jsx, src/components/import-modal/import-modal.css, src/components/import-modal/import-modal.jsx, src/components/preview-modal/preview-modal.css, src/components/preview-modal/preview-modal.jsx, src/containers/gui.jsx, src/containers/import-modal.jsx, src/containers/preview-modal.jsx, src/reducers/modals.js, test/integration/project-loading.test.js
Reverts LLK/scratch-gui#1888
Revert the reversion! (( My head hurts ))
=> Revert "Bring back "Updates to preview modal for release""

src/lib/libraries/backdrops.json, src/lib/libraries/costumes.json, src/lib/libraries/sounds.json, src/lib/libraries/sprites.json
- Updates libraries using new version of `libgen` that supports tagging and sorting
- Resolves issue with the "z" prefix on all of the letter sprites and costumes
- Initial PR to bring libraries up-to-date and start process of tagging all sprites, costumes, backdrops, and sounds
=> Update libraries with new version of libgen

src/lib/libraries/backdrops.json, src/lib/libraries/costumes.json, src/lib/libraries/sprites.json
Adds new sprites, costumes, and backdrops from ST intern: [Ipzy!](https://scratch.mit.edu/users/ipzy/)
=> Add sprites, costumes, and backdrops from Ipzy

src/lib/analytics.js, src/playground/index.ejs, webpack.config.js
Fixes https://github.com/LLK/scratch-gui/issues/1946
Puts the error logging and GA tokens in travis so that forks do not spam our logging.
=> Move analytics things to environment vars

package.json
1. Fix for offsetting costumes (h/t @kchadha)
2. Fix for paint editor undo (h/t @fsih)
=> Update deps for deploy

test/integration/blocks.test.js, test/integration/costumes.test.js, test/integration/sounds.test.js, test/integration/sprites.test.js
Personal fear that the surprise/empty buttons in thermometer menus were generally untested. Now they are!
Also this should make it easier to add tests for all the new file upload options as well /cc @kchadha.
Also /cc @BryceLTaylor since this is relevant to you!
=> Add several new integration tests to the GUI

.babelrc, package.json
Replace babel-preset-es2015 with babel-preset-env
Sibling of https://github.com/LLK/scratch-vm/pull/1112
=> Replace babel-preset-es2015 with babel-preset-env

package.json, src/lib/default-project/index.js
Replace buffer-loader with arraybuffer-loader
SIbling of https://github.com/LLK/scratch-vm/pull/1111
=> Replace buffer-loader with arraybuffer-loader

package.json
This fixes the music manifest issue.
=> Update scratch-vm dependency

package.json, src/components/monitor/monitor.css
Including triple scrollbars on list monitors and fixing the say bubble fonts
=> Fixes from smoke test

package.json
=> Update scratch render again to fix speech bubbles again

package.json
This is temporary for the release to master
=> Update scratch-paint to hide font dropdown

package.json
See #2096 
Pull in updates to smoke test branch into develop, so it is even with master.
=> Smoke test branch -> Develop

src/lib/libraries/costumes.json, src/lib/libraries/sounds.json, src/lib/libraries/sprites.json
- Adds the "story" letters to the sprite and costume libraries
- Re-sync libraries using `libgen`
Mac
Windows
Chromebook
iPad
Android Tablet
/cc @carljbowman @ntlrsk
=> Add 'story' letters to libraries

src/components/monitor/monitor.css
Fixes [#2156](https://github.com/LLK/scratch-gui/issues/2156)
Improve the appearance of the list monitors.
No tests necessary.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Change list monitor styles

src/containers/blocks.jsx
Resolves https://github.com/LLK/scratch-gui/issues/2181
Disable workspace sounds
See linked issue
Tested locally
=> Disable sounds in scratch-blocks

package.json, src/components/blocks/blocks.css
Make comments look reasonable and update vm dependency.
=> CSS updates for rendering block comments and update VM.

package.json
Mac
Windows
Chromebook
iPad
Android Tablet
=> Fix stack glow in toolbox by updating scratch-blocks

.travis.yml
Add a step to the travis yml to run the smoke tests automatically when making a PR against master. This was the "step 2" from https://github.com/LLK/scratch-gui/pull/2233
I looked at the documentation, it is kinda strange but my understanding is  TRAVIS_BRANCH is the branch you are PR'ing _against_ when TRAVIS_PULL_REQUEST is true, but it is the branch that is being built when TRAVIS_PULL_REQUEST is false... [src](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables)
=> Run smoke test if pull request against master

package.json
Bring in changes for reorder APIs
=> Update scratch vm

src/lib/blocks.js, src/lib/make-toolbox-xml.js
This reverts commit 94915a9a5e5ca1aa841209c69f4cb4e82bbae093.
@ericrosenbaum verbally approved
=> Revert "Add when touching hat"

src/lib/blocks.js, src/lib/make-toolbox-xml.js
###Features
* Comments to allow users to edit and move comments on imported projects
* Pen size can now fill whole stage at once
* Many new tags have been added to costumes allowing them to be searchable
* Several new bitmap backdrops have been added
=> Merge smoke changes for 6/8/18 iteration to back into develop

package.json
Closes #2313
Mac
Windows
Chromebook
iPad
Android Tablet
=> chore(package): update scratch-l10n to version 3.0.20180611175036

src/containers/blocks.jsx
Allows adding block and workspace comments.
=> Enable comments

src/containers/blocks.jsx
=> Disable comments

src/containers/blocks.jsx
Enable creating workspace and block comments.
=> Enable comments.

.github/PULL_REQUEST_TEMPLATE.md
this addes the keywords needed to close issues automatically
https://help.github.com/articles/closing-issues-using-keywords/
- https://github.com/LLK/scratch-gui/issues/2205 is one of the issues kept open after the pull request was merged. This will close these pull requests automatically on merge.
By adding a list of pull request numbers with "fixes" in them, 
Mac
Windows
Chromebook
iPad
Android Tablet
=> Close issues automatically

package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Update scratch vm to include sharing APIs

src/components/menu-bar/menu-bar.jsx
Resolves GH-2264
Changes copy for local save / load in the "File" menu
The current language was a little confusing
Mac
Windows
Chromebook
iPad
Android Tablet
=> Changes to language in "File" menu

.travis.yml
=> [Master] Don't set Content-Encoding header when deploying to S3

src/components/sprite-selector/sprite-list.jsx, src/containers/backpack.jsx, src/containers/target-pane.jsx, src/lib/backpack-api.js, src/lib/backpack/sprite-payload.js
This is based on https://github.com/LLK/scratch-gui/pull/2407, the only new commit is https://github.com/LLK/scratch-gui/commit/cc34255afb2e53a5e5ee65a96e044f0384bc351c
This adds saving sprites and dragging them back out of the backpack.
=> Backpack Step 6: Sprites!

src/lib/audio/audio-effects.js
- Resolves https://github.com/LLK/scratch-gui/issues/1651
Manually reverse the buffer data into a new buffer, making sure not to overwrite the original buffer data. If the original is modified, the undo stack does not work.
https://github.com/LLK/scratch-gui/issues/1651
Tested by trying to repro the issue: 
1. Click "sounds" tab
2. click "reverse" effect
3. click "undo" 
4. See that the sound has gone back to original
Mac
Windows
Chromebook
iPad
Android Tablet
=> Fix the "reverse" audio effect not working with the undo stack.

package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Update to newest scratch-vm

package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Update scratch vm to include promise reporter fixes

src/components/menu-bar/menu-bar.jsx, test/integration/localization.test.js
Enables the language menu for the preview/beta
Simply changes the 'enable' flag on the coming soon tooltip to true. Will open a `tech dept` issue to remove the wrapper.
=> Enable the language menu

src/containers/project-loader.jsx
- Resolves #1794
Don't crash editor if project file fails to upload, instead issue an alert.
Manual testing on valid .sb3 files, and non .sb3/.sb2 files (e.g. .sprite2 or .png).
Mac
Windows
Chromebook
iPad
Android Tablet
=> Don't crash the editor when a project file fails to upload.

src/lib/libraries/costumes.json, src/lib/libraries/sprites.json
🌮 🌮 🌮 🌮 🌮 🌮 🌮 🌮 🌮 🌮 🌮 🌮 🌮 🌮 🌮 🌮 🌮 🌮 
Mac
Windows
Chromebook
iPad
Android Tablet
=> All hail the taco wizard

src/components/library/library.jsx, src/containers/tips-library.jsx, src/reducers/cards.js
- Resolves https://github.com/LLK/scratch-gui/issues/2523
Add more in-depth events for understanding (1) progress through how-to cards and (2) searches in the libraries
Tested by seeing the debug events logged in the console during the given events
=> Improve search and tutorial instrumentation for preview

src/components/cards/cards.jsx
Resolves #2594 
I changed Remove to Close
"Close" makes sense.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Change Remove to Close

src/components/sprite-selector/sprite-selector.jsx
- Resolves #2690
Changes the default message for `gui.spriteSelector.addSpriteFromFile` to "Upload Sprite".
To fix a help wanted issue.
=> Update upload sprite message

package.json
Closes #2649
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> chore(package): update autoprefixer to version 9.0.1

src/lib/libraries/decks/index.jsx
#2696 
Use FormattedMessage
To translate 2 more things
=> Translate Spin & Arrow How-To

src/components/menu-bar/menu-bar.jsx
Update Give Feedback link to point to a new stickied topic. Resolves #2874.
=> [Master] Update Give Feedback link

src/components/import-modal/import-modal.jsx, src/containers/gui.jsx
For some reason the travis eslint did not catch these missing prop validations.
From @rschamp - It may be that there are dependencies that are out of date on travis...
=> Add missing propTypes

package.json
Roll back VM to before LLK/scratch-vm#1453. This broke some pen drawing. Resolves #2911.
=> [Master] Roll back x/y rounding

package.json
=> chore(package): update scratch-vm to version 0.2.0-prerelease.20180822215310

package.json
=> chore(package): update scratch-blocks to version 0.1.0-prerelease.1534979688

src/lib/libraries/extensions/index.jsx
=> Enable WeDo extension

README.md
Update readme with tips on what to do when linking or so didn't work correctly
I had no clue what to do when the local version of scratch-gui just wouldn't appear, so Ben and some others helped. This Readme is no updated with what I learned so others won't run into the same problems.
=> Update readme with tips

package.json, src/containers/paint-editor-wrapper.jsx
=> Zoom to fit

package.json
Keyboard shortcuts need to be disabled until bugs are fixed
=> Update to version that removes keyboard shortcuts

package.json
=> chore(package): update react-tooltip to version 3.8.0

package.json
=> chore(package): update scratch-vm to version 0.2.0-prerelease.20180906133035

package.json
Closes #3090
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> chore(package): update postcss-simple-vars to version 5.0.1

package.json
=> Update paint in smoke

package.json, src/lib/app-state-hoc.jsx, src/lib/libraries/decks/index.jsx, src/lib/tutorial-from-url.js, src/reducers/gui.js, test/integration/project-loading.test.js
- Add ability to load tutorial from id in the URL
=> Deploy Smoke to Master

README.md
- Added full support for "Right to Left" languages (e.g. Hebrew, Arabic)
- Added support for variable / reporter monitors within extensions
- Minor fixes and block language adjustments to the "micro:bit" extension
- Minor fixes to extensions that connect to hardware ("micro:bit", "LEGO WeDo 2.0", etc)
- Fixed various issues in the costume editor
- Resizing an object keeps it's ratio if you drag the corners
- Text in the bitmap editor no longer disappears if you don’t click off of it and change costumes
- Filled / outlined state and line thickness now stays in sync with the selected shape in bitmap editor if you change options and then undo / redo
- Text outline thickness matches between stage and editor
- Pressing backspace or delete in Mozilla Firefox doesn’t try to navigate when paint …
=> Merge to smoke branch

src/components/alerts/alert.css, src/components/alerts/alerts.jsx, src/components/gui/gui.css, src/components/gui/gui.jsx, src/containers/alerts.jsx, src/containers/blocks.jsx, src/containers/gui.jsx, src/css/z-index.css, src/lib/vm-listener-hoc.jsx, src/reducers/alerts.js, src/reducers/gui.js
- Basic alert component that displays when a peripheral disconnects in both editor and full screen mode that can be dismissed with an 'x' button
- This component is reusable for other types of alerts in the future with further customization
=> Testing a new gui component for alerts

src/containers/blocks.jsx
Fix #https://github.com/LLK/scratch-gui/issues/3133
Workspace update errors can be partially recovered from. This allows the gui to "successfully" load on projects that pass vm validation and loading but throw an error in scratch-blocks. Logging the error instead of throwing it allows the gui and vm to finish updating for the workspace change. This allows the VM to behave normally even if the scratch-blocks workspace rendering is incomplete.
----
I tried a few things figuring out a good approach to this. I tried a try/catch around the `emitTargetUpdate` and `emitWorkspaceUpdate` calls in the vm, but figured that was too broad. Tried filtering the error with the `'Workspace Update Error'` added prefix in GUI container. But realized for the VM to function properly the Blocks …
=> log workspace update errors

src/lib/libraries/costumes.json, src/lib/libraries/sprites.json
- Add new fashion sprites to the sprite and costume libraries
- Other small updates to the libraries
Thanks @kosiecki !
=> Add dress up costumes

src/components/alerts/alert.css, src/components/alerts/alert.jsx, src/components/alerts/alerts.jsx, src/components/close-button/close-button.css, src/components/close-button/close-button.jsx, src/components/close-button/icon--close-orange.svg, src/containers/alert.jsx, src/containers/alerts.jsx, src/reducers/alerts.js, test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
- Resolves #3266: Clean up alerts CSS
- Fixes React component/container model for alerts
- Progress towards #2956: Message System - Phase 1
- Localization of alert messages
- Fix alerts api to be more decoupled/abstract/customizable
=> Fix alerts component/containers and CSS styling

src/components/cards/cards.jsx
Resolves #2594
Resolves #3289 
This makes #2694 work.
I needed to change the message ID.
=> Change Cards Close ID

src/components/stage/stage.jsx, src/containers/stage.jsx
=> added micIndicator prop validation

src/components/sprite-selector/sprite-selector.jsx, src/lib/locale-utils.js, src/reducers/locales.js
- Resolves #3351 
Removed TODO. Also this is why Arabic is not RTL on develop
Make Arabic mirror correctly.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Get isRtl from scratch-l10n

src/lib/hash-parser-hoc.jsx, src/lib/project-fetcher-hoc.jsx, src/lib/vm-manager-hoc.jsx, test/unit/util/project-fetcher-hoc.test.jsx, test/unit/util/vm-manager-hoc.test.jsx
- Resolves #3347 
Adds tests for some of the new higher order components added in #3303 
We should make sure the things we add work the way we expect
These are tests!
N/A
=> Add project loading HOC tests

src/lib/libraries/sounds.json
Resolves https://github.com/LLK/scratch-gui/issues/2710
Resolves https://github.com/LLK/scratch-gui/issues/2844
- Add 14 new music loops to the sound library! They are all under either public domain, CC0, or CC-BY licenses, and come from freesound.org, freemusicarchive.org, incompetech.com and archive.org.
Air Hockey Saloon - [Chris Zabriskie](http://freemusicarchive.org/music/Chris_Zabriskie/Vendaface/05_-_Air_Hockey_Saloon)
Bossa Bossa - [Kevin MacLeod](https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1600055)
Darkling - [Kevin MacLeod](https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1700050)
Energetic Dance - [furbyguy](http://freesound.org/people/furbyguy/sounds/331881/)
Dance Sitar - [Nina Paley](https://archive.org/details/SitaSingsTheBluesSoundtrack/ss …
=> Sound library update

README.md, src/lib/hash-parser-hoc.jsx, src/lib/project-fetcher-hoc.jsx, src/lib/project-saver-hoc.jsx, src/reducers/project-state.js, test/unit/reducers/project-state-reducer.test.js, test/unit/util/hash-project-loader-hoc.test.jsx
Resolves #3348 
* Tests project-state reducer's exported state-related functions
* Fixes two bugs in the project-state reducer that writing the tests turned up!
=> project state reducer tests, bug fixes

src/lib/opcode-labels.js
Fixing a typo reported by translators.
=> Fix message typos

src/components/sprite-selector-item/sprite-selector-item.jsx, src/containers/sprite-selector-item.jsx, test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
- Resolves https://github.com/LLK/scratch-gui/issues/3469
Fix the broken reference to getCostumeUrl that was broken when the watermark was introduced, and also make sure to set draggable false on the image itself so the browser level image dragging is not triggered
=> Fix dragging tiles

src/containers/blocks.jsx
Small fix that was missing from https://github.com/LLK/scratch-gui/pull/3459
=> added missing onOpenConnectionModal

src/lib/libraries/decks/index.jsx
Resolves https://github.com/LLK/scratch-gui/issues/3485
=> Make tutorial ids unique

src/lib/vm-listener-hoc.jsx
We do not need these events when in fullscreen or player mode, and even if they do not change anything, the dispatch takes time.
This also re-requests a vm.emitTargetsUpdate when transitioning from fullscreen/player back to editor mode to make sure the most recent data is shown.
This is just a small performance boost for running the project in player mode / project page.
Also I moved the deprecated `componentWillReceiveProps` to `componentDidUpdate`. Our usage falls under the "causing side-effects" unsafe usage, which is safe to migrate directly to componentDidUpdate.
=> Only dispatch targetsUpdate events if the full editor is visible

test/integration/localization.test.js
@chrisgarrity this is a test which failed before your fix for the language switcher. It adds a new sprite before changing languages, then checks to make sure it is still there after switching.
=> Add integration test for changing languages not clearing project

src/components/crash-message/crash-message.jsx
Resolves #3191 
Closes quotation mark on each line
Transifex shows text with indent
=> Close quotation mark

package.json
Update scratch-vm, pulling in hotfix for the sprite upload from issue bug.
=> Update vm to pull in hotfix for sprite upload from image.

src/components/spinner/spinner.css, src/components/spinner/spinner.jsx
Implementing spec from https://github.com/LLK/scratch-www/issues/2264
Not actually using this yet, but want to have it in place for alerts.
=> added simple spinner component

package.json, test/integration/connection-modal.test.js
Depends on https://github.com/LLK/scratch-vm/pull/1736
=> Add test for Scratch Link unavailable error modal

src/components/cards/cards.jsx, src/lib/libraries/decks/index.jsx
Add tracking pixels to two tutorials for hour of code
=> [Master] Add HOC tracking px

src/components/menu-bar/author-info.css
Fix the font in creator info when you're looking in editor at a project by someone else!
=> more font options for creator, besides only "Helvetica Neue"

src/index.js
Should be checked in before https://github.com/LLK/scratch-www/issues/2283
- Resolves https://github.com/LLK/scratch-www/issues/2283 , together with https://github.com/LLK/scratch-www/issues/2283
Export the `remixProject` reducer action creator
Make it possible to remix from the project page
Too small to test, I think!
Mac
Windows
Chromebook
iPad
Android Tablet
=> export remixProject reducer function

src/components/alerts/alert.css, src/components/alerts/alert.jsx, src/components/alerts/alerts.jsx, src/components/gui/gui.css, src/containers/alert.jsx, src/reducers/alerts.js
- Resolves #3531: 448/multiline
- Resolves #3264: localize hardware alerts
=> Alerts CSS width changes and hardware alerts localization

package.json
Closes #3854
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> chore(package): update chromedriver to version 2.44.0

src/index.js, src/lib/app-state-hoc.jsx, src/lib/tutorial-from-url.js, src/reducers/gui.js, test/integration/tutorials-shortcut.test.js, test/unit/util/tutorial-from-url.test.js
open the tutorials library for the link to 'see more activities' on the HoC banner.
=> [Master] Start editor with Tutorial Library open (?tutorial=all)

src/components/menu-bar/menu-bar.css, src/components/menu-bar/menu-bar.jsx
We have alerts for this now.
Resolves #3893
=> Remove color rotation while saving

src/containers/alerts.jsx, src/containers/inline-messages.jsx, src/reducers/alerts.js
- Resolves https://github.com/LLK/scratch-gui/issues/3840
* alertsList.filter in containers/alerts.jsx and containers/inline-messages.jsx was made into a reducer selector
* extended comment defining fields of alerts in alerts reducer is now a jsdoc
* renamed SHOW_STANDARD_ALERT since it shows inline alerts too
routine code improvement
=> Revise alerts code to clarify and reorganize alert type handling

src/lib/libraries/sounds.json
- Rename sounds to connect/disconnect
- Fix trumpet sound tags
=> [Master] sound library update

src/lib/default-project/project-data.js, src/lib/libraries/costumes.json, src/lib/libraries/sprites.json
Thanks to @carljbowman for the beautiful and subtle update to the Scratch cat:
- Update the Cat in the sprite and costume libraries
- Use the new cat in the default project
=> Updated Scratch Cat!

src/components/menu-bar/community-button.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/3978
Change "See Community" to "See Project Page"
=> Change "See Community" to "See Project Page"

src/components/menu-bar/menu-bar.jsx
translate the new project confirm alert!
should translate the new project confirm alert
=> translate new project confirm alert

.travis.yml
This is the gui update to push english source when run as a cron job on travis.
=> Add deploy step to push translations in travis

src/lib/project-saver-hoc.jsx
Resolves #3950.
Unfortunately the design of scratch-storage doesn't make having multiple distinct POST urls easy at the moment. So for the time being, just make this request ourselves.
We need to follow up, filed in https://github.com/LLK/scratch-storage/issues/61
=> Manually upload projects using xhr, rather than scratch-storage

src/lib/libraries/sprites.json
=> Update sprite library with new assets

src/components/menu-bar/menu-bar.jsx, test/integration/menu-bar.test.js
Reverts #4035
Fixes #4064
It was a "mini bug" fix caused a critical problem, so I'm going to revert it.
/cc @benjiwheeler
=> Revert 4035 admin sees author

src/lib/cloud-provider.js
Resolves #4126
Removes log messages that were being used for debugging during development of cloud variables, but are now superfluous.
=> Remove unnecessary console logs that occur when sending and receiving cloud messages.

src/containers/tips-library.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/4072
If you aren't on the tutorial project, open it in a new tab in a way that'll work in production
=> Make the requiredProjectId work with the online editor

package.json, src/containers/sb-file-uploader.jsx
- Resolves LLK/scratch-sb1-converter#4
- Resolves LLK/scratch-vm#128
Thank you @mzgoddard!
=> The file uploader file input should accept .sb files as well.

src/lib/libraries/backdrops.json, src/lib/libraries/costumes.json, src/lib/libraries/sprites.json
One more update to the libraries! Many small fixes to the sprite, costume, and backdrop libraries, including:
- Remove blank backdrop1
- Add Forest backdrop
- Fix Woods backdrop thumbnail
- Fix Abby sprite thumbnail
- Add Milk-c (seated milk)
- Fix tags on all the "Story" letters 
Resolves https://github.com/LLK/scratch-gui/issues/4137
Resolves https://github.com/LLK/scratch-gui/issues/4101
=> More library updates

src/components/menu-bar/login-dropdown.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/4168
Adds `form.validationRequired` translation object
Should show actual message!
=> translate form validation string

package.json
=> chore(package): update scratch-vm to version 0.2.0-prerelease.20181221030743

package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Update to storage 1.2.2 for clean asset flag fix

package.json
=> chore(package): update scratch-vm to version 0.2.0-prerelease.20181226154000

src/components/browser-modal/browser-modal.jsx, src/lib/supported-browser.js
Reverts LLK/scratch-gui#4287
after testing and talking about this, we are going to take a softer approach, @thisandagain will describe in an issue.
=> Revert "Check for minimum versions of recommended browsers"

src/components/context-menu/context-menu.css, src/components/context-menu/context-menu.jsx, src/components/sprite-selector-item/sprite-selector-item.jsx
Reverts LLK/scratch-gui#4359
After talking with @carljbowman @benjiwheeler, we are going to bring this back out and work on the design before bringing it back. We don't want to block the high priority bugfixes that are going to production. Thanks for the submission @apple502j, sorry about the confusion.
=> Revert "Adds BorderedMenuItem and use it for delete menu"

package.json
pull in new version of blocks that should include Bulgarian
=> update scratch-blocks for languages.

test/integration/localization.test.js
=> [develop] Hotfix/fix tests

package.json
Reverts LLK/scratch-gui#4501
Pulling out the touching color fix
=> Revert "Update scratch-render to the latest version 🚀"

.travis.yml
Check if an NPM release just happened. And if so, tag the commit and push to GitHub.
Thanks to @paulkaplan for pairing on this
=> Tag NPM releases

package.json
Closes #4536
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> chore(package): update scratch-l10n to version 3.1.20190213142844

src/containers/blocks.jsx, test/integration/blocks.test.js
A hotfix version of https://github.com/LLK/scratch-gui/pull/4563
=> [master] Request a toolbox refresh after switching between tabs to fix #4561

package.json
=> chore(package): update scratch-vm to version 0.2.0-prerelease.20190304203619

src/components/menu/menu.css, src/components/menu/menu.jsx
- Resolves #4584 
Change cursor to a hand when hovering account nav items
make the UI look better and consistent
Mac
Windows
Chromebook
iPad
Android Tablet
=> fix(UI): fix cursor property when hovering account nav items

package.json
Closes #4678
/cc @ericrosenbaum
=> chore(package): update scratch-vm to latest version

package.json, test/integration/backpack.test.js
Closes #4697
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> chore(package): update scratch-storage to version 1.3.1

src/components/cards/card.css, src/components/cards/cards.jsx
- Resolves #4668
Change tutorial video in iframe to be 466x265 to more closely match other tutorial steps.
=> Changing tutorial video width to be smaller

package.json
=> chore(package): update react-intl to version 2.8.0

package.json
=> chore(package): update scratch-l10n to version 3.2.20190417195644

package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> update scratch-blocks version

package.json
Closes #4770
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> chore(package): update scratch-l10n to version 3.2.20190424151256

package.json
Closes #4077
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> chore(package): update chromedriver to version 74.0.0

package.json
Closes #4774
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> chore(package): update scratch-l10n to version 3.2.20190501144004

src/containers/target-pane.jsx
Resolves https://github.com/LLK/scratch-gui/issues/1542
When you press the "surprise sprite" button,  the random sprite is selected after filtering all letters and numbers out of the library.
Because we have lots of letters in different fonts in the sprite library, unless we filter them out, the surprise sprite button would give you a letter about 25% of the time.
=> Surprise sprite button does not give you letters

src/components/cards/card.css, src/components/cards/cards.jsx
=> Revert "Revert "Pause video on tutorial window shrink""

package.json
Don't want to wait for the greenkeeper PR.
=> Update l10n to the latest version

package.json, src/containers/blocks.jsx, src/lib/define-dynamic-block.js, src/lib/make-toolbox-xml.js, test/unit/util/define-dynamic-block.test.js
Reverts LLK/scratch-gui#4940
Put back the e16n changes. Restore the version of vm to `0.2.0-prerelease.20190619042313` which corresponds to the version in gui with tag [0.1.0-prerelease.20190619221447](https://github.com/LLK/scratch-gui/blob/0.1.0-prerelease.20190619221447/package.json)
=> Revert "Revert "Merge pull request #4790 from LLK/e16n""

package.json
Update to bring in scrollbar touch accessibility and initial zoom scrollbars fixes
=> Bump scratch-paint version

package.json
This brings in the delete button fix for the numpad and Firefox block dragging fixes
=> Update blocks manually

package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Bump l10n version

package.json
This fixes the costume and sprite integration tests
See failed build at https://travis-ci.org/LLK/scratch-gui/builds/557064023
=> Revert to last good render

package-lock.json, package.json
Part of https://github.com/LLK/scratch-gui/pull/5002
=> Update paint to revert svg-renderer

package-lock.json, package.json
Update l10n to the version that includes Khmer and Georgian
=> Greenkeeper/scratch l10n 3.5.20190724160319

package-lock.json, package.json
Fixes https://github.com/LLK/scratch-paint/issues/866, which allows us to roll forward https://github.com/LLK/scratch-gui/pull/5002
Project 167167477 should not have question mark sprites and not crash the paint editor
Mac
Windows
Chromebook
iPad
Android Tablet
=> Roll forward scratch-svg-renderer

package-lock.json, package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Greenkeeper/scratch blocks 0.1.0 prerelease.1564581595

test/integration/sounds.test.js
Remove `.only` from one of the sound editor tests, which was preventing the other tests in that file from running
=> Remove test.only

package-lock.json, package.json
Pull in updates from scratch-render.
=> Greenkeeper/scratch render 0.1.0 prerelease.20190813154945

src/lib/libraries/decks/translate-video.js
Changes
- added Italian tutorial video Wistia links for all videos except Pong and Make it Fly
- added Portuguese tutorial video Wistia links for all videos except Glide Around, Pong, and Make it Fly
- added Portuguese (Brazilian) tutorial video Wistia links for all videos except Glide Around, Pong, and Make it Fly. Note that these are the same as 'pt' video links for now
=> Portuguese and italian

package-lock.json, package.json
Fixes https://github.com/LLK/scratch-gui/issues/5105
=> Revert render to last good version

package-lock.json, package.json
=> Greenkeeper/scratch l10n 3.5.20190827223456

package-lock.json, package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Greenkeeper/scratch l10n 3.5.20190910223701

src/lib/libraries/backdrops.json, src/lib/libraries/costumes.json, src/lib/libraries/sprites.json
Fixes https://github.com/LLK/scratch-gui/issues/4976
Fixes https://github.com/LLK/scratch-paint/issues/274
Fixes https://github.com/LLK/scratch-paint/issues/273
Thanks @kosiecki!
Update library assets for the items that were causing issues on Android
=> Fix assets that aren't working correctly in Android libraries

package-lock.json, package.json
Fix no tool selected when loading bitmap in paint
=> Greenkeeper/scratch paint 0.2.0 prerelease.20190923154429

package-lock.json, package.json
=> Greenkeeper/scratch vm 0.2.0 prerelease.20191001145300

package-lock.json, package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Greenkeeper/scratch l10n 3.6.20191008224547

package-lock.json, package.json
ensure that the correct version of l10n is included.
=> change l10n version to get swahili

package-lock.json, package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Greenkeeper/scratch render 0.1.0 prerelease.20191001200908

package-lock.json, package.json
=> Update paint to add swahili to overflow languages

package-lock.json, package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Greenkeeper/chromedriver 78.0.1

package-lock.json, package.json
=> Greenkeeper/scratch l10n 3.6.20191029224007

package-lock.json, package.json
=> Greenkeeper/scratch l10n 3.6.20191112223853

src/lib/libraries/decks/index.jsx
Reorder tutorials so that new tutorials for HOC 2019 (Imagine a World, Code a Cartoon, and Talking Tales) are close to top of tutorials library.
The top 6 tutorials should be, in order, 
- Getting Started
- Imagine a World
- Code a Cartoon
- Create Animations that Talk
- Talking Tales
- Animate a Name
=> Reorder tutorials for HOC 2019

package-lock.json, package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Greenkeeper/scratch l10n 3.6.20191120161253

package-lock.json, package.json
Update generated from https://github.com/LLK/scratch-gui/pull/5018
This involves a major version bump, so testing carefully
=> Greenkeeper/papaparse 5.1.1

package-lock.json, package.json
=> Greenkeeper/scratch l10n 3.7.20200108141814

src/containers/sound-editor.jsx, src/lib/audio/audio-util.js, test/__mocks__/audio-effects.js, test/unit/containers/sound-editor.test.jsx, test/unit/util/audio-util.test.js
Reverts LLK/scratch-gui#5338
/cc @ericrosenbaum @fsih bug with it in Safari
=> Revert "Implement sound downsampler to try to allow more sounds to be edited"

src/containers/sound-editor.jsx, src/lib/audio/audio-util.js, test/__mocks__/audio-effects.js, test/unit/containers/sound-editor.test.jsx, test/unit/util/audio-util.test.js
This is a fixed version of https://github.com/LLK/scratch-gui/pull/5338 which was reverted due to a bug that is fixed in 76f5cfe
=> [fixup] Implement sound downsampler to try to allow more sounds to be edited

package-lock.json, package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Update with render hotfix

package-lock.json, package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Greenkeeper/scratch paint 0.2.0 prerelease.20200129174741

package-lock.json, package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Greenkeeper/scratch paint 0.2.0 prerelease.20200204155336

package-lock.json, package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Greenkeeper/chromedriver 80.0.0

package-lock.json, package.json
=> Update paint to roll back centering tool

package-lock.json, package.json
Greenkeeper PR for yesterday's l10n release is missing - so this one is manual. Will merge as soon as tests pass
=> Update to latest l10n for translations

package-lock.json, package.json
- Resolves #
Mac
Windows
Chromebook
iPad
Android Tablet
=> Update render to roll back pen line drawing change

package-lock.json, package.json
#5501  had package-lock conflicts with the l10n PR
=> Updates scratch-blocks manually 

package-lock.json, package.json
This is the correct version of l10n to bring in the kurdish update.
=> Greenkeeper/scratch l10n 3.8.20200325112845

package-lock.json, package.json
=> Greenkeeper/scratch l10n 3.8.20200407213553

package-lock.json, package.json
scratch-blocks 0.1.0-prerelease.1586372076 updated translations
=> Update scratch-blocks to the latest version

src/lib/libraries/costumes.json, src/lib/libraries/sprites.json
The Bring Yourself into Scratch (BYIS) project has created several new people sprites, with many costumes, which we are adding to the sprite and costume libraries:
Characters 1
Characters 2
Kia
Luca
Noor
Sasha
Tatiana
Taylor
Trisha
=> Add new people sprites

.travis.yml
Updating the regex since we switched from greenkeeper.
=> Stop building gh pages branches for dependabot 

package-lock.json, package.json, test/integration/localization.test.js
Updates a localization test that was being flaky.  
- Resolves #
https://github.com/LLK/scratch-gui/issues/5619
It may not fully resolve it, but at least it removes unnecessary steps from the test that was timing out.
Removes unnecessary steps from the localization integration test that was failing sometimes from a timeout.
Updates the version of Chromedriver to the most recent version
Hopefully it will stabilize the tests.
=> Update localization test

src/lib/libraries/decks/index.jsx
Put tutorials in their regular order (during HOC, we placed the HOC tutorials at the top). 
High level changes: 
- Imagine a World was the 2nd tutorial in the HOC ordering: it is now the 3rd tutorial (after Getting Started and Animate a Name)
- Code a Cartoon, Create Animations That Talk, and Talking Tales have moved down
New order
- Getting Started
- Animate a Name
- Imagine a World
- Make Music
- Create a Story
- Make a Chase Game
- Animate a Character
- Make a Clicker Game
- Make it Fly
- Pong Game
- Code a Cartoon
- Animate an Adventure Game
- Video Sensing
- Create Animations That Talk
- Talking Tales
- Add a Sprite
- Add a Backdrop
- Change Size
- Glide Around
- Record a Sound
- Spin 
- Hide and Show
- Animate a Sprite
- Move Using Arrow Keys
- Add Effects
=> Reorder tutorials to their order pre-HOC

README.md
- Resolves https://github.com/LLK/scratch-gui/issues/5995, at least for now
Adds section on troubleshooting to README
=> add troubleshooting section to README
