LLK/scratch-gui

- src/lib/vm-manager.js
This is mostly because it was annoying that Cmd-Opt-J didn't work, but seems like a good thing to have in general.
> Don't block keys intended for the browser

- package.json
- webpack.config.js
The previous method of configuring the port number was not cross-platform.  Resolves #20
> Configure port through webpack, not npm

- src/components/library/library.jsx
- src/containers/stage.jsx
This gets scratch-gui a bit more in line performance-wise with the scratch-vm playground.
Caching the stage bounding box prevents layout recalculations on every mouse event.
Don't render the contents of the libraries until they're actually visible. This was especially expensive now that we're listening to every `spriteInfoReport`. Further optimizations to the VM event listeners should come later.
> Cache stage bounding box and avoid unnecessary library rendering

- .travis.yml
- webpack.config.js
This improves React performance by skipping prop type checks and warnings.
PR #62 was hanging in Travis due to a problem with an upstream dependency.
> Build in production mode for gh-pages

- src/containers/blocks.jsx
- src/lib/blocks.js
/ht @rschamp
Addresses https://github.com/LLK/scratch-audio/issues/25
Update the Blocks component to receive a patched version of ScratchBlocks. The patched version receives a reference to the VM from the Blocks component. 
We use the reference to the VM to create a dynamic Blockly menu containing the names of the sounds of the editing target.
> Monkeypatch dynamic sound menu into ScratchBlocks

- src/containers/blocks.jsx
- src/lib/blocks.js
Addresses LLK/scratch-audio#25
The toolbox refreshes itself on workspace update.
The contents of the sound menu now change to reflect the sounds in the target you switch to.
In the earlier, larger monkeypatch, we included a dummy menu item that appears first ('select...'), to cover up the fact that the menu was not updating when you switch targets. This is no longer necessary. 
"The pygmy marmoset is a small New World monkey native to rainforests of the western Amazon Basin in South America. It is notable for being the smallest monkey and one of the smallest primates in the world at just over 100 grams." [wikipedia](https://en.wikipedia.org/wiki/Pygmy_marmoset)
> PygmyMarmosetPatch for sound menu updates on workspace update

- src/lib/blocks.js
https://github.com/LLK/scratch-vm/issues/418
The menus that list costume and backdrop names update when you switch targets. 
The menus now show the names of costumes and backdrops for the sprite or stage selected.
> Dynamic menus for costumes and backdrops

- src/lib/blocks.js
_Part of LLK/scratch-blocks#749_
_Adds sprites to drop-down menus in the same way #80 did_
_So you can actually select sprites in drop-down menus to interact with them._
> Add sprites to drop-down menus

- src/lib/blocks.js
Addresses https://github.com/LLK/scratch-gui/issues/101
If the sound array is empty, populate the sounds menu with a single entry containing an empty string. 
Currently, if you load a sprite with no sounds, there's an error and the sound blocks disappear.
> Check for empty sound array

- src/containers/blocks.jsx
Resolves #16
Utilize the `filterToolbox` method now available from https://github.com/LLK/scratch-vm/pull/461
> Filter toolbox to blocks available to the VM

- src/components/target-pane/target-pane.jsx
Resolves GH-100
Remove errant conditional logic for backdrop / costume modal
Backdrop "+" button should always cause the backdrop library modal to be displayed and should not depend on the user's sprite / backdrop selection state.
> Remove errant conditional logic for backdrop / costume modal

- src/components/sprite-selector/sprite-selector.css
The right edge of the Stage Selector isn't vertically aligned with the right edge of the Stage above it.
In  #134, we made StageSelector a fixed width for now, to 72px, to match design spec. 
Forgot to update`flex-grow` on the StageSelector to explicitly have it take up the available width.
I was testing projects during dev with ~15 sprites, thinking it wouldn't render differently with less sprites. Note to self: check projects with various numbers of sprites when submitting a PR involving layout updates.
> StageArea: fixed space near edge, on projects with less than 1 row of sprites

- package.json
- src/components/sprite-info/sprite-info.css
- src/components/sprite-info/sprite-info.jsx
- src/components/sprite-selector/sprite-selector.jsx
- src/components/target-pane/target-pane.jsx
- src/containers/sprite-info.jsx
- src/containers/target-pane.jsx
- src/index.jsx
- src/reducers/targets.js
Sets up sprite info component to reflect data about the selected sprite in the panel.
In the interest of time:
* Every field is updated as you type, including x/y position. Typing `-` is interpreted as `-1`. Eventually this should only happen on blur or enter key pressed.  Good luck trying to update position while a sprite is moving 🙃 
* When you select the stage, the sprite info pane becomes disabled, with placeholder values set in the inputs
* Everything is handled with props passing. This is a good place for redux, but I needed it to be done for the play test tomorrow.
* I did minimal performance testing. I would not be surprised if some projects perform more slowly after this update.  I believe the redux refactor could help with this, since it would reduce the number of parent …
> Wire sprite info panel to VM

- src/components/sprite-info/sprite-info.jsx
- src/containers/sprite-info.jsx
Changes to the name, x, or y fields should only be sent to the VM when the field is blurred or when enter is pressed.
Still allow updates while the fields are focused, but unchanged.
Fixes #154
/cc @carljbowman
> Buffer sprite info text fields

- src/containers/blocks.jsx
Reverts LLK/scratch-gui#135
With https://github.com/LLK/scratch-blocks/pull/830 this hackiness is no longer needed.
> Revert "Filter toolbox to blocks available to the VM"

- src/lib/libraries/sprites.json
Fixes #220
To be clear this is a _short term_ fix.
I did this manually by inserting this goofy code into the renderer just after [this line]( https://github.com/LLK/scratch-render/blob/bbffee7bfdfd4b62cff73266393110707d542f0a/src/svg-quirks-mode/svg-renderer.js#L264). Then opened project id 149405222 in the GUI, which downloaded all the fixed SVGs. Then I uploaded those as costumes into a Scratch project, and got the "fixed" asset IDs to use in the library:
```javascript
const blob = new Blob([svgText], {type: 'image/svg+xml'});
const link = document.createElement('a');
link.download = 'story.svg';
link.href = window.URL.createObjectURL(blob);
link.onclick = function (e) {
setTimeout(
function () {window.URL.revokeObjectURL(this.href)}.bind(this),
1500
)
};
link.click();
link.remove(); …
```
> Fix story letter SVGs in the sprite library

- src/containers/blocks.jsx
@rschamp just wanted to publish this as a starting point for discussing if this is the right way to go. 
_update: talked with @carljbowman  and @rschamp  about how this behavior varies from 2.0 behavior. Trying to follow principle of least surprise, this seems least surprising and addresses the test of issue #187 the best. We can see at the next user test if it is actually !surprising._
https://github.com/LLK/scratch-gui/issues/187
Adds in listeners on `workspace.translate` and `workspace.zoom` that store the `scrollX, scrollY, scale` properties of the workspace in the state of the blocks container, keyed by target id. It restores these properties and triggers a refresh whenever the …
> Store the scroll/zoom of the workspace on a per-target basis

- src/containers/blocks.jsx
First iteration of a background pattern, fixes https://github.com/LLK/scratch-blocks/issues/817
Note this pattern isn't actually what was given in that issue. This just uses what scratch-blocks already offers as a starting point to create something similar without approaching the issues mentioned in the comments of https://github.com/LLK/scratch-blocks/issues/817
cc @thisandagain @carljbowman
> Add simple blocks background pattern

- src/components/close-button/close-button.css
- src/components/gui/gui.css
- src/components/menu-bar/menu-bar.css
- src/components/modal/modal.css
- src/components/sprite-info/sprite-info.css
- src/components/sprite-selector-item/sprite-selector-item.css
- src/components/stage-selector/stage-selector.css
- src/components/target-pane/target-pane.css
Fixes #162 for Chrome + Firefox.
- Affects: SpriteSelector Pane, StageSelector Pane, Stage, MenuBar, Libraries Modal, Add/Import buttons
- This update does not fix issue on Edge.
- `SpriteSelector` pane is still broken in Safari, but this is related to #105. Once that is fixed, this might resolve without further updates needed.
> Made UI elements non-selectable

- src/components/blocks/blocks.css
This is a simpler and more flexible way to fix the UI issues with the scratch-block borders. Instead of changing it in scratch-blocks and needing to support many orientations, for now just do it in the GUI. There is precedent for this, since we are doing the rounded edge in GUI also.
Before:
After:
css @carljbowman @lifeinchords
> Fix block editor borders 

- package.json
- src/components/gui/gui.jsx
- src/containers/blocks.jsx
- src/containers/stage.jsx
- src/lib/storage.js
- src/lib/vm-listener-hoc.jsx
This is the GUI side of LLK/scratch-vm#427
This change causes the GUI (specifically, the stage container) to:
1. create an instance of `ScratchStorage`, storing a reference locally,
2. add two standard web sources to the storage module, and
3. give the storage module instance to the VM.
There are several places in the GUI that could use the storage module for file access; those are not yet updated to use this module but they could be.
This is the minimum necessary to make it safe to merge LLK/scratch-vm#498
> Use scratch-storage

- src/containers/blocks.jsx
- src/containers/green-flag.jsx
- src/containers/stop-all.jsx
Fixes https://github.com/LLK/scratch-gui/issues/256
`.on` is an alias for `.addListener`[1], but there is no alias for `.off` and it looks like there never will be [2] :( :( :( 
[1] https://github.com/nodejs/node/blob/master/lib/events.js#L307
[2] https://github.com/nodejs/node/pull/540
> Change #off to #removeListener

- src/components/asset-panel/selector.jsx
- src/components/close-button/close-button.jsx
- src/components/costume-canvas/costume-canvas.jsx
- src/components/green-flag/green-flag.jsx
- src/components/library-item/library-item.jsx
- src/components/library/library.jsx
- src/components/modal/modal.jsx
- src/components/sprite-selector-item/sprite-selector-item.jsx
- src/components/sprite-selector/sprite-selector.jsx
- src/components/stage-selector/stage-selector.jsx
- src/components/stop-all/stop-all.jsx
- src/containers/costume-tab.jsx
- src/containers/sound-tab.jsx
This PR adds more `.isRequired` validations to the prop types of components. These should be used whenever the prop is actually required. It will help us with debugging and catching bugs when reviewing, as well as for testing. 
There are a few new proptype validation errors you'll see from this: 
- `.image is undefined` (costume tab doesn’t render images)
- `costumeURL is undefined` (sprite selector doesn’t render images)
Those are actual bugs introduced by `scratch-storage`, so they can be fixed separately. 
---
_Note:_ I have in general left out `isRequired` from function props on components that are wrapped directly by containers. The pattern we use for proptypes on containers would have required a fairly large refactoring. Since those wouldn't have caught any bugs, I'm going to leave …
> Stricter PropType validation

- src/components/sprite-info/sprite-info.jsx
When the sprite's x/y are numeric, the string type was throwing a warning.
> Fix warning from SpriteInfo on initialization

- src/containers/sound-tab.jsx
Fixes https://github.com/LLK/scratch-gui/issues/299, showing the sound icon again in the sounds list.
> Fix audio images in sounds tab

- src/containers/stage.jsx
#308
Previously, it was possible to drag a sprite even when the mouse cursor did not start on the sprite. This change saves the mouse position on mousedown and adds an extra check to ensure this does not happen.
Fixes bug in #308.
N/A
> Fix dragging sprite only when mousedown starts on sprite

- src/containers/stage.jsx
#260
Double-clicking a sprite in the stage now focuses the editing target to that sprite.
Added feature present in 2.0.
N/A, tested locally
> Set editing target when double clicking on sprite in stage

- src/containers/costume-tab.jsx
- src/containers/sound-tab.jsx
Fixes https://github.com/LLK/scratch-gui/issues/280
Make rendering costume and sound tab lists use data passed in through redux instead of reaching into the VM. 
Reaching into the VM breaks the module boundaries and can result in unexpected problems. 
**Note**: the sound and costume tabs still reach into the VM to delete costumes, because there is no public API from the VM for that yet. And the issue with deleting sprites seems to still exist.
n/a
> Use sprite info for costumes and sounds

- src/containers/sound-library.jsx
- src/lib/storage.js
Resolves #320 
Access `Asset` and `AssetType` through an instance of ScratchStorage. Remove a now-unnecessary instance of `require('scratch-storage')`.
Accessing `Asset` and `AssetType` as properties of `ScratchStorage` instead of an instance is deprecated as of LLK/scratch-storage#9. Accessing them through an instance ensures consistency between the storage runtime code and the values and objects being used with it, and allows for the possibility of a dynamic asset type list in the future.
> Get `Asset` and `AssetType` from storage instance

- src/components/stage-selector/stage-selector.css
- src/components/stage-selector/stage-selector.jsx
Fixes #140, follow up on discussion from #285. 
Use 4x3 aspect ratio on stage thumbnail to prevent blank space at the top. Also fix border radius mismatch by using overflow: hidden; on the container with the border-radius.
> Fix whitespace canvas

- src/index.jsx
If the app is loading with an initial project id, don't try to load the default project. Previously, this default data would load on top of the project being loaded.
Does not fix the issue of blocks not loading in the blocks pane, which appears to be separate.
> Stop clobbering loading projects with default data

- src/components/prompt/prompt.css
- src/components/prompt/prompt.jsx
- src/containers/blocks.jsx
- src/containers/prompt.jsx
A simple first iteration of a new variable prompt. I wanted to get some feedback on the way this is implemented @rschamp. (The css definitely needs some work, and I avoided the header bar from the mockup because there isn't the data to fill it). 
_Update:_ Added the prompt header and refactored container/component divide.
Fixes https://github.com/LLK/scratch-blocks/issues/535
> Add prompt for variable creation

- src/containers/green-flag.jsx
https://github.com/LLK/scratch-gui/issues/332
Enable turbo mode when shift clicking the green flag. No UI indicating that turbo mode is on or off yet.
> Toggle turbo mode when shift clicking the green flag

- package.json
- src/components/monitor-list/monitor-list.css
- src/components/monitor-list/monitor-list.jsx
- src/components/monitor/monitor.css
- src/components/monitor/monitor.jsx
- src/components/stage/stage.css
- src/components/stage/stage.jsx
- src/containers/monitor-list.jsx
- src/containers/monitor.jsx
- src/reducers/gui.js
- src/reducers/monitors.js
Initial front-end for monitors including a reducer for updating monitors, an stage-overlayed component that displays monitors and draggable monitor components that emit position events at the end of their drags. 
You can add monitors through the redux console by dispatching this event:
```
{
type: 'scratch-gui/monitors/UPDATE_MONITORS',
monitors: [{
id: 'var1',
category: 'data',
label: 'Variable',
value: '123',
x: 20,
y: 40
}, {
id: 'var2',
category: 'motion',
label: 'Variable2',
value: '123123123',
x: 200,
y: 100
}]
}
```
> Add reducer, components and containers for monitors

- src/components/stage/stage.css
Fixes https://github.com/LLK/scratch-gui/issues/341
Add `pointer-events: none` to the container.
Allow pointer events to fall through the overlay
> Allow pointer events to fall through the overlay

- src/components/asset-panel/selector.jsx
- src/components/sprite-selector/sprite-selector.jsx
- src/components/target-pane/target-pane.jsx
- src/containers/sprite-selector-item.jsx
- src/containers/stage-selector.jsx
- src/lib/vm-listener-hoc.jsx
- src/reducers/gui.js
- src/reducers/vm.js
When the VM stops sending costume data over in sprite info reports and target updates, the sprite thumbnail image data need to be retrieved from storage.
To make this easier to do, I moved the vm into a reducer, and connected the relevant components to it, so that they convert asset ids into data.
Requires https://github.com/LLK/scratch-vm/pull/552
/cc @thisandagain @cwillisf
> Integrate VM serialization changes

- src/containers/costume-tab.jsx
- src/lib/vm-listener-hoc.jsx
- src/reducers/targets.js
This reduces the complexity of the reducer, as well as how frequently it's run. The VM will emit a targets update after a step if any target info has changed.
Resolves https://github.com/LLK/scratch-vm/issues/550. Brings the "medium complexity" project to comparable performance of the VM playground.
Stop listening to `SPRITE_INFO_REPORT`, since as of https://github.com/LLK/scratch-vm/pull/563 the VM isn't emitting them anymore.
A lot of time is spent in the reducer merging sprite info into the GUI's target list. Instead just use the current state of the list from `targetsUpdate`, which now is emitted each step which modifies target data.
Before …
> Only listen to targets updates

- src/components/gui/gui.jsx
- src/containers/blocks.jsx
- src/containers/gui.jsx
Resolves https://github.com/LLK/scratch-gui/issues/270
Makes https://github.com/LLK/scratch-gui/issues/358 less bad
When switching off the scripts tab, make it not visible. When switching onto it, make it visible, and reload the scripts. This means that UI from the scripts tab won't accidentally be visible in other tabs (like menus on blocks), and the scripts tab text length will be measured correctly when you re-open it.
Also does some clean-up in gui.jsx moving the handle tab change logic into the container.
> Fix squashed blocks in flyout when adding a sprite while on another tab

- src/components/library-item/library-item.css
- src/components/library-item/library-item.jsx
- src/containers/costume-library.jsx
- src/containers/sound-library.jsx
- src/containers/sprite-library.jsx
Use the new mouseenter and mouseleave hooks to cycle through a sprites costume when it is hovered over. 
Note that as shown in the gif, if a sprites costume does not have the correct svg positioning, it will not show or it may show off center. That is a separate issue that we will have to deal with.
> Use library mouseenter and mouseleave to cycle sprite costumes

- src/components/library-item/library-item.jsx
Fixes https://github.com/LLK/scratch-gui/issues/393
Instead of only checking for iconURL changes, check all props for `shouldUpdate` by using `PureComponent` (reference: https://facebook.github.io/react/docs/react-api.html#react.purecomponent)
With filtering, the other props can change! See https://github.com/LLK/scratch-gui/issues/393 for an explanation of the resulting bug.
> Use PureComponent and remove incorrect shouldComponentUpdate call

- src/lib/libraries/sprites.json
Fixes https://github.com/LLK/scratch-gui/issues/398
Puts the letter blocks back at the end of the sprite list, like they were (and are on the costume list).
They were promoted for the "Animate your name" playtest, but need to be put back to the default for our next playtest
n/a
> Put letter blocks back at the end of the sprites list

- src/components/gui/gui.css
Updates border bottom color of selected tab to the same color as the background of what's under it, to better show what's selected/unselected
Depends on #396 to keep the width set
> Made selected tab more prominent

- src/components/gui/gui.css
Fixes https://github.com/LLK/scratch-gui/issues/318
Hide overflow-y around the container of the blocks to prevent the border popping issue.
> Hide overflow-y on gui container

- src/containers/blocks.jsx
Fixes this error you get when dragging a sprite around with a category other than motion open:
Didn't realize that when you are on a different category, those blocks actually just do not exist.
> Check if blocks exists before updating values

- src/containers/blocks.jsx
Fixes the common cases of https://github.com/LLK/scratch-blocks/issues/912. But see my long comment at the end of that bug for a full description. 
TL;DR don't trigger a window resize before making the workspace visible.
> Show workspace before triggering resize

- .travis.yml
This allows gh-pages to work. Something changed in the precise VMs that prevents the git clone gh-pages uses from working correctly.  See https://github.com/travis-ci/travis-ci/issues/4942
On my fork, this change allowed the gh-pages deploy to succeed.
/fyi @paulkaplan @fsih
> Use trusty beta for Travis builds

- src/components/modal/modal.jsx
Fixes https://github.com/LLK/scratch-gui/issues/425
Pass `onRequestClose` to the react modal. It can handle escape-to-close automatically if you give it something to do when escape is hit. We already do this in the `Prompt` component.
Escape-to-close is a common expectation. @lifeinchords we have talked about implementing this, turns out it is a one-liner :)
> Make escape key exit library modals

- src/containers/blocks.jsx
Disable code comments by passing a `comments: false` into scratch-blocks.
This disables the "add comment" option in the right click menu.
Commenting is not implemented in the VM and there is no design for it, so disable it the same way the playgrounds do.
> Use `comments` flag to disable comments in scratch-blocks

- .travis.yml
- package.json
- src/components/gui/gui.jsx
- src/index.jsx
- webpack.config.js
Check out the results of this PR build here! https://rschamp.github.io/scratch-gui/deploy/multi-branch/
I assigned everyone who might be interested in this change, since we may want something like this change in other repos (www?). Not everyone has to review it though.
_Currently this works using an unmerged PR to tschaub/gh-pages. (Will update to an LLK fork if we decide to go this way until that PR is merged.)_
When deploying from Travis, push all branches except master to a subdirectory. So the build for master would be available at https://llk.github.io/scratch-gui/ but to view the build for e.g., develop, you would look at https://llk.github.io/scratch-gui/develop/.
As part of this change, stop building for multiple versions of Node, since everything is static. This allows us to get …
> Deploy all branches but master to subdirectories

- src/containers/blocks.jsx
Goes with https://github.com/LLK/scratch-vm/pull/611
Workaround for blocks bug https://github.com/LLK/scratch-blocks/issues/929
Refresh workspace when changing to scripts tab
> Refresh workspace when setting it to visible

- src/lib/libraries/sprites.json
Fixes https://github.com/LLK/scratch-gui/issues/449
Add the "Pop" sound to every sprite that doesn't have any sounds. In the future this should probably be revised to make the sounds more useful, but this is a good starting place. 
This is available live on my fork at https://paulkaplan.github.io/scratch-gui/add-pop-to-all-sprites
> Add pop sound to all sprites without sounds

- src/containers/blocks.jsx
Reverts LLK/scratch-gui#390
We no longer need to explicitly create variables in the VM, since the VM will be bound directly to scratch blocks pending https://github.com/LLK/scratch-vm/pull/614
> Revert "Explicitly create variables in the VM"

- src/containers/costume-tab.jsx
#474
Sets the active sprite's costume (in the VM) when a costume is selected in the costumes tab.
To behave as Scratch 2.0 does.
(No tests.)
> Set costume when selected in costumes tab

- src/lib/audio/shared-audio-context.js
Fixes white screen in Safari (and possibly old Chrome) caused by use of `AudioContext`
I didn't bother to open an issue
Uses `webkitAudioContext` when `AudioContext` is not found
Because people use Safari
???
> Fix AudioContext issue in Safari

- src/components/target-pane/target-pane.jsx
In order to comply to WCAG 2.0[1], buttons must have discernible text that
clearly describe the purpose, so that it can be used by screen readers.
[1] https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H65
> "Add sprite/backdrop" buttons should have a discernible text

- src/components/buffered-input/buffered-input.jsx
- src/components/sprite-info/sprite-info.jsx
- src/containers/sprite-info.jsx
This PR extracts the "buffered input" logic from the sprite info container into a component so that it isn't repeated many times. The new `BufferedInput` component wraps a regular `input` (you can pass `disabled`, `placeholder` and other `input` props) but replaces the fine-grain events like `onBlur`, `onChange` and `onKeyPress` with a single callback `onSubmit` which is triggered on blur/enter key. 
`BufferedInput` can handle numbers and strings with basic `!isNaN()` validation when the `value` prop is a number. `onSubmit` is passed a number or a string based on what the original`value` prop was. (note: this fixes a minor bug where we were submitting the x/y positions as strings instead of numbers).
We will …
> Refactor buffered inputs for sprite info

- src/components/record-modal/record-modal.css
- src/components/record-modal/recording-step.jsx
- src/containers/recording-step.jsx
- src/lib/audio/audio-recorder.js
Fixes https://github.com/LLK/scratch-gui/issues/503
Disable the record button (and gray it out) before mic access is given.
It should not be possible to start the recording before mic access is given. This doesn't really address the design problem mentioned in that issue, let's make a separate issue for that. 
@carljbowman thoughts? this is what it looks like
Note: the button is actually disabled, it cannot be clicked.
> Disable record button before mic access is given

- src/components/target-pane/target-pane.css
solved #108 add button not centered in Firefox
There could be 2 ways in solving this:
1. adding "margin: auto" to center the img displayed in block;
2. turn the img to flexbox and center it with align-items.
I tried to do 2. But it somewhat does not work in Firefox (an issue in Firefox?). 
So I fallback to 1.
no link issue emerges
> fix #108 add button is not centered in firefox

- src/components/gui/gui.jsx
GH-497
- Changes the "Scripts" tab to "Blocks"
- Resolve inconsistency and confusion observed during play testing
- None
> Change 'Scripts' tab to 'Blocks'

- src/components/asset-panel/selector.jsx
- src/containers/costume-tab.jsx
- src/containers/sound-tab.jsx
Keep localization in the container level. Ideally we should not be passing message descriptors.
#524 
Avoids passing message descriptors to a component. Translatable strings should be handled in the place where they're defined.
As example usage, AssetPanel no longer needs react-intl, all the translation is handled in the sound-tab and costume tab.
> Revise localization calls

- src/lib/vm-listener-hoc.jsx
There was a place where we expected to be able to import the action creators as part of the reducer object that I missed in the import/export refactor I merged today. That broke develop slightly. 
Fixes that problem.
> Fix reducer imports

- scripts/generate-locale-messages.js
- src/components/language-selector/language-selector.jsx
- src/languages.json
- src/locale.js
- src/reducers/intl.js
#557 
move all locale data (react-intl/locale-data and gui messages) into locale.js. This also makes switching to an external node package easier because the package just needs to export the same thing as locale.js.
> localeData cleanup

- src/containers/sound-editor.jsx
- src/containers/sound-library.jsx
Update the way sounds are played in the library to work with these audio engine changes https://github.com/LLK/scratch-audio/pull/57. 
Now the audio engine returns a `soundId` that must be used to play the sounds instead of being played by "md5". 
See the attached issue for more context.
> Use sound ID coming back from decodeSound

- src/containers/blocks.jsx
Change default zoom (`startScale` for blockly) to 0.675 from 0.75. This is what that looks like (new on the left, old on the right, at 1280x800 window size, non-retina screen):
cc @carljbowman @thisandagain
> Change default block zoom to 0.675 from 0.75

- src/components/language-selector/language-selector.css
#564 - Language selector options were invisible until hovered over
Changes the text color to black, while keeping the background color as white
So that language menu options can be instantly seen, instead of having to hover over each one to find your language.
> Fix color conflict

- src/components/asset-panel/selector.jsx
- src/components/icon-button/icon-button.css
- src/components/icon-button/icon-button.jsx
- src/components/target-pane/icon--backdrop.svg
- src/components/target-pane/icon--sprite.svg
- src/components/target-pane/target-pane.css
- src/components/target-pane/target-pane.jsx
- test/unit/components/__snapshots__/icon-button.test.jsx.snap
- test/unit/components/icon-button.test.jsx
One part of https://github.com/LLK/scratch-gui/issues/514
Extract out and reuse the `IconButton` pattern as a component. Use it along with the new icon images for the "add sprite" and "add backdrop" buttons
Added snapshot and callback testing for the new component. 
---
/cc @chrisgarrity another translated component! One thing that ray and I talked about briefly was that this technically includes the same string as the other `addBackdropMessage`, but since it might change in the future and we couldn't do that without breaking the translation, we decided to use different ideas. That makes me think that (contrary to what I said when …
> Add new icons for sprite and backdrop buttons

- package.json
- src/components/forms/input.css
- src/components/gui/gui.css
- src/components/gui/gui.jsx
- src/components/sprite-info/sprite-info.css
- src/components/sprite-info/sprite-info.jsx
- src/containers/stage.jsx
- src/lib/layout-constants.js
Fixes https://github.com/LLK/scratch-gui/issues/579 by shrinking the stage and some minor changes to the sprite info area (hides icons, makes inputs slightly smaller). 
Depends on https://github.com/LLK/scratch-render/pull/154
Still have to review these changes with @carljbowman, but the in-progress idea is to shrink the stage and to do a bit of responsive work on the sprite info area to fit everything into 1024 layout. 
Note in the code the width of the break is actually 1096, because that is where it was previously breaking. If we put the break at 1024, it would work for [1024, 1096+], but this way it works for 1024+. 
Explained in …
> Allow GUI to fit into 1024px screen widths

- package.json
- src/components/context-menu/context-menu.css
- src/components/context-menu/context-menu.jsx
- src/components/sprite-selector-item/sprite-selector-item.jsx
- test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
- test/unit/components/sprite-selector-item.test.jsx
- test/unit/containers/sprite-selector-item.test.jsx
Part of implementing https://github.com/LLK/scratch-gui/issues/224. Specifically, the context menu with the delete menu item. Duplicate menu item will take VM work, so this is just the structure of the context menu.
Using the `react-contextmenu` package, wrap the sprite selector in a `ContextMenuTrigger` and include a `ContextMenu` with the delete menu item. 
The `react-contextmenu` package includes no styling, so I created a custom `ContextMenu` and `MenuItem` that just inject custom classnames/styles into the components provided by `react-contextmenu`. 
This will be the pattern we use for context menus throughout the app. 
_Please show how you …
> Context menu

- package.json
Fixes the "peer dependency missing" errors that were being caused by greenkeeper updating the peer dependencies but not the other dependencies.
> Update all react deps to most recent version

- src/components/audio-trimmer/audio-trimmer.css
- src/components/audio-trimmer/audio-trimmer.jsx
- src/containers/audio-trimmer.jsx
- src/containers/stage.jsx
- src/lib/touch-utils.js
- test/unit/components/__snapshots__/sound-editor.test.jsx.snap
Make the audio trimmers and stage work with touch events!
In addition to getting the trimmers and sprite dragging on the stage to work, this also makes all of the related mouse blocks work, so also fixes https://github.com/LLK/scratch-gui/issues/591.
> Enable touch events for the stage and audio trimmers

- package.json
fixes #630 
Run node explicitly: `#! …node` in the script doesn’t work on windows.
> Script update for windows

- src/components/gui/gui.css
Fixes https://github.com/LLK/scratch-gui/issues/640
Adds a max width (and helpful comment to future us) about sizing the sprite selector. 
See screenshots in linked issue. 
No tests, but here is a screenshot before and after
> Add max width to fix flex-grow errors

- src/containers/sound-tab.jsx
https://github.com/LLK/scratch-gui/issues/604
The editingTarget might be null when loading new project, while target will not be null (it will be the state):
const target = editingTarget && sprites[editingTarget] ? sprites[editingTarget] : stage;
Fixed the project load error caused by sound editor.
> Fixed #604: Load project error

- src/lib/blocks.js
Resolves https://github.com/LLK/scratch-gui/issues/639
When updating menus on blocks that require information from the current editing target (names of costumes, backdrops, or sounds), avoid an error by checking first in case none is present.
The toolbox can be loaded before the GUI, so the editing targets are not yet present at the first update.
No tests yet.
> Check for sprites before trying to update block menus

- src/lib/blocks.js
LLK/scratch-gui#598
Adds the `init` function for the glideto’s menu.
Comes with LLK/scratch-blocks#1046 and LLK/scratch-vm#662
> Add glideto menu

- src/components/gui/gui.jsx
- src/components/library/library.jsx
- src/components/modal/modal.jsx
- src/components/prompt/prompt.jsx
- src/components/record-modal/record-modal.jsx
- src/components/target-pane/target-pane.jsx
- src/containers/backdrop-library.jsx
- src/containers/costume-library.jsx
- src/containers/record-modal.jsx
- src/containers/sound-library.jsx
- src/containers/sprite-library.jsx
This is a performance improvement. Reduces tick timing from ~30ms to ~18ms on my machine (in development). Also a generally good idea to not render components that aren't visible. 
Before
After
Instead of passing `isVisible` to the library / tab components, just do not render them if they are not visible. 
The change from `Box` to `div` is because box wasn't being used for anything in particular, and it makes debugging harder.
> Do not render invisible components

- src/containers/recording-step.jsx
Fixes the broken build on develop that came from a minor version update in eslint. 
Be explicit with react proptypes, even if it involves copy/pasting :( 
Because the build was failing.
They pass now
---
Maybe worth noting that because the eslint version is not pinned to a specific version, develop was passing when the last merge was done, but something caused subsequent builds to use an in-range update to eslint, which then failed (probably because another PR updated the node_module cache?)
> Fix eslint error from prop types

- package.json
Travis seems to not like the way jest tries to run the tests in serial. Not sure if that is caused by a chromedriver update or a jest update. But using the `--runInBand` flag seems to make the tests stable again.
> Fix travis problems

- src/containers/audio-trimmer.jsx
Fixes https://github.com/LLK/scratch-gui/issues/590 by preventing it from being possible to overlap the trimmers.
Set a minimum trimmable length so that trimmers cannot overlap. 
Consulted @carljbowman, seems like a simple way to prevent the problem and avoid questions of what should happen by preventing it from happening in the first place.
> Add minimum trimmable length for audio trimmer

- package.json
Do this manually because greenkeeper failed due to other broken build issues. 
Resolves https://github.com/LLK/scratch-gui/issues/680
> Update webpack to 3.6.0

- src/components/loupe/loupe.css
- src/components/loupe/loupe.jsx
- src/components/stage/stage.css
- src/components/stage/stage.jsx
- src/containers/blocks.jsx
- src/containers/stage.jsx
- src/reducers/color-picker.js
- src/reducers/gui.js
Resolves https://github.com/LLK/scratch-gui/issues/649
3 main parts:
1. A reducer and associated actions for handling the color picker state. 
2. Connecting the actions to scratch-blocks
3. The loupe component that draws the result of `renderer.extractColor` to a magnifying glass over the stage.
---
> Eyedropper color picking tool

- package.json
We removed the integration tests from `npm test`, which also removed `npm run build`. This adds it back so that develop can deploy again.
> Add npm run build to the test to cover for removed integration tests

- src/containers/blocks.jsx
- src/lib/make-toolbox-xml.js
Resolves https://github.com/LLK/scratch-gui/issues/732
Always load the toolbox contents from the Scratch-gui toolbox XML. 
This PR also includes fixes to the existing toolbox XML to re-order the categories to spec, and to not omit the new "glide to" and pen transparency blocks.
The toolbox was initially loaded from the Scratch-blocks default toolbox, which is now different from the Scratch-gui toolbox.
> Sync toolbox

- src/lib/make-toolbox-xml.js
Progress on https://github.com/LLK/scratch-gui/issues/603
Add a "top" category containing a set of commonly used blocks.
Note that this change omits the "say hello for 2 secs" block, because it is not yet implemented. 
Also note that this new category will not be visible on load until we merge https://github.com/LLK/scratch-gui/pull/733
See https://github.com/LLK/scratch-gui/issues/603
> Add “top” category to toolbox xml

- package.json
- test/helpers/selenium-helper.js
- test/integration/test.js
Fixes https://github.com/LLK/scratch-gui/issues/727 and restores integration tests to the build process.
Fixes the problem with the integration tests. They were not flaking out, they were responding to a real change in the GUI: the strings used for `clickText` were no longer unique on the page, and their first instance (inside the now rendered looks blocks) were indeed invisible. I used the tab ids to create scoping for the `clickText` selenium helper. 
Integration tests are very important! As demonstrated by yesterdays broken deploy :( 
`npm run test` works locally, hopefully will on …
> Fix selenium tests

- src/lib/make-toolbox-xml.js
Add say and think blocks to the "Looks" category. Also add "say for secs" to the "Top" category as per https://github.com/LLK/scratch-gui/issues/603
These blocks won't work until the implementations in vm and render are merged, but the work was done so I figured I might as well submit it. It won't cause any harm (just won't do anything).
> Add say and think blocks to the toolbox XML

- src/containers/stage.jsx
Issue 701 (https://github.com/LLK/scratch-gui/issues/701)
I have added an if statement to check what click is being used when clicking on the sprite. If it is a right click, the sprite is unable to be dragged.
Before this change the user could right click the sprite, and then left click on the stage and the sprite would be dragged to where you left clicked, causing unexpected behavior.
All npm test test cases passed, this is a very small change so I did not see additional tests necessary.
> Fixed issue causing right click to drag sprite. 

- src/containers/costume-tab.jsx
- src/containers/paint-editor-wrapper.jsx
Breaks out a new component between the costume tab and the paint editor. This wrapper implements shouldComponentUpdate so that when it receives an updated SVG from the paint editor, it doesn't immediately push that SVG back to the paint editor. When an SVG is pushed, the paint editor state gets reset, since it expected a sprite or costume change to cause the push.
> Add a paint editor wrapper which only rerenders when necessary

- src/containers/blocks.jsx
Previous issues (#413) required manually refreshing the scratch-blocks workspace. It is now dealt with from within scratch-blocks, so these manual calls need to be removed for performance-sake. This removes two unnecessary calls when switching between costume/sounds => blocks tab, and one unnecessary call when switching between sprites. Further optimization to this is being tracked https://github.com/LLK/scratch-blocks/issues/1145
Tested manually against the scenarios from issue #413.
> Remove manual refresh for scratch-blocks workspace

- package.json
- src/reducers/intl.js
Uses new version of scratch-l10n that supports localization of gui and paint. Part of https://github.com/LLK/scratch-paint/issues/16. 
Goes along with https://github.com/LLK/scratch-l10n/pull/6
This will be ready as soon as there's a  published release of l10n version 2.x
> importing l10n that includes paint strings

- src/containers/blocks.jsx
- test/helpers/selenium-helper.js
- test/integration/test.js
Resolves https://github.com/LLK/scratch-gui/issues/799, which was caused by a scratch blocks change the [has been reverted](https://github.com/LLK/scratch-blocks/pull/1168). The revert commit is to take out the corresponding "performance improvement" that went along with the now-reverted scratch-blocks PR. 
In order to make sure these problems do not happen again, I've added tests for the following things which were broken:
- Clicking on blocks to run them from the toolbox, seeing reported values.
- (same but specifically for variables, something which was also fixed recently)
- Switching sprites updating the block menus. This would have been broken if we had reverted the scratch-blocks PR but not reverted this GUI commit. 
It's …
> Revert broken performance improvement and add tests

- src/containers/paint-editor-wrapper.jsx
Integrates https://github.com/LLK/scratch-paint/pull/78, so this should not be pulled in until that's been published.  Resolves https://github.com/LLK/scratch-paint/issues/50
With the smarter handling of the `svg`/`svgId` props, `shouldComponentUpdate` is no longer needed. Clean up `PropTypes` to match.
> Update the costume name from the paint editor

- src/lib/make-toolbox-xml.js
FIxes https://github.com/LLK/scratch-gui/issues/745
It was caused by a mistaken copy/paste when we moved from using the default toolbox in scratch-blocks to providing our own. The set/move/glide fields need fixed IDs so that they can be updating when a sprite moves around. So I just copied them over correctly from scratch-blocks.
> Fix sprite position updating the toolbox blocks

- src/containers/blocks.jsx
_note: this depends on https://github.com/LLK/scratch-blocks/pull/1178 and will probably fail on travis until that is deployed_
Uses the new batch xml loading utility to load xml when changing workspaces introduced in  https://github.com/LLK/scratch-blocks/pull/1178
The new batch loading guarantees that `refreshSelection` on the toolbox is called exactly once.  This requires a change to unhook the workspace vm listener during the update, instead of disabling the events from scratch-blocks, because the vm still needs to hear the toolbox events, for now.
> Stop refreshing the toolbox by using new batch update API

- src/lib/make-toolbox-xml.js
Fixes https://github.com/LLK/scratch-gui/issues/768, making all monitors appear in sync and correctly reflect the monitored blocks in the VM. 
Which incidentally means that the currently un-implemented "sprite specific" monitors do not work and show that they don't work, meaning when you switch sprites the checkbox stays checked. 
This is an improvement, because it accurately reflects the monitored block container in the VM.
It does this by assigning fixed IDs to all blocks in the toolbox that are monitored. We previously fixed the variable blocks so that they have deterministic IDs as well. 
Lacking other ideas, i just used the back half of the opcode as the fixed ID. Doesn't much matter since it is never referred to manually.
> Give fixed IDs to all monitored blocks

- src/components/stage/stage.css
Fixes https://github.com/LLK/scratch-gui/issues/805 by moving the corner radius up to the wrapper and setting `overflow: hidden` to prevent the canvas from appearing outside the corner radius. Also adds a border to make it match the other panels.
> Fix corner radius bug

- src/lib/make-toolbox-xml.js
Resolves https://github.com/LLK/scratch-gui/issues/813
Removes the "top" category of blocks containing commonly used blocks at the top of the category menu.
We tried it out with kids and found that it was used very infrequently.
> Remove “top” category

- src/containers/paint-editor-wrapper.jsx
Fixes https://github.com/LLK/scratch-paint/issues/121
Use the skin ID rather than the costume index.
When costumes are deleted from the sprite, the costume index shifts. Skin ID tracks what we want.
> Use unique costume ID

- src/components/gui/gui.css
This is part of tightening up the category menu (https://github.com/LLK/scratch-blocks/pull/1198).
Just make the "add extension" button a little smaller
This makes it match the new smaller width of the category menu.
No tests.
> Shrink extension button

- src/containers/blocks.jsx
- src/lib/make-toolbox-xml.js
1.Toolbox should be updated before ScratchBlocks inject to avoid repeated rendering.
2.Some monitored blocks's shadow blocks also need IDs.
> Update toolbox before ScratchBlocks inject and Give  IDs to some shadow blocks

- src/lib/make-toolbox-xml.js
Resolves https://github.com/LLK/scratch-gui/issues/836
Brings back the new `contains` block which looks like it was lost in the shuffle between blocks xml and gui xml. 
I also noticed that the default values were wrong when this was originally implemented (`hello contains world`, while the spec says `hello world contains world`). I updated it to match the spec. @thisandagain this block is pretty wide, which makes it somewhat harder to notice that it is a boolean. Is the below screenshot ok?
h/t to @Kenny2github for noticing the regression.
> Bring back the 'contains' operator block

- src/components/target-pane/target-pane.jsx
- src/containers/blocks.jsx
- src/containers/extension-library.jsx
- src/containers/target-pane.jsx
- test/integration/test.js
Resolves https://github.com/LLK/scratch-gui/issues/821
Depends on https://github.com/LLK/scratch-vm/pull/724
- Prevent loading duplicate extensions by checking with the VM extension manager before loading
- If the extension has already been loaded, scroll the blocks menu to that extension category
- Render the extension library in the blocks container, so that it can scroll the blocks.
This prevents the loading of duplicate extensions, at least for internal extensions.
[test coming]
> Prevent loading duplicate extensions

- test/integration/examples.test.js
Dev is intermittently failing because the distance to scroll changed slightly messing with what used to be a lucky bit of timing.
Update the examples.test.js to wait for scroll animations, which should make the tests pass consistently again. 
Note: we wait for this scroll animation in the other tests already.
> Wait for scroll animations correctly 

- src/lib/default-project/index.js
- src/lib/project-loader-hoc.jsx
Hotfix bug loading projects by ID introduced by https://github.com/LLK/scratch-gui/pull/837
Data comes through storage now, meaning it isn't parsed as JSON when it arrives, it is just an array buffer that needs to be stringified. 
Previously we were catching errors here and just logging them. Doing this breaks the error checking in the integration tests.
> Fix project json loading through storage

- src/containers/blocks.jsx
- src/containers/extension-library.jsx
Only scroll the blocks menu to the extension category when the extension was just loaded from the library (or when selecting an extension in the library that is already loaded).
Previously, when an extensions was automatically loaded on project load (via https://github.com/LLK/scratch-vm/pull/756), the gui would cause the blocks menu to scroll to the extension. We do not want the blocks menu to scroll in that situation.
> Scroll to extension category only when loading from library

- src/examples/compatibility-testing.jsx
- webpack.config.js
Add a simple example page `/compatibility-testing.html` that loads a project (from hash) in both scratch 3 player and an embedded iframe with the scratch 2 player. 
One note when using this locally is that I had to go into my chrome settings and whitelist `http://localhost:8601` to allow the flash player. It doesn't pop up an "allow" thing from the iframe for some reason. Will probably have to do the same thing with the deployed github url.
> Add compatibility testing example page

- src/components/language-selector/language-selector.jsx
The language selector has no aria-label, meaning that a user navigating Scratch with a screen reader is forced to guess what the selector is for. 
Add aria-label to the language selector.
The aria-label will be read when someone is navigating the page using a screen reader and is focused on the language selector form.
On Mac, I used a screen reader to check that the label was read aloud upon navigating to the selector.
> Add aria label to language selector.

- src/components/menu-bar/menu-bar.jsx
When a screen reader is focused on the Scratch logo, the user hears "/svg%3E" since the logo is unlabeled.
User of screen reader on Scratch GUI hears "Scratch logo image" voiced when navigation is on the Scratch logo image.
Provides meaningful text describing the image for those who can't see.
Tested manually using VoiceOver on Mac
> Add alternate text for Scratch logo.

- src/components/close-button/close-button.jsx
- src/components/icon-button/icon-button.jsx
- src/components/sprite-info/sprite-info.jsx
- test/unit/components/__snapshots__/icon-button.test.jsx.snap
- test/unit/components/__snapshots__/sound-editor.test.jsx.snap
- test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
When using a screenreader on the Scratch GUI, images are encountered but are not meaningful (they are referred to as "/svg%3E") nor necessary.
Have the screen reader skip over these images upon encountering them by using the aria-hidden attribute on these images.
These images are not actionable nor necessary for the user to understand and use the Scratch GUI
I tested VoiceOver on Mac, checking that it skips over these images.
> Hide icons from screenreader

- src/components/language-selector/language-selector.css
There is no visual indicator of focus on the language selector when tabbing through the GUI. 
Add white ring around the selector when it has focus (e.g. you have tabbed to the language selector).
Before:
After:
Upon discussion with Carl, the highlight is consistent with other ways in which the focus on elements is shown.
> Show focus on language selector.

- src/components/sprite-info/sprite-info.css
- src/components/sprite-info/sprite-info.jsx
- src/containers/sprite-info.jsx
- Cannot tab to individual show/hide sprite buttons (they both have same tab index)
- Cannot use keypresses (press space or enter) to activate show/hide sprite buttons
- Show and hide buttons do not visually show focus
- You can tab to each button individually 
- User can press space or enter to activate either of the buttons when the button has focus on it
- Buttons have a border when they currently have focus
Focused on active Show Sprite Button:
Focused on inactive Show Sprite Button:
Focused on active Hide Sprite Button:
Focused on inactive Hide Sprite Button:
Someone with limited motor skills may not be able to use the mouse to click on the show and hide sprite buttons. Keyboard controls may be more usable. Adding visual indicators to show that focus is on the buttons provides …
> Enable selection of sprite visibility by keyboard.

- src/components/asset-panel/selector.css
- src/css/units.css
- src/lib/layout-constants.js
This is for https://github.com/LLK/scratch-paint/pull/194, making the selector area smaller on tablet so as to create more space for the paint editor.
This change adds a media query, set to the paint editor's minimum full width (`1250px`), to make the selector column smaller when below the minimum full width. It also adds constants to the `units.css` file that match those from the `layout-constants.js` file in order to be used on css media queries.
In order to make the paint editor viewable and usable in tablet, we need to shrink the selector's size. This is because resizing the canvas itself is non-trivial, and we have already condensed space in the paint editor in all of the other ways we can.
/cc @carljbowman
> Make selector column responsive to paint editor width

- src/containers/sound-tab.jsx
- test/helpers/selenium-helper.js
- test/integration/test.js
Fixes https://github.com/LLK/scratch-gui/issues/858
Use the vm editing target directly to handle loading a sound into the sound editor. There is some kind of state synchrony problem between the editing targets as they exist in the VM vs. the redux store. This is a quick fix for that. I've filed another issue to deal with actually finding the root of that problem.
Add an integration test that I confirmed used to fail (deleting the only sound).
> Prevent deleting a sound from exploding

- src/containers/blocks.jsx
- src/lib/make-toolbox-xml.js
- src/reducers/toolbox.js
Working towards LLK/scratch-vm#564
Give per-sprite monitor blocks unique IDs for each target. This way monitor blocks for different targets will be able to exist concurrently.
> Refresh workspace with sprite-specific blocks when sprite changes

- src/index.jsx
- test/helpers/selenium-helper.js
- test/integration/examples.test.js
- test/integration/test.js
When you're working on your project, sometimes you accidentally swipe back or refresh when you don't mean to and you lose all your work!
When the GUI is built for production, the page asks you (in modern browsers) if you really want to unload the page.  This isn't active while developing, only when the GUI is built with `NODE_ENV=production`.
This way you'll be able to confirm before navigating away.
All the tests still work now. Should I update to add a test for this alert?
> Warn user before navigating away/unloading

- src/lib/storage.js
- webpack.config.js
Progress toward loading the drum and instrument sounds from scratch storage: https://github.com/LLK/scratch-audio/issues/48
- Copy extension assets from the VM
- Add a web source for the music extension assets
These changes allow us to load sound files used by the music extension from a static directory.
> Register music extension assets

- src/components/waveform/waveform.jsx
- test/unit/components/__snapshots__/sound-editor.test.jsx.snap
Sound editor looks weird in non-Chrome #657 
<https://github.com/LLK/scratch-gui/issues/657>
add argument to `join` so SVG path output of waveform will not contain comma
Firefox doesn't like comma (,) in SVG path. Someone has similar problem:
<https://support.mozilla.org/zh-TW/questions/878388>
Change test file in `test/unit/components/__snapshots__/sound-editor.test.jsx.snap` as waveform SVG path is malformed and makes Firefox angry
> Fix waveform in sound editor in Firefox

- src/components/monitor-list/monitor-list.jsx
- src/containers/monitor.jsx
- src/lib/monitor-adapter.js
Working towards https://github.com/LLK/scratch-vm/issues/564
Depends on https://github.com/LLK/scratch-vm/pull/784
> Append sprite name to monitor label for sprite-specific monitors.

- src/lib/storage.js
The drum sounds were not loading after we merged https://github.com/LLK/scratch-vm/pull/785
Use a relative path to the static assets directory.
The path used to load the sounds as static assets was working correctly locally, but not in the deployed version. This relative path accounts for the fact that the URL on github.io is different.
> Use relative path to load extension assets

- src/containers/blocks.jsx
- src/lib/blocks.js
- src/lib/make-toolbox-xml.js
- src/reducers/toolbox.js
- test/integration/test.js
Fixes https://github.com/LLK/scratch-blocks/issues/682
Adds a `isStage` flag to the temporary "make toolbox XML" functionality that the GUI has. Show different blocks depending on whether or not a target is a stage. This level of specificity I think is acceptable for now, since this functionality will move out to the more general filtering of the VM with extensions. 
Added an integration test to make sure the label "Stage selected: no motion blocks" is visible when you have the stage selected.
> Target specific palette

- src/containers/blocks.jsx
- test/integration/test.js
Fixes https://github.com/LLK/scratch-gui/issues/937
Missed this when reviewing the PR for custom target palettes. We forgot to include the dynamic extension toolbox XML from the VM when changing targets. 
I added a step to the integration test that loads extensions to switch sprites and confirm that the pen category is still loaded.
> Fix extensions disappearing when switching sprites

- src/containers/sound-editor.jsx
- test/unit/containers/sound-editor.test.jsx
Fixes https://github.com/LLK/scratch-gui/issues/927
Play the sound after undo/redo in the sound editor.
Makes it clear that a change has taken place. See discussion https://github.com/LLK/scratch-gui/issues/927.
Added a new test to the sound editor container, making sure that undo/redo updates the sound buffer and plays the sound.
> Play the restored sound after undo/redo in the sound editor

- src/lib/blocks.js
- test/integration/test.js
Fixes the problem where deleting the only sprite exploded the page. It was caused by the recent change to how the clone menu was populating. 
@ericrosenbaum I am guessing this was another big source of problems with using the GUI.
> Fix only sprite failure

- src/index.ejs
This is a small experiment to use Sentry to record uncaught errors from using scratch-gui. I don't expect that we will keep this in for a long time, but I've been trying it and it gives a lot of useful context.
> Try using sentry to make bug finding more effective

- src/lib/make-toolbox-xml.js
Fixes the warnings coming from loading the toolbox because the spec for broadcast blocks changed. 
Before there were console warnings, now there are none.
> Fix toolbox xml for broadcast messages

- src/lib/libraries/extensions/index.js
We're temporarily hiding this extension (until after the preview release- it will come back!).
The extension system is missing a few features (connection status indicator, non-droppable inputs, stop button events) and the WeDo extension itself has some unfixed bugs (error on running blocks when not connected, failure to reconnect on disconnect, crash on excessively rapid commands, can't set motor direction while running).
> Temporarily hide WeDo extension

- src/lib/make-toolbox-xml.js
Add the "More" category. It acts like the variable category in that the palette blocks are dynamic and populated in scratch-blocks. This is what it looks like when you have custom procedures already defined:
Or when you have no custom procedures
But that is all handled by scratch blocks.
---
Since the "Make a block..." button callback is not implemented yet (it alerts "not implemented") we can hold this PR until the other parts of custom procedures are done. Just wanted to get this submitted (low hanging fruit yay).
> Add "More" category for custom procedures

- src/containers/custom-procedures.jsx
Currently the custom procedure block is just centered in the view.
Instead, try to center the custom procedures block but make sure the right side doesn't fall off the edge.
> Try to keep new custom procedure inputs in view

- test/helpers/selenium-helper.js
Fixes https://github.com/LLK/scratch-gui/issues/984 (hopefully, needs to be tested to confirm, more on that below).
Set the integration test window size to 1024x768. In reality this leaves us with a window innerWidth/innerHeight of 1024x654 on my computer, but the tests still pass. 
Integration tests still pass for me and presumably will still pass on travis. The real test is to see if @ericrosenbaum, @quachtina96 this PR fixes you running integration tests locally.
> Force 1024x768 window size for automated tests

- src/lib/blocks.js
Fixes https://github.com/LLK/scratch-gui/issues/1009
Reorders the menus so that the random is above mouse pointer.
Want to make randomness easier to get to, more fun!
> Reorder menu options so random position is above mouse-pointer

- src/components/monitor-list/monitor-list.jsx
- src/components/monitor/monitor.jsx
- src/containers/monitor-list.jsx
- src/containers/monitor.jsx
- src/lib/monitor-adapter.js
- src/reducers/gui.js
- src/reducers/monitor-layout.js
- test/unit/reducers/monitor-layout-reducer.test.js
https://github.com/LLK/scratch-gui/issues/458 Monitors overlap each other on stage
https://github.com/LLK/scratch-gui/issues/472 Variable Monitor Cannot Be Moved
https://github.com/LLK/scratch-gui/issues/463 Monitor list extends outside of stage
Algorithm for layout out monitors
Requirements:
- Monitors line up on the left edge of the screen first
- Monitors try to appear in a place where they won't overlap already showing monitors
- If a monitor is moved, then turned off and on again, it stays in the place it was put
Beyond that, I didn't try to match very closely the behavior of 2.0, which can be pretty strange. 
I tried to document some of it in https://github.com/LLK/scratch-gui/issues/463. You're pretty unlikely to want your entire project covered in monitors anyway.
Here is how I …
> Monitor layout

- src/components/sprite-info/sprite-info.css
- src/components/sprite-info/sprite-info.jsx
Unable to tab over the Sprite Rotation dropdown in Sprite Info, and the tab order jumps directly down to Sprite Info when it's standard to tab through elements top to bottom, left to right.
Include the rotation dropdown in the tab order.
Show focus on the rotation dropdown.
Use tab index 0.
Improve keyboard control accessibility.
> Enable sprite rotation keyboard control and standardize tabbing.

- src/components/close-button/close-button.jsx
- src/components/library-item/library-item.jsx
- src/components/library/library.jsx
- src/index.jsx
- test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
When a user opens a modal, the screen reader is moved out of the web content. When navigating into the  GUI, it reads "In Scratch 3.0 GUI, web content web content is empty". Modal and GUI becomes completely unusable.
- Rather than hide the entire Scratch GUI from the screen reader when the modal is open, hide everything but the modal.  
- Include library items and close button in the tab order
- assign library items the button aria role
- Add an onBlur and onFocus listener to the library items so that one may preview the sound before selecting it, as is done with mouseEnter and mouseLeave.
Someone who is blind or low-vision can now use the screen reader to identify various assets and add them to their projects! It also enables them to navigate out of the modal and back to the rest of the …
> Make libraries screen reader accessible.

- src/components/gui/gui.css
#1015
Remove the ability to select the tab button text
The text selection can easily be trigged by accident and it doesn't look good
> Make it so that the user cannot select tabs

- src/containers/sound-tab.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1013
Check for the selected sound before rendering the sound editor. 
The fix from https://github.com/LLK/scratch-gui/issues/858 was not complete.
Crash no longer occurs
> Check for the selected sound before rendering the editor

- src/lib/libraries/costumes.json
- src/lib/libraries/sprites.json
- Adds "Empty" sprite and costume
- Temporarily resolves issue for workshops by introducing an "Empty" sprite and costume library option
> Add 'empty' sprite and costume

- package.json
copy-webpack-plugin 4.2.2 was published with no dist. Ensure we skip over this version.
Closes #941
> chore(package): update copy-webpack-plugin to version 4.3.0

- package.json
- src/containers/blocks.jsx
- src/reducers/intl.js
- test/integration/test.js
Initial version of extension localization.
- pen translations are imported by default, we may want to consider whether the translations should be imported dynamically when the extension is added.
- blocks.jsx container is calling setLocale on the VM when the locale changes. Would this actually be better in the intl reducer?
- handleBlocksInfoUpdate is currently a duplicate of adding an extension, but it gets lots of warnings about overwriting the definition of blocks from blockly.js. Do we want to change the handler to remove the blocks before redefining them, or just remove the warning in scratch-blocks? [Update, left a todo comment to deal with scratch-blocks warnings, and simply call handleExtensionAdded]
The setLocale in componentDidUpdate never actually gets called because blocks …
> Localize extension blocks

- src/lib/libraries/costumes.json
- src/lib/libraries/sounds.json
- src/lib/libraries/sprites.json
- Add musical instruments to libraries (https://scratch.mit.edu/projects/193585377/#editor)
- Add letters to libraries (https://scratch.mit.edu/projects/193577829/#editor)
The names of the "letter" sprites and costumes have been modified to ensure they are rendered at the bottom of each library. This is a gross hack, but does the trick for now until the `libgen` tool can understand ordering beyond simple alphabetical sorting.
I ended up sticking with the old (legacy) instruments as some of the new instruments would render in the paint editor but were inexplicably not rendering to the stage (even though they work in Scratch 2.0).
/cc @chrisgarrity @carljbowman
> Add musical instruments and letters to libraries

- src/components/target-pane/target-pane.jsx
- src/containers/backdrop-library.jsx
- src/containers/costume-library.jsx
- src/containers/costume-tab.jsx
- src/containers/record-modal.jsx
- src/containers/sound-library.jsx
- src/containers/sound-tab.jsx
- src/containers/target-pane.jsx
- test/integration/test.js
Fixes https://github.com/LLK/scratch-gui/issues/925
Moves the costume and sound libraries under their respective tabs so that they can communicate. 
This depends on a minor fix to the VM to provide a promise for costume loading. https://github.com/LLK/scratch-vm/pull/864
> Show newly added assets after they are loaded

- src/components/target-pane/target-pane.jsx
- src/containers/backdrop-library.jsx
- src/containers/target-pane.jsx
- test/integration/test.js
Fixes https://github.com/LLK/scratch-gui/issues/1044
And adds an integration test.
@fsih the backdrop library is actually accessible from two different places, the costume tab and the "stage" target pane. I added it back to there.
> Fix backdrop library 

- src/containers/stage.jsx
Fixes https://github.com/LLK/scratch-gui/issues/757
The `button` property does not exist for touch devices.
Tested on touch devices, and using the emulator for touch in chrome.
> Fix touch actions on the stage

- src/containers/blocks.jsx
- src/containers/custom-procedures.jsx
GH-1082
- Adds a new `PropType` definition and default option for `collapse: false` to both the `blocks` and `custom-procedures` containers.
- Removes the "collapse" option from context menus in the blocks workspace which is not a feature that would like to support for Scratch 3.0, but is not worth removing from `scratch-blocks`.
> Disable the 'collapse' option in the blocks workspace

- package.json
Not sure why greenkeeper hasn't picked up this release... Seems to be up-to-date on the other dependencies?
> Update to most recent paint editor release

- src/lib/make-toolbox-xml.js
Fixes https://github.com/LLK/scratch-gui/issues/1103
Closes https://github.com/LLK/scratch-gui/issues/1103
Sorry @thisandagain stole it!
> Update graphics effects blocks to use scratch2 default values.

- src/components/stage-selector/stage-selector.css
Fixes https://github.com/LLK/scratch-gui/issues/1065
> For now, we would like to drop the outline around the indicator to remove this confusion.
> Remove border to stop backdrop count from looking like an input.

- src/containers/sound-editor.jsx
Closes https://github.com/LLK/scratch-gui/issues/1093
Start dropping old undo snapshots in the sound editor after 99 snapshots.
> Add 99 max undo stack size for sound editor

- src/lib/make-toolbox-xml.js
Fixes https://github.com/LLK/scratch-gui/issues/1066
For stage
For sprite
> Update looks palette ordering, including "next backdrop" in sprite.

- src/containers/custom-procedures.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1024
Auto focus last input when opening custom procedure modal.
> Focus on the last input when opening custom block modal

- src/containers/blocks.jsx
[Issue #1048](https://github.com/LLK/scratch-gui/issues/1048)
Revised number rounding logic for default x and y values in motion blocks on the flyout so that when the sprite is at a position such as (x=-0.001, y=216), the blocks display this
instead of this.
The value "-0" looks ugly and might confuse beginners.
None.
> Modify rounding logic in flyout blocks

- src/containers/blocks.jsx
[LLK/scratch-blocks#1272](https://github.com/LLK/scratch-blocks/issues/1272)
Allows custom modal title for new variable/list/broadcast message.
[LLK/scratch-blocks#1272](https://github.com/LLK/scratch-blocks/issues/1272)
Associated with PR [LLK/scratch-blocks#1321](https://github.com/LLK/scratch-blocks/pull/1321)
> Custom Titles for Variable Modals

- src/lib/make-toolbox-xml.js
Pluggable inputs for broadcast blocks.
Accomodates pluggable input functionality for broadcast blocks.
Depends on these PRs and **should not get merged in until these are also ready to be merged**:
[LLK/scratch-blocks#1302](https://github.com/LLK/scratch-blocks/pull/1302)
[LLK/scratch-vm#860](https://github.com/LLK/scratch-vm/pull/860)
To make pluggable inputs work correctly. Compatibility with SB2.
These three PRs can be tested together [here](https://llk.github.io/scratch-gui/broadcast-input/).
> Broadcast Inputs

- src/components/asset-panel/selector.jsx
- src/components/sprite-selector-item/sprite-selector-item.jsx
- src/containers/costume-tab.jsx
- src/containers/sprite-selector-item.jsx
Fixes https://github.com/LLK/scratch-gui/issues/824
We prevent deleting the last costume in the VM. This PR enforces that in the GUI by removing the delete button when only 1 costume is left.
Elements in the GUI shouldn't seem to do nothing
> Prevent deleting the last costume

- src/lib/make-toolbox-xml.js
GUI part of https://github.com/LLK/scratch-vm/issues/553
Depends on https://github.com/LLK/scratch-blocks/pull/1325
Adds new drag mode block to the toolbox. 
@thisandagain I assume this block shouldn't be there for the stage, but let me know if that isn't right.
> Add drag mode block to make toolbox XML

- package.json
Fixes https://github.com/LLK/scratch-gui/issues/795
Update the dependency manually. It looks like it tried to update at a moment when develop wasn't building (before we pinned all the other repo deps). Trying again, if it passes will merge.
> Update to 2.8.0 manually because of greenkeeper test error.

- src/lib/libraries/backdrops.json
- src/lib/libraries/costumes.json
- src/lib/libraries/sounds.json
- src/lib/libraries/sprites.json
The first round of new sprites for Scratch 3.0. :tada:
| Theme      | Illustrator       | Preview                                      |
| ---------- | ----------------- | -------------------------------------------- |
| Basketball | Alex Eben Meyer   | https://llk.github.io/scratch-gui/#195719374 |
| Dinosaurs  | Alex Eben Meyer   | https://llk.github.io/scratch-gui/#195651707 |
| Food       | Alex Eben Meyer   | https://llk.github.io/scratch-gui/#195866936 |
| Soccer     | Alex Eben Meyer   | https://llk.github.io/scratch-gui/#195721329 |
| Music      | Andrew Rae        | https://llk.github.io/scratch-gui/#182680684 |
| Forest     | Daria Skrybchenko | https://llk.github.io/scratch-gui/#195902156 |
| Ocean      | Daria Skrybchenko | https://llk.github.io/scratch-gui/#195899904 |
| …
> Add new sprites 

- src/lib/blocks.js
[Issue #849 in the VM](https://github.com/LLK/scratch-vm/issues/849)
Adds "next backdrop" and "previous backdrop" menu options to the "switch backdrop to [  ]" block.
Consistency with Scratch 2.
None.
> Add next/previous backdrop options in backdrop block

- src/lib/libraries/costumes.json
- src/lib/libraries/sprites.json
Addresses https://github.com/LLK/scratch-paint/issues/246 but should not close the issue as it does not resolve the larger underlying problem.
- Remane "101" to "Robot"
- Modify the SVG asset for "101-a" to not include a numeric group ID
- Rename dinosaurs to be "DinosaurN" rather than individual genus / species names
> Minor revisions to new sprites and costumes

- package.json
Fixes https://github.com/LLK/scratch-gui/issues/1161
Update to the most recent scratch paint manually. Not sure why greenkeeper didn't pick this up?
> Update scratch paint version number manually

- src/containers/sprite-selector-item.jsx
Fixes #385.
Removes the sprite-specific message from the "delete" prompt that appears when you click on the X of any sprite, sound, costume, or backdrop card in a project.
If anything, this is a hack :) - But it's appropriate. This fixes #385, which is scheduled for the February milestone; it's a very old bug (May of last year) and has been put into and brought out of backlog over the course of its lifespan. The *correct* fix is to make non-sprite elements use an element other than `SpriteSelectorItem`, but this is a *hard* fix. It means creating a general component for "selector items", then making subclasses for each selector item, and changing the GUI to appropriately use these; no quick task.
This is a simple fix and gets rid of the bug quickly. It should also be noted that putting a …
> Remove sprite-specific text from sprite/sound/etc deletion warning

- src/lib/libraries/sounds.json
Fixes #1180.
Removes "Birthday" and "Birthday Song"; renames "Birthday Bells" to "Birthday".
To fix #1180. Rest in peace, [Birthday](https://cdn.assets.scratch.mit.edu/internalapi/asset/e8df0951694293fe17850260b4d12734.wav/get/)! 🍰
Automated tests aren't applicable; tested manually locally.
> Fix duplicate birthday sound clips

- src/components/stage-header/stage-header.css
- src/components/stage-header/stage-header.jsx
- src/components/stage/stage.jsx
- src/lib/screen-utils.js
LLK/scratch-gui#1179
Brings the menu controls in stage header component to be centered and of the same width as the stage in full-screen mode.
In non-full-screen mode, the menu controls for the stage are aligned with the width of the stage. Full screen mode should match this behavior. 
No test added.
> center/size stage-header controls in the same way as stage in fullscreen

- src/lib/libraries/costumes.json
- src/lib/libraries/sounds.json
- src/lib/libraries/sprites.json
Resolves GH-1182
Resolves GH-1187
Resolves GH-1188
Resolves GH-1189
Resolves GH-1184
- Removes any remaining gender pronouns from legacy sounds (GH-1184)
- Changes default food costume for "food" theme sprites (GH-1189)
- Changes grouping of `drum-snare-b` costume (GH-1188)
- Removes pillow from sleeping hedgehog sprite (GH-1187)
- Fixes ordering of costumes in `dinosaur4` sprite (GH-1182)
> Update libraries re: feedback from smoke test

- src/lib/make-toolbox-xml.js
Resolves GH-1191
Reorders motion category blocks as per #1191 
More logical clustering of functional areas and optimize for having more widely used blocks closer to the top of the category.
> Reorder motion category

- src/components/asset-panel/asset-panel.css
- src/components/sound-editor/sound-editor.css
- src/containers/sound-editor.jsx
- test/__mocks__/audio-buffer-player.js
Fixes the overflowing display of the waveform editor on firefox
Fixes https://github.com/LLK/scratch-gui/issues/990 sound editor not working on firefox.
broken
fixed
And the detached array buffer issue was fixed by retrieving a fresh copy of the samples.
> Fix firefox display and functionality issues with sound edit

- src/containers/error-boundary.jsx
temporary patch for #1205.
Unhandled errors will get a plain text message letting them know it has been logged.
> Temporary message when the GUI has an unhandled error

- package.json
- src/containers/error-boundary.jsx
- src/index.jsx
- src/lib/audio/shared-audio-context.js
- Add object-assign polyfill to handle missing features in IE.
- Prevent audio library from trying to create an Audio Context is the browser is IE, as that fails during load. (This prevents the `SCRIPT445: Object doesn't support this action` error) 
Catch any other errors during render, and render Browser unsupported modal instead.
Fixes #982 
/cc @ericrosenbaum @rschamp
> Support IE just enough to show unsupported modal

- package.json
- src/lib/blocks.js
- src/lib/opcode-labels.js
Fixes https://github.com/LLK/scratch-gui/issues/1211
Clean up the param strings that are shown as monitor labels
Remove sensing of, which is no longer monitored after https://github.com/LLK/scratch-blocks/pull/1337 goes in.
Convert 'dayofweek' to 'day of week'
> Clean up monitor dropdown strings

- package.json
- src/containers/error-boundary.jsx
Fixes Edge not rendering at all.
Pulls in the fix from scratch-render, and also fixes the webgl check to make sure it doesn't say "webgl not supported" whenever there is an error in Edge.
@chrisgarrity the change to the webgl check is because edge actually uses `experimental-webgl` context. 
/cc @fsih
> Get GUI working on Edge

- src/components/stage-header/stage-header.jsx
- src/containers/stage-header.jsx
LLK/scratch-gui#1171
The stage-header now listens for the 'escape' key press. If in full-screen mode, it exits this mode.
Requested by user  @kyleplo.
No additional testing added.
> Exit full-screen mode by hitting escape key

- package.json
- src/components/gui/gui.jsx
- src/containers/error-boundary.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1227
0. Update renderer in package json to get new checking methods.
1. Use new renderer methods to check for WebGL.
2. Remove the WebGL checks from the error boundary. Instead, just do not
render the stage if it is not supported.
The renderer can now tell us if it can be supported. Because we put up a fullscreen block if it isn't supported, do not bother trying to render the stage if the renderer is not supported (preventing errors which would lead to the error boundary. ). 
Tested locally using an extension to disable WebGL.
> Use new renderer methods to check for WebGL.

- src/components/costume-canvas/costume-canvas.jsx
- test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
Additionally render the canvas at a multiplier of the device pixel
ratio, so we get hidpi images for supported screens. The fixed CSS
sizing allows us to do that.
The problem was that on Edge, flexbox apparently can grow canvas
elements, whereas on Chrome/FF the canvas width/height is respected. No
problem, we can set the width/height in CSS to fix it, which
conveniently allows us to also fix the low-res-on-retina-screens problem
at the same time.
Before on Edge
After on Edge
@cwillisf this may interfere with some of the work you are doing with the SVG rendering stuff. If so, feel free to defer this until that is done. But it is just a couple line change, so it should be easy to reconcile with whatever you are working on. But let me know if it causes any issues.
> Use style sizing to fix issues with Edge + flex + canvas.

- package.json
- src/lib/audio/audio-recorder.js
Fixes sound recording in firefox.
Use a ponyfill for `getUserMedia` to use the promise based API for many different browsers. Tested on safari (mobile ios11/desktop), edge, chrome and firefox. 
Firefox doesn't support the old callback method anymore, so use the polyfill to get maximum coverage while using the new API.
> Fix Firefox sound recording

- package.json
- src/lib/make-toolbox-xml.js
Resolves https://github.com/LLK/scratch-blocks/issues/1199
Depends on https://github.com/LLK/scratch-blocks/pull/1339
Remove the menu shadows for some blocks to make the input non-droppable (i.e. so that you cannot drag and drop a reporter block onto the input).
See discussion in the issue above. Our focus is preventing confusion for beginners.
> Remove some blocks’ menu shadows to make them non-droppable

- package.json
- src/components/library/library.jsx
- src/containers/backdrop-library.jsx
- src/containers/blocks.jsx
- src/containers/controls.jsx
- src/containers/costume-library.jsx
- src/containers/extension-library.jsx
- src/containers/paint-editor-wrapper.jsx
- src/containers/sound-editor.jsx
- src/containers/sound-library.jsx
- src/containers/sprite-library.jsx
- src/index.jsx
- src/lib/analytics.js
- src/lib/project-loader-hoc.jsx
- src/reducers/modals.js
- test/unit/containers/sound-editor.test.jsx
- test/unit/util/project-loader-hoc.test.jsx
Resolves GH-1036
Add basic telemetry for the preview release that provides us with anonymous usage information. The full scope of `pageview`s and `event`s are listed in detail within GH-1036.
In order to understand usage patterns and the effectiveness of some of our new features / design changes, we will need some basic telemetry that provides us with insight into how the preview release is being used. This is much more minimal that what we have today for Scratch 2.0, but should be helpful nonetheless.
> Add Google Analytics

- package.json
I just released a new version of scratch-audio because Travis is being slow. Now I'm making this PR because Greenkeeper is also slow. Try and keep up guys.
> Update scratch-audio to the latest version 🚀 

- src/lib/libraries/backdrops.json
Fixes #1302 
This corrects a spelling error of the word "jurassic".
Correct spelling.
N/A - Just a quick spelling fix [dictionary.com for Jurassic](http://www.dictionary.com/browse/jurassic) :smile_cat:
> Fix spelling of backdrop

- src/components/sprite-info/sprite-info.css
#1288 
Changed the sprite stlye sheet to add the left hand border for the hide icon. 
So that the icon has a border all the way round.
Ran on Firefox 57.0.1 on Mac OS 10.13.1, checked that the border went around the whole icon.
> Whole border now highlighted blue

- src/components/preview-modal/preview-modal.jsx
#1260 
The "Try It" button had the "tryit" title assigned to it and the other button didn't, this was causing the tooltip to show up. This PR removes the title.
Requested in #1260 
After setting the repository up in an environment, I tested it and the tooltip seems to be gone now.
> Remove tooltip from Try It button. (Fixes #1260)

- src/containers/sound-editor.jsx
- test/integration/test.js
Fixes https://github.com/LLK/scratch-gui/issues/1320
Make sure that the "selected sound index" is within the range of available sounds.
When switching sprites, the selected sound index is supposed to reset to zero. This is done in the `componentWillReceiveProps`. However the setState there is async. The sound tab can be rendered before that setState, so you can get to a place where the selected sound index is outside the range of available sprites. 
Added a regression integration test to make sure it works.
> Constrain selected sound index to the list of available sounds.

- src/components/prompt/prompt.css
- src/components/prompt/prompt.jsx
- src/containers/blocks.jsx
- src/containers/prompt.jsx
#1262
Removes the  "More options" in New Message dialog
Becuase it looks better without it and the issue asked for this change.
FF 57.0.4 on 10.13.1. This is the result:
> Remove "More options" in New Message dialog

- src/components/monitor/monitor.jsx
Partial fix for #1298 
Proptype validator for monitor prop type now asserts that the monitor value can be a string or a number.
I couldn't seem to remove the second warning mentioned in #1298 about OrderedMap, but @fsih mentioned that that warning has been around for a while...
#1298
> Fixing monitor prop type warning for scalar variable monitors.

- src/components/library/library.css
#1277
Changed the library style sheet to center each row on the sprite library.
Center the grid on the sprite library.
Ran on Firefox 57.0.1 on Mac OS 10.13.1 and checked sprites were centered.
> Sprite library now centered

- src/containers/error-boundary.jsx
Resolves https://github.com/LLK/scratch-gui/issues/1246
Add telemetry for "hard crash" events through the "componentDidCatch" in the error boundary component which is only used for completely disabling errors. 
Tested manually by adding a `throw new Error('foo')` to a component render function. Got the hard crash and saw the output in the console (dev mode)
(sorry i kinda stole this one @thisandagain I was just itching to know how frequent these events are in the wild)
> Add telemetry for "hard crash" events

- src/containers/sound-editor.jsx
- src/lib/audio/audio-buffer-player.js
- src/lib/audio/audio-effects.js
Resolves #1376 
Resolves #1286 
Resolves #1281 
3 changes:
1. For the webkitOfflineAudioContext (used by Safari), force a sample rate that actually works (44k) instead of using the sample rate from the buffer. 
2. To support (1), store the sample rate in the undo stack to allow it to be changed on undo.
3. Wrap `buffer.stop` in a try/catch, because safari can throw an error if you stop more than once. Throwing in a lifecycle method causes a hard crash. That error being thrown is out of spec, the [developer guide](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode) specifically says you can call stop more than once.
Prevent hard …
> Fix several safari audio issues

- package.json
@fsih I'm not sure why greenkeeper didn't do this. Let's keep an eye on it going forward to see if we can figure out when it does/does not update.
> Update scratch-paint dependency because greenkeeper does not want to

- src/components/feedback-form/feedback-form.css
This is a long standing issue with how iOS deals with scrollable
elements within a fixed area. This was a helpful resource
https://davidwalsh.name/scroll-iframes-ios
Fixes https://github.com/LLK/scratch-gui/issues/1239
Adds a CSS property to allow for iOS scrolling of embedded iframe.
Tested in the iOS simulator.
> Fix feedback iframe scrolling for iOS.

- src/containers/blocks.jsx
Resolves #1361.
Depends on https://github.com/LLK/scratch-blocks/pull/1366
Uses the variable type provided by the scratch blocks to show/hide 'more options' in the different variable prompts. Also uses the ScratchBlocks constant for the default modal title instead of a hard-coded string literal.
#1361.
> Use variable type information in variable prompts to show/hide 'more options'

- src/components/library/library.css
Reverts LLK/scratch-gui#1297
@thisandagain unfortunately this PR broke several things with the libraries (left is develop, right is reverted)
1. The background of the library when you search for something used to be full height:
2. The extension library used to look... right
> Revert "Sprite library now centered"

- src/lib/libraries/sounds.json
#1355
Removes the duplicate computer beeps sound
You shouldn't have two of the same sounds
If you search for "computer beep", there are 3 results, but only 2 different sounds
> Remove duplicate computer beeps

- src/components/forms/input.css
@carljbowman it looks like there was an attempt to make the inputs have that popping border, but the syntax of it was all wrong... 
I updated it and now it shows the light blue border similar to the sprite tiles
> Fix the broken box shadow to make inputs pop more on focus

- src/containers/stage.jsx
Part of resolving https://github.com/LLK/scratch-gui/issues/1408
In scratch 2, it is 400ms, in scratch 3 it was 500ms. 
To make the behavior feel more similar to scratch 2.
n/a
/cc @morantsur
> Lower long and double click timing to 400ms to match scratch 2

- src/containers/preview-modal.jsx
- test/integration/project-loading.test.js
Resolves #1359
When the user clicks the `Not Now` button, it will direct them to `scratch.mit.edu` instead of sending them back.
If this should instead be an `href` instead of a button that redirects, I could give that try?
Requested in #1359 
I'm not sure how to write a test for this one, but if there's a way, I would love to learn and implement it.
> fix not now to redirect to scratch.mit.edu

- src/components/asset-button/asset-button.jsx
- src/components/green-flag/green-flag.jsx
- src/components/gui/gui.jsx
- src/components/icon-button/icon-button.jsx
- src/components/menu-bar/menu-bar.jsx
- src/components/record-modal/playback-step.jsx
- src/components/record-modal/recording-step.jsx
- src/components/sound-editor/sound-editor.jsx
- src/components/stage-header/stage-header.jsx
- src/components/stop-all/stop-all.jsx
- test/unit/components/__snapshots__/icon-button.test.jsx.snap
- test/unit/components/__snapshots__/sound-editor.test.jsx.snap
- test/unit/containers/__snapshots__/green-flag.test.jsx.snap
Images are draggable by default, but when used within buttons or as
clickable elements, they should not be draggable because starting a drag
accidentally prevents the click event.
Resolves https://github.com/LLK/scratch-gui/issues/1430
(GUI part only, will submit separate PR for scratch-paint).
use the `draggable={false}` attribute on images that are used as clickable elements
Images are draggable by default, but when used within buttons or as
clickable elements, they should not be draggable because starting a drag
accidentally prevents the click event.
Note a couple things about this …
> Fix numerous draggable images in the GUI

- src/containers/stage.jsx
Use the same drag threshold as from the blocks. It may need to be dialed
in further, but testing will be needed.
Resolvers https://github.com/LLK/scratch-gui/issues/1408, but may need further refinements to the drag threshold to dial it in.
Use a 3 px drag threshold before starting a drag on sprites. This gives a bit of breathing space for an unintentional movement while the mouse/touchpoint is down.
This will require a fair bit of manual testing on different devices / pointers. I'll mark it "needs-qa" so we can make sure to dial it in.
> Apply a drag threshold to make clicking sprites easier

- src/containers/stage.jsx
Fixes LLK/scratch-vm#865. Must be merged after LLK/scratch-vm#920.
This adds the GUI code which posts wheel scroll data to the VM's `mouseWheel` IO (which, in turn, activates relevant "when key pressed" blocks).
For consistency with 2.0 and 1.4.
No automated tests (besides what's in the VM PR); manually tested on the projects mentioned in LLK/scratch-vm#920.
> Detect wheel event on canvas and post data to VM

- src/containers/blocks.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1212
- Call scrollToCategoryByName('My Blocks') after custom block is created
- Cannot assume custom blocks section will be last category
- May pose issue during localization efforts
Fix issue posted
Manually tested on local build and test server using 'npm start'
Two test cases:
1 - Create new block after clicking on 'My Block' category
2 - Create new block after clicking on higher category ('Operators') and then scrolling down and clicking 'Make a Block'
3 - Add extensions 'Music' and 'Pen'  to Toolbox categories then repeat  cases 1 and 2
> Fix issue 1212

- src/components/gui/gui.jsx
- src/containers/gui.jsx
Resolves https://github.com/LLK/scratch-gui/issues/1151
Remove the enableExtensions prop.
This prop was used to hide the "add extension" button during a prototyping phase. We do not plan to use it, and it was confusing because it no longer worked.
> Remove enableExtensions prop

- src/containers/sound-tab.jsx
- src/containers/sprite-selector-item.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1486
Prevent the sprite selector item context menu click from bubbling to the selector item click. 
it was deleting a costume, then the event bubbled which tried to select the costume, throwing an error.
> Fix deleting in sprite selector item event bubbling

- src/components/action-menu/action-menu.jsx
- src/components/asset-panel/selector.css
- src/containers/stage-selector.jsx
- src/containers/target-pane.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1501
Fixes https://github.com/LLK/scratch-gui/issues/1505
Fixes https://github.com/LLK/scratch-gui/issues/1504
Fixes https://github.com/LLK/scratch-gui/issues/1499
and fixes a few proptype warnings that get logged in development
- Adds a shouldComponentUpdate that prevents re-rendering constantly. The reason for the re-rendering is a not-so-great use of react props that aren't simple values (using arrays/objects). Refactoring will be needed for a more thorough fix. fixing is a really good introduction/exercise on how react/redux works.
- Adds a pointer-events: none to prevent the fade-out pseudo element in the costume tab from blocking clicks. …
> Asset menu follow ups

- src/containers/target-pane.jsx
- src/lib/vm-listener-hoc.jsx
Fixes a current problem where the project importing does not work.
Remove shouldComponentUpdate from vmListenerHOC, move block drag endto target pane, which already has all the needed props.
Coincidentally, we merged two things at once that broke each other. The shouldComponentUpdate in the vm listener HOC broke the project loading from actually updating. 
@fsih I moved the block end drag listener to the actual container where the action is happening (the target pane) which already has the needed state.
> Fix the GUI not updating when new project data is available

- src/components/gui/gui.jsx
Fixes https://github.com/LLK/scratch-render/issues/243
Cache Renderer.isSupported because it takes 30ms every time and breaks if called too often
---
This was separated from the performance PR so that it could be merged as a quick fix because share-the-love causes webgl contexts to be created en-masse
> Cache Renderer.isSupported because it takes 30ms every time and breaks if called too often

- src/components/gui/gui.jsx
- src/containers/costume-tab.jsx
- src/containers/load-button.jsx
- src/containers/paint-editor-wrapper.jsx
- src/containers/save-button.jsx
- src/containers/sound-editor.jsx
This PR is a few small tweaks to the way that certain components consume state that actually add up to a pretty large benefit. The largest thing is to make sure that the props only contain the things you actually need (costume editor change) and to not use `.bind()` when creating props, because it will always cause a re-render. Here are some example flame graphs:
Here is an example while dragging a sprite with the sound editor open
And after fixing the binds
I used the react devtools extension, particularly the "highlight on update" checkbox, to show which components were re-rendering (this is like a version of the chrome "paint flashing" tool, but showing react renders not just (after-reconciliation) dom updates).
There is one "bonus" thing here which is to cache the result of the …
> Performance audit of react/redux state

- src/containers/costume-tab.jsx
- src/containers/sound-tab.jsx
Resolves https://github.com/LLK/scratch-gui/issues/1502
When switching targets, update the selected costume in the costume tab
Selected costume did not match costume on stage before
> Switch to the correct costume number when switching sprites

- src/components/stage-selector/stage-selector.jsx
- src/components/target-pane/target-pane.jsx
- src/containers/backdrop-library.jsx
- src/containers/costume-tab.jsx
- src/containers/stage-selector.jsx
- src/containers/target-pane.jsx
- src/index.ejs
Move the backdrop library back in to costume-tab. This fixes https://github.com/LLK/scratch-gui/issues/1475 for all but adding a surprise or paint backdrop from the info pane (Fixes adding a backdrop from library from the costume tab, adding a surprise/paint backdrop from the costume tab, and adding a backdrop from library from the info pane)
Fixing surprise backdrop from the info pane is more complex so I plan to make another PR.
> Move backdrop library back to costumes tab

- src/containers/stage.jsx
Resolves LLK/scratch-vm#940
Reports mouse-up data to VM even in the case of ending a drag. Also sends VM flag indicating whether this mouse-up was the end of a drag (which the VM should then use so that the `when this sprite clicked` block doesn't get activated on a drag: LLK/scratch-vm#957).
Compatibility bugfix.
> Always report mouse-up to VM and send flag indicating end of drag

- src/containers/error-boundary.jsx
Resolves #1609 
Fix reload button on the "Oops" error page so that it goes to the correct url (including the pathname).
> Fix reload button on error page 

- src/lib/make-toolbox-xml.js
Fixes LLK/scratch-blocks#1370. Must be merged after LLK/scratch-blocks#1371.
(I haven't done many pull requests which span across multiple repositories before. I'm not sure if I'll need to update `scratch-blocks` in the package.json in this PR?)
Reverts part of #1223 to make the "key pressed" sensing block input droppable.
To implement a help wanted feature request; to make the "key pressed" block more powerful. (See discussion in LLK/scratch-blocks#1370.)
Manually tested locally. VM functionality tested as well ("set my variable to space, say (key (my variable) pressed?)").
> Make sensing "key pressed" block input droppable

- src/containers/blocks.jsx
Resolves https://github.com/LLK/scratch-blocks/issues/1406
Depends on a blocks PR: https://github.com/LLK/scratch-blocks/pull/1407
When switching sprites, record the name of currently selected blocks category, and the distance by which the flyout is offset from the top of that category. After updating the toolbox, set the scroll position of the flyout to that offset relative relative to the top of the category.
The goal is to keep the scroll position of the blocks menu (aka the flyout) stable when you switch sprites. Generally, it should only move when you drag it or change categories. Up to now, after switching sprites, it would scroll to the top of the current category. This change prevents any scrolling on switching sprites in most cases*.
Note that the the offset can be negative, and …
> Hold scroll position on switching sprites

- src/lib/vm-listener-hoc.jsx
vm-listener-hoc's prevent default on keyboard events prevents the text tool in the paint editor from working.
> Don't prevent default on keyboard events

- src/components/asset-panel/selector.jsx
Fix some proptype warnings not cleaned up by https://github.com/LLK/scratch-gui/pull/1596/files
> Fix proptype warnings for asset panel buttons

- src/components/browser-modal/browser-modal.jsx
- src/containers/error-boundary.jsx
- src/containers/preview-modal.jsx
Added:
- Opera (including Opera Mini)
- Silk
Not Added:
- Vivialdi - appears to be ‘Chrome’ in `platform.name`
Resolves #1460 
I downloaded Opera (and Vivaldi) and checked that Opera gets the unsupported browser modal.
Testing:
> Add more browsers to the unsupported list

- src/lib/make-toolbox-xml.js
Final piece to resolve https://github.com/LLK/scratch-blocks/issues/634
Depends on https://github.com/LLK/scratch-blocks/pull/1412 and https://github.com/LLK/scratch-vm/pull/992
> Conditionally use "when stage clicked" vs "when this sprite clicked"

- src/components/loader/loader.css
- src/components/loader/loader.jsx
Resolvers https://github.com/LLK/scratch-gui/issues/1552
Rotate the loading messages every 5 seconds to make sure people know it is still going!
From @thisandagain 
> While loading projects, displaying a single message (e.g. "Loading sprites ...", "Loading costumes ...", etc.) can lead to the perception that the editor has "hung" and gotten stuck. My instinct is that this is reinforced by the behavior of the current Scratch 2.0 loading screen which shows a progress bar.
> My recommendation would be for us to rotate through messages every few seconds to better reinforce that the 3.0 editor is "doing something".
> Make the loader message update every 5 seconds

- src/components/filter/filter.jsx
Resolves https://github.com/LLK/scratch-gui/issues/1644 by not autofocusing the filter input when opening modals.
> Do not autofocus filter in libraries.

- src/components/asset-panel/selector.jsx
- src/components/sprite-selector-item/sprite-selector-item.css
- src/components/sprite-selector-item/sprite-selector-item.jsx
- test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
- test/unit/components/sprite-selector-item.test.jsx
Doesn't seem to be an issue filed here for it, but it is part of the April milestone. @carljbowman I put this up with just the styling from scratch 2, we can pair on restyling if you want.
Show the costume/sound number in their respective tabs.
Helps for using the costume number reporters, and a feature of Scratch 2.
Added a jest unit test for making sure the number is rendered out when
provided and not when not provided.
> Show the costume/sound number similar to Scratch 2.

- src/containers/record-modal.jsx
Resolves #1707 
Towards more easily allowing adding metadata to sounds in the sound editor tab.
Changes include:
- Add sample rate and sample count to sound object being added to the vm when a sound is recorded. This data is already provided for library sounds and for sounds imported from sb2 projects, so this change standardizes the availability of these properties across all sounds.
- Update the name property of the sound object to just be 'recording 1'. The VM already assigns fresh names to sounds, costumes, and sprites to remove duplication, so it will handle renaming the sound so that it doesn't overlap with other sound names for the given sprite. This change resolves #1707.
Note: these changes need to go in before the save-load work, so that the sb3 validation can correctly check …
> Store sample rate/count for recorded sounds

- src/containers/blocks.jsx
This resolves issues encountered while converting control blocks into an extension.
If an extension is loaded at project-load time, there won't be any targets. In that case, `handleExtensionAdded` now skips target-specific steps.
This change also adds a filter for JSON block info to support upcoming block separators, which have XML but no JSON.
> Fix handleExtensionAdded when no targets present

- src/lib/project-loader-hoc.jsx
No longer need to convert the data from the loaded project to a string. This was also causing an error in the issue mentioned below.
Resolves part of #1722 (namely the second project mentioned in that issue). Also for ergonomics; the toString call is no longer necessary now that vm/parser can load .sb2 files.
> Remove toString call in the project-loader.

- src/containers/load-button.jsx
Resolves #1747 
Fixes to issues in #1747 that were caused due to the way we were handling changes to the input element.
Issues that came up during smoke testing.
Since the load button doesn't exist anymore, these changes should be manually tested. In order to test these changes, pull in these changes as well as the changes from this PR #1728.
Since the save/load code being referenced on develop is not the same as that in the save-load branch, you should create your own .sb3 file (via creating your own project from scratch in 3.0 or via importing a 2.0 project) this is because .sb3 files saved from the save-load branch won't load on develop.
> Fixes for load button issues.

- src/components/sprite-selector-item/sprite-selector-item.css
Close buttons should not be over the new sprite menu #1753
Changed CSS `z-index` of the delete button in question. 
Fix issue #1753
> Fixing issue #1753

- src/containers/error-boundary.jsx
Add more stack info to the error messages emitted by the error boundary.  Retains the error message (it's the first line of `error.stack`).
While working on the menubar, I couldn't find the source of an error. I imagine this will help others in the future.
> Add more information to error boundary messages

- src/components/stage/stage.css
- src/components/stage/stage.jsx
- src/containers/stage.jsx
Also integrate the "ignore draggability, always drag" behavior of editor
mode.
Right now, editor drag mode is hooked up to the "isFullscreen" flag,
since it is the closest thing we have to player mode now.
Resolves https://github.com/LLK/scratch-render/issues/128, implemented in the GUI because (a) we needed the sprite drag out of the stage for the backpack and (b) the shadow is trivial in the GUI (`filter: drop-shadow`) but would be complex in the renderer.
Resolves https://github.com/LLK/scratch-gui/issues/1653
Doesn't create a "player" mode, but introduces a flag that can be used when making player mode, so related to https://github.com/LLK/scratch-gui/issues/1687
Adds a flag to the …
> Add editor drag mode for popping sprites of stage.

- src/containers/costume-tab.jsx
#1795
Loading a project while in the costume tab was yielding a fatal error resulting in the 'Oops' page because we were trying to lookup the length of target.costumes at a time when target.costumes doesn't exist anymore (because loading a new project requires clearing the runtime).
Change the line causing the error to first check if target and target.costumes are not falsey.
#1795
Existing tests pass. Also manually tested for the same issue with the sound tab.
> Fix issue where loading a project while in costume tab yields oops page.

- src/components/action-menu/action-menu.css
- src/components/action-menu/action-menu.jsx
- src/containers/sound-tab.jsx
#1776
Adds the ability to upload a sound from a file on disk. Supports both .wav (regular and ADPCM) and .mp3.
**Changes yet to come:** Support for selecting and uploading multiple files at once (this shouldn't be a difficult change, but I wanted to get feedback on these proposed changes first).
These changes depend on the following, and should not be merged until these others have been merged in:
LLK/scratch-vm#1060
LLK/scratch-audio#76
#1776
> Upload a sound file

- src/lib/make-toolbox-xml.js
https://github.com/LLK/scratch-blocks/pull/1442#issuecomment-381216217
In order to use the "reuse toolbox blocks" scratch-blocks patch, we need to make sure blocks that have shadows that will change based on sprite id are updated.
> Use unique ids for the toolbox elements that change per sprite

- test/integration/project-loading.test.js
Quit and restart driver to hit # URL because hashchange behavior changed
and pages no longer reload if you hit the same hash URL twice
If it passes on travis, it works!
> Fix integration tests failing due to Chrome update?

- test/helpers/selenium-helper.js
* Add an environment variable `USE_HEADLESS` to the selenium helper which if set to `no` disables headless (any other value including blank is "yes")
* Easy access to turn off headless mode
> Add USE_HEADLESS=no npm run test:integration option

- src/components/filter/filter.css
- src/components/library/library.css
- src/components/modal/modal.css
These are some late fixes to layout, some of which that came up while fixing the tag clipping on 1024px wide devices.
* Align back icon with the left edge of content
* Add padding to the search bar
* Give the divider height so you can see it
* Add a cool border around the filter bar while focused, but this uses focus-within which has limited support so not all browsers will display this (let's say it's progressive enhancement)
> Library tweaks

- src/containers/blocks.jsx
#901
* Force the `toolboxRefreshEnabled` flag on the workspace to always be false (regardless of what `Blockly.Xml.domToWorkspace` says)
* Defer the toolbox update a frame to allow the click handler to return earlier
* Removes approximately 400ms from the click event handler.
* Defers 200ms of it to the "next frame" so it still feels a bit jumpy, but since nothing really changes much you don't notice it.
> Limit toolbox updates to when we tell it to update

- src/lib/libraries/extensions/index.js
- Make the word "Mindstorms" uppercase ("MINDSTORMS") as per feedback from LEGO
- Correct branding in extension library
> Make MINDSTORMS uppercase as per feedback from LEGO

- src/components/library/library.css
- src/components/library/library.jsx
This prevents the fullscreen modal from being scrollable by removing extra height from the 
Try scrolling on the header of the sprite library. You shouldn't be able to scroll this.
Demo: https://rschamp.github.io/scratch-gui/bugfix/library-header-height/
> Account for filter bar in library grid height

- package.json
Reverts LLK/scratch-gui#1861, which broke adding new costumes and backdrops from the paint editor.
/cc @ericrosenbaum FYI
> Revert "Update scratch-vm"

- src/components/library/library.jsx
- src/containers/backdrop-library.jsx
- src/containers/costume-library.jsx
- src/containers/extension-library.jsx
- src/containers/modal.jsx
- src/containers/sound-library.jsx
- src/containers/sprite-library.jsx
Demo: https://rschamp.github.io/scratch-gui/feature/modal-back-button/
Push to history when the library mounts. Whenever popstate occurs after mounting, request to be closed.
Behavior captured in the `Modal` container. If we want to re-use this functionality for anything else that uses `ModalComponent`, just use the `Modal` container rather than `ModalComponent`.
Follow-up from Friday's smoke test
Enable the back button when opening modals. You can click back once, and clicking forward again doesn't re-open the modal. This is the most logical way of allowing to back out of modals but not keeping the rest of your navigation history logged while using the GUI (we could think about doing this …
> Allow the back button to work with libraries

- .npmignore
- .travis.yml
- webpack.config.js
Dependency of https://github.com/LLK/scratch-www/issues/1773
1. Update webpack so that `./dist` is an addition to the default build when `NODE_ENV=production`
2. Adds .npmignore so that `./dist` and `./build` get published.
3. Set NODE_ENV to production in travis
Build directory is needed for the normal integration tests to run, and the dist directory is needed to for importing to www.
Normal integration tests run
> Update travis to publish dist and build

- package.json
Looks like bitmap paint editor is still having issues that are causing crashes, so excluding it from todays deploy.
> Revert to pre-bitmap paint editor for deploying

- src/lib/file-uploader.js
Firefox and Safari both process mp3s as having audio/mpeg, and a variety of different audio/wav* possibilities.
Fix originally by @kchadha!
> Allow more mime types to be processed.

- src/containers/project-saver.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1897
Use the method available to Edge for downloading files, namely `msSaveOrOpenBlob`
Because Edge has to be special like that :( 
Tested by downloading files on Edge
Can test with this demo http://paulkaplan.me/scratch-gui/fix-edge-downloading/
> Use special method for downloading blobs in Edge

- src/components/sound-editor/sound-editor.css
Fixes an issue @carljbowman noticed where you can select the text on sound editor buttons
Like elsewhere in the UI, if you can click it, you shouldn't be able to select the text on it.
It is easy to get confused/lost when click/dragging on buttons (happens a lot) and all the sudden the UI turns blue.
> Make sound editor buttons unselectable

- src/lib/vm-listener-hoc.jsx
- src/reducers/targets.js
Fixes https://github.com/LLK/scratch-gui/issues/1632
Make sure not to render the costume tab if the data indicates a sprite is selected that is not in the targets list. 
I decided to make this defensive change instead of changing the reducer API because I want that to involve a more holistic refactor after discussing with @rschamp 
@fsih can you try this branch out, you should be able to find it (after travis builds) here:
paulkaplan.me/scratch-gui/fix-costume-crash or by pulling this locally.
> Protect against showing costume tab for target that does not exist.

- src/components/gui/gui.jsx
- src/containers/gui.jsx
Fixes https://github.com/LLK/scratch-gui/issues/267
Show "Backdrops" for the costumes tab if the editing target is the stage.
Scratch 2
> Show "Backdrops" instead of "Costumes" in tab text if stage is selected.

- src/components/green-flag/green-flag.css
- src/components/gui/gui.css
- src/components/gui/gui.jsx
- src/components/sprite-info/sprite-info.css
- src/components/stage-header/stage-header.css
- src/components/stage-header/stage-header.jsx
- src/components/stage-wrapper/stage-wrapper.css
- src/components/stage-wrapper/stage-wrapper.jsx
- src/components/stop-all/stop-all.css
- src/containers/gui.jsx
- src/containers/stage-header.jsx
- src/containers/stage-wrapper.jsx
- src/containers/stage.jsx
- src/lib/app-state-hoc.jsx
- src/lib/storage.js
- src/playground/player.css
- src/playground/player.jsx
- src/reducers/gui.js
- src/reducers/mode.js
- src/reducers/stage-size.js
Adds player-only mode to GUI.
Fixes #1687
Add isPlayerOnly property on GUI. Move isFullScreen into mode reducer with isPlayerOnly.
Full screen needs to be a separate prop so that GUI knows what to show when exiting full-screen (either player-only or full editor).
Set `box-sizing: border-box` for all of gui-body. Required the update to width and height on some elements that were still content-box sized.
Player mode for www
Current tests run, player playground example uses `player` mode, so player integration test checks player.
To check manually:
> Player mode

- src/containers/stage.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1931
Fix early return to be before draggability checking. Looks like just a typo in the original code.
Tested by making the editor fullscreen and trying to drag the stage, seeing no errors.
n/a not browser specific.
> Fix errors when dragging in player mode

- src/components/crash-message/crash-message.jsx
Back out a change which is not allowing the "crash" message to be seen.
/cc @chrisgarrity It doesn't work without an intl provider, which is mounted inside the error boundary.
> Revert localization of crash message.

- src/.eslintrc.js
- src/components/browser-modal/browser-modal.jsx
- src/components/crash-message/crash-message.jsx
- src/components/menu-bar/menu-bar.jsx
- src/components/prompt/prompt.jsx
- src/components/question/question.jsx
- src/components/record-modal/playback-step.jsx
- src/components/stage-selector/stage-selector.jsx
- test/helpers/selenium-helper.js
This moves all the remaining text in JSX to translatable `FormatMessage` components and adds the `react/jsx-no-literals` rule to the gui's eslintrc to prevent new untranslated strings from being introduced.
One thing to note about the `jsx-no-literals` rule is that you can still do `{'hello'}`. There is a mode to enforce not doing this, but I found turning it on that it gave a lot of "false positives" with respect to what we want, because there are a fair number of non-translation-related strings in the code. But this mode caught most of what I think we care about.
/cc @rschamp @chrisgarrity
> Make remaining text translatable, and prevent future regressions

- src/components/sprite-info/sprite-info.jsx
Fixes #1955
Use the `intl.formatMessage` with `defineMessages` for the placeholder.
Sprite info placeholder was showing [object Object]
Not browser specific.
> Fix stage naming by using intl.formatMessage instead of component.

- webpack.config.js
Last pr fixed it for production, this PR makes sure you don't have sentry in local development, which should make debugging a lot easier.
> Make sure no sentry config for local development

- src/containers/blocks.jsx
- src/containers/costume-tab.jsx
- src/containers/error-boundary.jsx
- src/containers/preview-modal.jsx
- src/containers/sound-tab.jsx
- src/lib/app-state-hoc.jsx
- src/lib/error-boundary-hoc.jsx
- src/lib/supported-browser.js
Fixes an issue where it is difficult for us to find out where crashing errors are coming from by looking at GA.
2 major things:
1. Separate errors coming from unsupported browsers from those coming from supported browsers. This is because basically every visit from IE counts as a "Fatal Error" like the actual bugs. Track those as a separate type of error.
2. Add ErrorBoundary's around the sounds, costumes and blocks tabs to report where the errors are coming from. This has the added benefit of allowing certain kinds of errors to be "recovered" from, because it only shows the "oops" page within the tab, instead of over the whole page. So it should still be possible to download your project …
> Make error catching and reporting better

- test/integration/costumes.test.js
Lack of integration smoke tests for the paint editor
Add a simple test to make sure converting to/from vector is properly interacting with the rest of the app, including making the paint editor load in the correct mode.
Nervous about merging paint editor PRs without something like this.
Add a test!
n/a bc it is a test.
> Add an integration test for bitmap vector conversion

- src/lib/blocks.js
Resolves #919 
Actual implementation for menu in when backdrop switches to hat. Should always reflect the current list of backdrops in the project.
#919
Manually tested in browser. List is dynamic, and selected values update if the selected backdrop is renamed in the costume tab.
Only tested on Mac as this should not be different from other dynamic menus we have.
Mac
Windows
Chromebook
iPad
Android Tablet
> Implement when backdrop switches to menu.

- src/containers/blocks.jsx
This is already landed on the performance branch -- #1784 
-----
#901
* Force the `toolboxRefreshEnabled` flag on the workspace to always be false (regardless of what `Blockly.Xml.domToWorkspace` says)
* Defer the toolbox update a frame to allow the click handler to return earlier
* scratch-blocks internally will set `toolboxRefreshEnabled` on the workspace after it finishes updating.  This causes an immediate re-render of the current toolbox, which we then give new XML for immediately following, basically re-rendering the entire toolbox again. 
* Removes approximately 400ms from the click event handler.
* Defers 200ms of it to the "next frame" so it still feels a bit jumpy, but since nothing really changes much you don't notice it.
> Limit toolbox updates

- package.json
Brings in https://github.com/LLK/scratch-blocks/pull/1464
> Bump scratch-blocks version

- package.json
- src/components/sprite-selector/sprite-selector.jsx
- src/components/target-pane/target-pane.jsx
- src/containers/sprite-library.jsx
- src/containers/target-pane.jsx
- src/lib/file-uploader.js
Resolves #222.
Enable uploading a sprite from a file. The file can be an image or a .sprite2 file (.sprite3 coming soon). If uploading an image as a sprite, adds new sprite and sets the image as the sprite's costume.
This PR does not cover saving a sprite to a local file.
https://llk.github.io/scratch-gui/sprite-upload/
#222
Existing tests pass. Integration tests needed for file upload features. Tracking in #1868.
Mac
Windows
Chromebook
iPad
Android Tablet
LLK/scratch-vm#1110. <-- should be merged before this one and get package updated in this PR
> Sprite upload

- src/components/context-menu/context-menu.css
- src/components/monitor-list/monitor-list.jsx
- src/components/monitor/default-monitor.jsx
- src/components/monitor/large-monitor.jsx
- src/components/monitor/monitor.css
- src/components/monitor/monitor.jsx
- src/containers/monitor.jsx
One of the parts of finishing monitors.
Implement the large monitor mode, including:
1. Temporary state storage for monitor type, will eventually be moved to VM
2. Context menu for changing between normal/large readout. Copied language from S2.
3. Double click action for cycling through the monitor types available.
I tried to make the large monitors match S2 style and size wise as much as possible.
No automated tests for monitors yet... :(
Tested: dragging monitors, context menu layers above other monitors, double click changes monitor mode.
Mac
Windows
Chromebook
iPad
Android Tablet
> Large readout mode for monitors

- src/lib/blocks.js
Resolves LLK/scratch-blocks#1500
Depends on LLK/scratch-vm#1122
Adds the "random backdrop" option to the `backdropsMenu` menu.
To resolve a help wanted issue.
Irrelevant - adding an item to a list is browser-independent.
> Add random backdrop menu option

- src/components/modal/modal.css
- src/containers/gui.jsx
- src/playground/index.jsx
#1853 
Add setAppElement to exported GUI. Consumers of GUI (e.g. playground, www) must call `GUI.setAppElement()` 
Modals are added at the root, so the modal needs to explicitly set `box-sizing` to work outside of playground.
Eliminate warnings
Usual tests run
Mac
Windows
Chromebook
iPad
Android Tablet
> Add setAppElement to GUI

- src/components/monitor-list/monitor-list.jsx
- src/components/monitor/monitor.css
- src/components/monitor/monitor.jsx
- src/containers/monitor.jsx
Another step towards importing monitors from scratch 2 projects from the VM.
Pass in monitor x/y data as well as mode data from the VM. This change will not do anything without the PR that imports monitors from SB2 files in the VM, but it does not break without it. With the VM update, monitors will be imported with the correct mode and positioning.
Also made a minor CSS update to make large monitors a bit closer in size to SB2, which I found was important when we got SB2 importing working.
Remaining work for monitors in the GUI includes:
- Sending mode updates to the VM, not storing them in state
- Adding slider and monitor modes to the GUI
- Hooking up the new slider/monitor modes to VM …
> Consume monitor mode and position from VM

- package.json
- src/components/monitor-list/monitor-list.jsx
- src/components/monitor/list-monitor.jsx
- src/components/monitor/monitor.css
- src/components/monitor/monitor.jsx
- src/components/monitor/slider-monitor.jsx
- src/containers/monitor.jsx
- src/lib/monitor-adapter.js
Adds first iteration UI for list and slider monitors. They are "read-only" in this PR, i.e. they cannot be edited, the sliders do not work. I wanted to do that in a separate PR, because it may require VM APIs that do not exist yet.
You can now:
- Create list monitors from scratch 3 toolbox
- Import list monitors with the XY/width/height set from scratch 2
- Use double-click or context menu to change variable monitors to slider mode.
Manually tested along with monitor imports:
Depends on https://github.com/LLK/scratch-vm/pull/1128, which is merged, i'll update this PR when it is built.
> Add "read-only" slider and list monitors.

- package.json
- src/components/monitor-list/monitor-list.jsx
- src/components/monitor/list-monitor-scroller.jsx
- src/components/monitor/list-monitor.jsx
- src/components/monitor/monitor.css
- src/components/monitor/monitor.jsx
- src/components/monitor/slider-monitor.jsx
- src/containers/list-monitor.jsx
- src/containers/monitor-list.jsx
- src/containers/monitor.jsx
- src/containers/slider-monitor.jsx
- src/lib/variable-utils.js
Resolves https://github.com/LLK/scratch-gui/issues/942
Makes the slider and list monitors interactive:
- slider monitors update variables
- list monitors do... a lot:
- clicking a list item turns it into an input, selecting all the text
- when active, there is a button that removes the item from the list and activates the next item
- when active, the <kbd>Tab</kbd> key activates the next item (<kbd>Shift</kbd> goes backwards) which wraps the around
- when active, the <kbd>Enter</kbd> key adds a new blank item after the current item, and activates it (<kbd>Shift</kbd> inserts above, h/t @towerofnix for pointing that out).
- when active, the <kbd>ArrowDown</kbd> and <kbd>ArrowUp</kbd> activate the next / prev items (h/t …
> Make slider and list monitors update variables in the VM

- src/.eslintrc.js
eslint-plugin-react assumes you are the most recent stable version of react, which is 16.3, which deprecates certain lifecycle methods. We are not using 16.3 yet, so manually specify the react version for now instead. There does not seem to be an option for using the version listed in the package json 😢
> Fix linting errors from eslint-plugin-react

- src/containers/stage.jsx
Found issue when building routing on top of Scratch GUI. Returning to Scratch GUI would yield error of:
```
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
Please check the code for the Stage component.
```
It seems like other listeners are removed on `componentWillMount` so this matches that pattern with the question listener. I tested multiple `setState`s and this line of code stopped the error from occurring.
Removes event listener from question on `componentWillUnmount` of stage component (container)
Error seen in console.
I'm not sure how to create the tests for this. Would be interested in learning.
Mac
Windows
Chromebook
iPad
Android Tablet
> remove question event listener on stage unmount

- .github/PULL_REQUEST_TEMPLATE.md
The overwhelming experience of testing every browser/OS combination.
Adds instructions to the Browser Coverage section of the PR template to indicate that you should check at least two combinations and not necessarily all of them.
It would take too long to test all of them and it would encourage larger PRs so you wouldn't have to test as often.  This encourages increasing coverage but makes it easier to check.
> Add instructions to PR template browser coverage section

- package.json
See https://github.com/LLK/scratch-render/commit/6cff0f984f753f5c7eb441e74302d218f566bf17
> Update scratch-render to get the babel-built version of fonts

- src/components/stage-wrapper/stage-wrapper.css
- src/lib/hash-parser-hoc.jsx
- src/lib/project-loader-hoc.jsx
- src/playground/blocks-only.jsx
- src/playground/compatibility-testing.jsx
- src/playground/index.jsx
- src/playground/player.jsx
- test/unit/util/hash-project-loader-hoc.test.jsx
- test/unit/util/project-loader-hoc.test.jsx
Separate getting the project id from the `location.hash` (needed for playground) from loading the project by Id - needed by all uses of GUI.
When GUI is embedded (e.g. in www), it will be passed the project id, and the main app will be managing the URL.
Changed the current project-loader test to check that hash-parser+project-loader continues to work as before. Added new project loader test.
Mac
Windows
Chromebook
iPad
Android Tablet
> Project loader refactor

- src/lib/default-project/project.json
Resolves GH-2074
- Replaces white bitmap rectangle with an empty SVG for the default backdrop
- We should bias users towards using the vector editor (particularly during the preview period)
- Resolves (albeit in a "treat the symptom and not the disease sort of way) issue with the default backdrop scaling in Scratch 3.0.
Mac
Windows
Chromebook
iPad
Android Tablet
> Replace white rectangle bitmap with empty svg for default backdrop

- src/lib/project-loader-hoc.jsx
Only call updateProject to load the project if there is a project id, or it’s the default project id.
There's an error in the console `TypeError: Cannot read property 'split' of null` due to loading a null project id in the project-loader-hoc. 
Check the projectId before calling `updateProject`
Tests pass and no more TypeErrors in the console.
/cc @kchadha 
Mac
Windows
Chromebook
iPad
Android Tablet
> Don’t load null project id

- src/components/monitor-list/monitor-list.css
- src/components/monitor-list/monitor-list.jsx
- src/components/monitor/list-monitor-scroller.jsx
- src/components/monitor/list-monitor.jsx
- src/components/monitor/monitor.css
- src/components/monitor/monitor.jsx
- src/components/stage/stage.jsx
- src/containers/monitor.jsx
- src/containers/stage.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1235
Also fixes several other issues in addition to the monitor scaling and positioning:
- Monitors should not be draggable when in fullscreen/player mode
- List monitors should not be editable in fullscreen/player mode, fully:
- Should not be resizable
- Should not be able to add elements via `+` button
- Should not be able to edit elements via text inputs
- Should be able to select text of list monitors in player mode
Fix the above issues in a couple of commits:
- Propagate the `useEditorDragStyle` property from the stage down the the monitors and use it correctly to disable dragging and edit-ability of list fields
- Fix the markup/css so …
> Fix monitor scaling, positioning and draggability in fullscreen mode

- .travis.yml
This brings scratch-gui in line with the rest of the scratch-* packages, and what scratch-www needs for the project preview page.
> Publish develop builds to NPM

- src/components/monitor-list/monitor-list.jsx
- src/components/monitor/monitor.css
- src/components/monitor/monitor.jsx
- src/components/monitor/slider-monitor.jsx
Several issues in https://github.com/LLK/scratch-gui/issues/2097:
Fixes https://github.com/LLK/scratch-gui/pull/2102
Fixes https://github.com/LLK/scratch-gui/issues/2088
See commits individually for each fixes details. Just CSS stuff.
> Fix several minor monitor issues from recent testing

- src/containers/blocks.jsx
Fixes https://github.com/LLK/scratch-gui/issues/2009
A small follow-up to https://github.com/LLK/scratch-gui/pull/2107 that adds the fullscreen mode state flag to the list of "visible modals", making it hide block field editors/ reported values when entering fullscreen mode. 
https://github.com/LLK/scratch-gui/issues/2009 and the recently submitted duplicate https://github.com/LLK/scratch-gui/issues/2113
Tested by following the directions in the linked issues.
> Hide block inputs when entering fullscreen mode

- src/playground/index.css
Fixes https://github.com/LLK/scratch-gui/issues/2027
Force the preview wrapper to have a minimum width/height so that the UI scrolls below those points. We have a pretty well defined minimum viewport size that we have not designed below, so instead of allowing things to just look broken below that point, make it so the entire UI scrolls. 
TL;DR Instead of being super broken on unsupported screen sizes, allow the UI to scroll around to make the intention clear: you need to see this on a bigger window.
Issues with viewports smaller than we have designed for have been reported often, including issues with windows that are too short (so the …
> Force a min viewport size to scroll around the UI instead of breaking

- src/lib/libraries/sprites.json
Resolves GH-1995
- Fixes default costume index (`0`) for cat sprite
- Adds `animals` tag to cat sprites
Mac
Windows
Chromebook
iPad
Android Tablet
> Fix default costume index for cat sprite

- src/components/backpack/backpack.css
- src/components/backpack/backpack.jsx
- src/components/blocks/blocks.css
- src/components/gui/gui.jsx
- src/playground/index.jsx
Another small step toward the backpack! The bottom bar with coming soon.
@carljbowman I want to make sure the colors on this are right. 
@thisandagain @rschamp I want to make sure I understand what we want in the stand-alone preview build. This PR allows the backpack visibility to be controlled via a prop (to make it easier to remove for offline build, etc.) but I did enable it for the standalone preview build. Is that what we want to do? Or did we want to hide it completely from preview?
> Show a coming-soon backpack

- package.json
- src/lib/make-toolbox-xml.js
- src/lib/opcode-labels.js
Shows the username block in the toolbox. Will bring in https://github.com/LLK/scratch-vm/pull/1163
> Show username block in sensing

- src/containers/blocks.jsx
Fixes https://github.com/LLK/scratch-gui/issues/2120
re-enable toolbox refreshing, the way we do after doing a real toolbox refresh, after the blocks tab is re-shown after being hidden. 
The full workspace refresh which is done the line before causes refreshing to be disabled. See the comments on line 148-150 for more info.
Toolbox refreshing was not happening when it needed to after switching tabs. 
Repro the test case in the lined issue.
not browser related.
----
/cc @gnarf, @rschamp
> Fix toolbox refreshing for new variables after switching tabs

- src/containers/gui.jsx
Fixes https://github.com/LLK/scratch-gui/issues/2137#issuecomment-391474843
Move the error boundary outside of the project loader hoc. 
/cc @chrisgarrity 
Tested by loading a project with a non-existent asset. we get back to where preview is where we show the "oops" screen instead of a blank one. 
I'm looking into how we can get it to load the default asset instead of breaking entirely.
> Move error boundary out beyond the project loader

- src/components/action-menu/action-menu.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1891
Force the tooltips to go away, because they do not play nicely with touch since they are based on mouse position.
The action menus are awkward on touch because they stay open!
Tested on various touch devices.
Broken
Fixed
Mac
Windows
Chromebook
iPad
Android Tablet
> Force the tooltips to close to fix touch devices

- src/components/sprite-selector/sprite-selector.css
- src/components/stage-selector/stage-selector.css
- src/components/stage-selector/stage-selector.jsx
- src/containers/stage-selector.jsx
Fixes https://github.com/LLK/scratch-gui/issues/1524
/cc @carljbowman I just borrowed the exact styling for the sprite tile for the droppability indication, the hover animation and the dropped indication. The wiggle is a a bit crazy for the long bar, but I kinda love it. Any other thoughts?
Hook up the stage to work the same way as the sprite selector tiles. Stage has a target id the same way the sprite tiles do, so the block drop works without any additional work. 
Also refactors the animation stuff from sprite selector because the autoprefixer does a lot of that automatically.
Working on testing different browsers.
Check the …
> Share blocks to the stage

- src/containers/list-monitor.jsx
[#2177](https://github.com/LLK/scratch-gui/issues/2177)
Currently, when shift-tab is pressed on a focused list item, the list monitor shifts focus to the previous element. However, this does not work if the first list item is focused.
No tests needed.
Mac
Windows
Chromebook
iPad
Android Tablet
> Change list wraparound logic when shift-tab pressed

- src/components/action-menu/action-menu.css
[#2066](https://github.com/LLK/scratch-gui/issues/2066)
In Firefox, remove the ugly border and icon offset when a "Choose a Sprite" menu button is active.
Image of Firefox's border:
No tests needed.
Mac
Windows
Chromebook
iPad
Android Tablet
> Change styles of action menu button

- src/components/monitor/list-monitor.jsx
Fixes #2112 
Adds the "no-drag" class to the "+" button so it doesn't 
To prevent dragging by the "add an item" button 😛
> Prevent dragging the "+" button

- src/components/library/library.jsx
[#2099](https://github.com/LLK/scratch-gui/issues/2099)
When a library category button is clicked or the search query is modified, reset the scroll position to the top.
No tests needed.
Mac
Windows
Chromebook
iPad
Android Tablet
> Reset scroll position when clicking library category button

- src/components/asset-panel/asset-panel.css
- src/components/backpack/backpack.css
- src/components/backpack/backpack.jsx
- src/components/gui/gui.css
- src/components/gui/gui.jsx
- src/containers/backpack.jsx
- src/playground/index.jsx
- test/integration/backpack.test.js
Next step for backpack work.
Also includes a fix for https://github.com/LLK/scratch-gui/issues/2182
Add some more skeleton for the backpack. Allow it to be passed a `host` param, which controls whether the "coming soon" tooltips appear and whether the backpack can be toggled. Right now  `contents` defaults to `[]`, so the "Backpack is empty" message will appear.
@rschamp In addition to accepting a "backpackHost" prop in the GUI container, this change also allows the index playground to read the backpack_host param from the url query string, as a first step towards making this testable. If you think this is not a good route, let me know. The alternative I considered was creating a separate …
> Toggle backpack when backpack host param is available

- src/components/browser-modal/browser-modal.jsx
- src/lib/supported-browser.js
#2018 
Blocked Vivaldi and Changed browser-modal's text.
#1460 
Tested on my PC, Windows 7 Home Premium, Firefox (not blocked), Chrome (not blocked), and **Vivaldi (blocked)**
Mac
Windows
Chromebook
iPad
Android Tablet
> Block Vivaldi

- webpack.config.js
- Build scratch-* dependencies with babel-loader
- Disable babelrc use by babel-loader so lower dependencies use the stated webpack babel configuration
Sibling of https://github.com/LLK/scratch-vm/pull/1106
> Build scratch-* dependencies with babel-loader

- package.json
- test/helpers/selenium-helper.js
- test/smoke/browser.test.js
@BryceLTaylor I wanted to make sure that we don't keep making mistakes w/r/t older browsers, so I gave the hosted VMs on Sauce a try (we had intended to use this in the past, but haven't had the time/need).
I wanted to get this smoke test into the repo so that we can continue building on it in the future. I propose we use this script in the following way:
Step 1 (this PR): Instead of having "test IE and old Safari" on the manual smoketest checklist, use this script instead.
This script can be run locally in the following way 
```
SAUCE_USERNAME=<sauce username> \
SAUCE_ACCESS_KEY=<sauce access key> \
SMOKE_URL=https://llk.github.io/scratch-gui/develop \
npm run test:smoke
```
The sauce username/access key can be a free trial account, or if this is useful, a team account. For reference, …
> Add IE11 and Safari 9/10 tests to browser smoke test using Sauce

- src/containers/gui.jsx
- src/containers/project-loader.jsx
- src/lib/project-loader-hoc.jsx
Fixes an issue where we can't see which projects are giving us errors, and which modes projects are being brought in by (file vs. server)
Making the project load analytics use `label` instead of `value` makes it possible to see which projects are getting loaded, making it easier to see those projects for users with errors.
Including the window.location.hash in the project loader error message also creates a more direct way to see where load errors are coming from.
> Better project loading analytics and errors

- .travis.yml
Resolves #2262 
Start publishing develop builds to a separate release channel from `latest` called `develop`. I also moved the `before_deploy` section in the .travis.yml to ...before the ...deploy section for readability (although this looks like I moved the script section).
This allows us to pin scratch-www to `scratch-gui@latest`, and ensure that it will be up to date with the most recent smoke-tested (or smoke-testable) build. If need be, we still have the ability to pin it to a specific develop version on the `scratch-gui@develop` channel.
I tested that pushing to the smoke branch …
> Npm preview channel

- src/components/library-item/library-item.css
- src/components/library/library.css
#2266, #2267
Change the following in the extension library:
* Each item's image is now flush with the top of the card.
* The library now functions correctly when zoomed out enough for all the items to fit on one row.
Mac
Windows
Chromebook
iPad
Android Tablet
> Change CSS

- src/components/gui/gui.css
- src/components/sprite-selector/sprite-selector.css
#2295 
The scroll bar in the sprite selector area shows up if and only if it is needed.
Mac
Windows
Chromebook
iPad
Android Tablet
> Fix sprite selector scroll bar

- src/components/action-menu/action-menu.jsx
- src/components/gui/gui.jsx
- src/containers/backdrop-library.jsx
- src/containers/costume-tab.jsx
- src/containers/gui.jsx
- src/containers/stage-selector.jsx
#2188 
When the "choose a backdrop" button is pressed (the biggest button in the action menu) but the backdrop library is closed without selecting a backdrop, the Stage's paint editor tab is **not** opened. Instead, nothing happens.
Behind the scenes, there are several changes:
* The BackdropLibrary component is no longer nested in the CostumeTab component; it has been moved to the root GUI component, as discussed in the issue.
* Clicks on the action menu don't propagate up to the stage selector. This way, a click to the action menu won't select the stage as well.
* The third commit ("fix bug") explicitly shifts focus to the stage immediately after a backdrop is added, which is necessary.
Mac
Windows
Chromebook
iPad
Android Tablet
> Fix "Opening the backdrop library causes the stage backdrop editor to become selected"

- src/components/browser-modal/browser-modal.css
- src/components/cards/card.css
- src/components/coming-soon/coming-soon.css
- src/components/context-menu/context-menu.css
- src/components/drag-layer/drag-layer.css
- src/components/gui/gui.css
- src/components/import-modal/import-modal.css
- src/components/loader/loader.css
- src/components/menu-bar/menu-bar.css
- src/components/modal/modal.css
- src/components/monitor/monitor.css
- src/components/preview-modal/preview-modal.css
- src/components/stage-header/stage-header.css
- src/components/stage/stage.css
- src/components/webgl-modal/webgl-modal.css
- src/css/z-index.css
#2205
#2189
Move z-index values into a new file called "z-index.css".
This makes it obvious which components overlap what.
No tests needed.
Mac
Windows
Chromebook
iPad
Android Tablet
> Move z-index values to separate file

- src/components/monitor/monitor.jsx
- test/integration/blocks.test.js
Fixes integration test which was failing trying to use the context menu
Fixes https://github.com/LLK/scratch-gui/issues/2329
Use React.createPortal to put the `position: fixed` context menu at the end of the document, instead of within the `transform`ed viewport of the monitor container.
`react-contextmenu` does not work when used within a parent that has `transform`s https://github.com/vkbansal/react-contextmenu/issues/147. The "create variable" smoke test was doing exactly what it is supposed to do, it was failing because there was no context menu to change to "slider" type. I didn't catch that when testing manually because I forget the …
> Move context menus for monitors outside of the document flow.

- .travis.yml
- clean_greenkeeper.sh
- package.json
- prune-gh-pages.sh
Trim the directories in gh-pages after each build to match our active branches. It also begins building all branches, including master into a subdirectory on gh-pages, and due to this change, redirects llk.github.io/scratch-gui/ to llk.github.io/scratch-gui/master/. We should land #2334 first so the gh-pages branch is already set up for this change.
Right now there is no cleaning up of directories in gh-pages when branches are deleted. This means that our gh-pages branch is continually growing, and occasionally gets to the point where GitHub fails to build the gh-pages site after successful pushes to the gh-pages branch.  This in turn causes confusion by developers when changes from a successful build aren't …
> Prune gh-pages to match our branch list after each build

- .travis.yml
Our deploys are complaining about how many times we set `user.name` and are failing.
> Only run before_deploy phase once

- src/components/asset-panel/selector.css
- src/components/asset-panel/selector.jsx
- src/components/asset-panel/sortable-asset.jsx
- src/components/drag-layer/drag-layer.css
- src/components/sprite-selector-item/sprite-selector-item.css
- src/components/sprite-selector/sprite-list.jsx
- src/components/sprite-selector/sprite-selector.css
- src/components/sprite-selector/sprite-selector.jsx
- src/components/target-pane/target-pane.jsx
- src/containers/costume-tab.jsx
- src/containers/paint-editor-wrapper.jsx
- src/containers/sound-tab.jsx
- src/containers/sprite-selector-item.jsx
- src/containers/target-pane.jsx
- src/lib/drag-constants.js
- src/lib/drag-utils.js
- src/lib/sortable-hoc.jsx
- test/unit/util/drag-utils.test.js
_Note: sprite reordering depends on the API from https://github.com/LLK/scratch-vm/pull/1231_
Fixes https://github.com/LLK/scratch-gui/issues/225
Fixes https://github.com/LLK/scratch-gui/issues/295
Fixes https://github.com/LLK/scratch-gui/issues/1602
Create a `SortableHOC` that wraps the area one wishes to be sortable, and wrap each item in a  `SortableAsset`, which takes care of reordering the elements using the flex-order property. SortableAsset is not an HOC because it needs a ref to an actual DOM node, to be registered with the SortableHOC via `addSortableRef` and `removeSortableRef` callbacks. 
Some limitations:
- The sorting area that renders the list of sortable assets needs to be …
> Make costumes, sounds and sprites sortable

- src/components/language-selector/language-selector.css
- src/components/language-selector/language-selector.jsx
- src/components/menu-bar/menu-bar.css
- src/components/menu-bar/menu-bar.jsx
- src/containers/language-selector.jsx
- src/reducers/menus.js
Resolves https://github.com/LLK/scratch-gui/issues/2325
Allows the language selection menu to be active if `?enable=language` is in the URL, otherwise shows a ‘coming soon’ tooltip. This can also land on a branch if we don’t want that available on preview.
- language menu opens if the globe is clicked
- language menu closes if mouse is clicked anywhere outside the language selector
- language list is imported from scratch-l10n
- current locale is updated if another language is selected (i.e. the current language selected changes)
Not in this PR:
- styling of language selector
- actually changing the messages!
You can try it at https://chrisgarrity.github.io/scratch-gui/feature/enable-languag …
> Enable language selection menu

- package.json
- src/containers/sound-library.jsx
Depends on llk/scratch-audio#88
- Stopping sounds in SoundLibrary fades them out avoiding potential audio clipping
Use new `AudioEngine.decodeSoundPlayer` to decode sounds in SoundLibrary and have a promise resolving to a SoundPlayer instance returned. This SoundPlayer can control playback on its own and fades out when told to stop playback.
`scratch-audio` is being rewritten to help resolve vm bugs like `deleting a clone stops sprite sounds`. SoundLibrary depends on a small part of `scratch-audio` so that is being updated to use the slightly different new API.
> use new SoundPlayer in SoundLibrary

- src/containers/list-monitor.jsx
Fixes https://github.com/LLK/scratch-gui/issues/2361
Force new active index and value after hitting the remove button.
Old: ![list-remove-issue](https://user-images.githubusercontent.com/654102/41471840-b4e0281a-7082-11e8-86d5-7877826dd4c6.gif)
Fixed:
> Force new active index and value after hitting the remove button.

- src/components/backpack/backpack.css
- src/components/backpack/backpack.jsx
- src/containers/backpack.jsx
- src/lib/backpack-api.js
- src/playground/index.jsx
Next step for the backpack is to get basic loading of the backpack contents into the list. This PR loads up the first page of contents.
The functionality here is very limited (just loads a single page into the list), but this PR is mostly about infrastructure in terms of backpack-api and session token/username information.
As a compromise to allow the backpack to be tested independently from the servers, I made the backpack container first try to get session information from the state tree matching `scratch-www`, then if that is not available try to get it from url params the same way the host is retrieved. 
I've tested this using the backpack server locally, using the included dummy scratchteam/sessionid user. 
It loads content …
> Backpack load contents from server

- src/components/asset-panel/selector.jsx
- src/components/sprite-selector-item/sprite-selector-item.css
- src/components/sprite-selector/sprite-list.jsx
- src/containers/target-pane.jsx
- src/lib/sortable-hoc.jsx
Resolves https://github.com/LLK/scratch-gui/issues/1983
Resolves https://github.com/LLK/scratch-gui/issues/2395
Allows target pane to handle "drop" events from the costume/sound tiles, which duplicates the costume/sound to that sprite. 
Of note:
- You can share assets to the sprite that already owns that asset ("yourself"). This duplicates the asset. This is an existing behavior of scratch 2...
- This does not work on touch yet because of the reliance of hoveredTarget on mouseEnter/mouseLeave events, same issue impacting sharing blocks. I'm working on a fix.
- In order to prevent reorders from happening when sharing assets, I confined the reorder logic in sortableHOC to only work when you …
> Sharing costumes and sounds to other sprites and the stage

- package.json
- src/lib/make-toolbox-xml.js
Use Blockly messages for category names in the default toolbox XML to allow the names to be localized from the Msgs table.
The most recent update to scratch-blocks allows localization of Category labels using the Blockly message lookup syntax `%{BKY_messagename}`.
The category names are already defined, so we can just go ahead and use them. The stage label for the motion category can also get handled this way, but the string needs to get defined in scratch-blocks first.
> Localize category names in default toolbox

- src/lib/libraries/backdrops.json
- src/lib/libraries/costumes.json
- src/lib/libraries/sprites.json
Resolves GH-2310
Resolves GH-2349
Resolves GH-2375
- Changes name of the "theatre" backdrop to "theater"
- Resolves issue with "heart" backdrops
- Adds tags to ice skates (note: this will likely be removed / replaced soon
- Adds "baseball" theme
- Adds "spooky" theme (replaces old ghosts, bats, and woods backdrop)
Mac
Windows
Chromebook
iPad
Android Tablet
> Various fixes & additions for library assets

- src/components/stage/stage.css
- Resolves #2413 
Forces the stage canvas element to use `box-sizing: content-box;` so that the border is not included in the sizing. 
See bottom of https://github.com/LLK/scratch-gui/issues/2413 for explanation
It is not clear to me that this fixes any kind of blurriness, though. The original issue does not cite a specific project or give any specifics, so it is tough for me to tell if this helped. 
@cwillisf if you can repro the original blurriness, could you check if this fixes it?
> Fix 2px error in stage sizing

- src/components/sprite-selector/sprite-list.jsx
- src/components/sprite-selector/sprite-selector.css
- Resolves https://github.com/LLK/scratch-gui/issues/2430
A wrapper element was added when doing sprite reordering, this brings the CSS that was within that wrapper out to the wrapper so that the flex layout works correctly
Broken (as discovered by @chrisgarrity)
Fixed
> Fix the sprite layout by making the layout code apply to the wrapper

- src/components/monitor-list/monitor-list.css
- Resolves #2106 
Remove “clear field” X button on certain inputs for Edge?
To remove the extra x.
Tested by inspection. Before:
After:
Mac
Windows
Chromebook
iPad
Android Tablet
> Got rid of extra Edge x on monitor list

- src/lib/app-state-hoc.jsx
- src/lib/detect-locale.js
- test/unit/util/detect-locale.test.js
Language detection function that checks browser setting and lets URL parameter (locale= or lang=) override the browser setting. Also fixes a bug where locale was being ignored (e.g., pr-BR was recognized as 'pt').
- Resolves #510
Tries to use locale from `navigator.language`, allows options on the URL to override.
Added a basic test for the new detectLocale function.
Mac
Windows
Chromebook
iPad
Android Tablet
> Added automatic detection of locale from browser langauge

- src/lib/blocks.js
- src/lib/make-toolbox-xml.js
- Resolves #2320 (depends on https://github.com/LLK/scratch-blocks/pull/1609)
Use the new `ScratchMsgs.translate` function to generate localized menus and default values in the toolbox.
Replace hard-coded string values with localized strings to support other languages.
Current tests run (when using the new scratch-blocks).
Mac
Windows
Chromebook
iPad
Android Tablet
> Use translations from scratch-blocks to generate menus

- src/components/blocks/blocks.css
Partial solution for https://github.com/LLK/scratch-gui/issues/2396
Do not hide the scrollbar for blocks categories. Only works for chrome, safari and edge. Firefox will need a separate fix.
https://github.com/LLK/scratch-gui/issues/2396
Mac
Windows
Chromebook
iPad
Android Tablet
> Hide category scrollbar for blocks for webkit/edge browsers

- src/components/gui/gui.jsx
- src/components/stage/stage.jsx
- src/containers/dom-element-renderer.jsx
- src/containers/gui.jsx
- src/containers/stage.jsx
- src/playground/player.jsx
This is for demonstration purposes, if this is the way we decide, I will make official APIs on the VM and the renderer for checking for a renderer or canvas respectively.  I'm not 100% on adding another wrapper around the canvas, but this seemed like the easiest to read way to do it, and doesn't break any CSS.
@paulkaplan When @cwillisf and I spoke yesterday about the possibility of attaching a new canvas to the renderer, we decided it wouldn't be as clean as keeping the canvas around. The WebGL context stores a lot of state that would need to be maintained, and we would invariably miss something, or it could break down the line as we changed things.
/cc @chrisgarrity 
Fixes the issue where the stage becomes blank after changing …
> Hack to make the renderer own the stage canvas

- src/containers/slider-monitor.jsx
- src/lib/monitor-adapter.js
Fixes #2409.
Makes boolean values (true, false) show up in (list and variable) monitors correctly. Before, they wouldn't show up at all.
Compatibility with 2.0 and convenience.
Manually tested with [this project](https://scratch.mit.edu/projects/229992327/). Screenshots below. From left to right: 2.0, 3.0 before this PR, 3.0 with this PR.
Lists also tested (no screenshots here for brevity). They work right.
N/A (tested on firefox/debian).
> Fix booleans not showing up in monitors

- src/components/cards/card.css
- Resolves https://github.com/LLK/scratch-gui/issues/1961
Uses the full font-family declaration for the card contents
Font was not being rendered correctly on the last card of how-tos, see https://github.com/LLK/scratch-gui/issues/1961
Tested on windows VM.
> Add font-family for card css

- src/lib/opcode-labels.js
- Resolves #
Uses ScratchBlocks.ScratchMsgs to translate labels for monitors.
Allows translation of monitor labels for predefined monitors (e.g., volume, direction)
Current tests still pass.
Mac
Windows
Chromebook
iPad
Android Tablet
> Translate monitor labels

- src/containers/preview-modal.jsx
- src/lib/tablet-full-screen.js
Using `bowser` to detect tablets, and type of browser to call either `webkitRequestFullScreen()` or `mozRequestFullScreen()`
Full screen request must happen in reponse to a user-action, so it’s included in the ‘try-it’ handler for the preview modal.
We'll need to figure out where this goes when we no longer have the preview-modal.
Parts of the gui UI end up getting cut off on 7-inch tablets due to the amount of browser 'chrome'  (tabs, URL, menus etc). Detecting that it's a tablet and requesting full screen when the user decides to 'Try It' in the preview modal makes the UI much more usable.
Requests that the browser run in full screen mode if it's a tablet
Mac
Windows
Chromebook
iPad
Android …
> Try to run in full screen on tablets

- package.json
- src/components/stage-wrapper/stage-wrapper.jsx
- src/components/stage/stage.jsx
- src/containers/dom-element-renderer.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/2510
- Resolves https://github.com/LLK/scratch-gui/issues/2509
Use the `to-style` module to correctly translate the style object to a style string in the DOMElementRenderer.
So that the width/height can be applied to the canvas as CSS, since the width/height attributes are managed by the renderer.
I also removed the `shrink={0}` property, since it isn't doing anything.
Manually tested the issues linked above
Mac
Windows
Chromebook
iPad
Android Tablet
> Correctly apply react style object to the dom element renderer

- src/containers/tips-library.jsx
Another approach would be to have the title be part of what’s imported from `lib/libraries/decks/index.jsx`
- Resolves #2499 
Uses react-intl to translate the text.
Title should be translated.
Current tests still run
Mac
Windows
Chromebook
iPad
Android Tablet
> Localize how-tos title

- package.json
The babel extraction process includes translations from node modules. The extraction process creates two directories: `translations/messages/src` and `translations/messages/node_modules`. When generating the file to sync with transifex we only want the messages in the `src` directory. The paint editor messages in transifex are synced from the paint editor repo.
If the node_modules directory isn't ignored we end up with duplicate keys, and building the file to sync with transifex fails.
> ignore paint editor messages in gui

- package.json
- src/containers/dom-element-renderer.jsx
- src/playground/index.jsx
Bring this fix back from smoke to develop. These are the fixes for IE11 and Safari10. 
/cc @rschamp @chrisgarrity
> Shim array#includes and fix style assignment. Fixes IE11 and Safari10

- src/lib/make-toolbox-xml.js
Resolves GH-2507
Update the `>`, `<`, and `=` reporters in the "Operators" category to use `50` as the default value rather than `100`.
Mac
Windows
Chromebook
iPad
Android Tablet
> Update default values for GT, LT, EQ operators to be 50

- src/lib/make-toolbox-xml.js
Change the order of the blocks in the menu, so that "play sound until done" appears first, followed by "start sound". 
We made this change to make it more likely that people will try out the "play sound until done" block first, before the "start sound" block. We want them to use the "until done" block first because it seems easier to understand its behavior when it is used in a stack of other command blocks, or in a loop.
> Swap order of “start sound” and “play sound until done”

- src/components/library-item/library-item.jsx
- src/containers/extension-library.jsx
Eliminate warnings and errors due to library item text (name and desctiption) being localized components instead of simply a string. Some are not localized (e.g. LEGO EV3), so either string or component is still possible.
Check whether `item.name` is a string or an object. If it's an object grab the `defaultMessage` prop for reactGA. Also change LibraryItem.propTypes to allow description to be a string or node.
Eliminates errors and warnings in the console when clicking on library items.
Current tests pass.
Mac
Windows
Chromebook
iPad
Android Tablet
> Handle localized library strings for Analytics

- package.json
- src/containers/blocks.jsx
- src/containers/connection-modal.jsx
- src/lib/blocks.js
- Resolves https://github.com/LLK/scratch-gui/issues/2542 and https://github.com/LLK/scratch-gui/issues/2541, together with https://github.com/LLK/scratch-blocks/pull/1637
Also closes https://github.com/LLK/scratch-gui/pull/2583
Wires up the getExtensionStatus api from the blocks the same way the monitors are hooked up.
> Fix device status indicator updating issues

- src/components/menu-bar/menu-bar.jsx
The onMouseUp handler for the menu rerenders the language menu before the select onChange function runs on Firefox. So it resets the language value back to the previous value and the locale doesn’t update.  With this change it doesn’t fire the openlanguageMenu action if the menu is open.
- Resolves #2538 
Add new handler for onLanguageMouseup that checks for whether the menu is already open.
(Note: the `mapDispatchToProps (dispatch, props)...` wasn't working. The props are just the ones passed in, not anything mapped to state. It appeared to work, but it turned out I still had the onMouseup handler checking for the menu being open.) …
> Handle mouseUp on language select for firefox

- src/components/blocks/blocks.css
- Resolves the issue @kchadha mentioned where after doing certain things, you could not share the blocks anymore. 
Set `pointer-events: none` on the drag surface SVG, so that it does not prevent mouse-enter events.
The drag surface was sometimes preventing the mouseenter events from happening.
> Stop block drag surface from stopping mouse enter events

- src/components/stage-selector/stage-selector.css
- src/components/stage-selector/stage-selector.jsx
- Make stage look more distinguished: add some space around the preview such that it is not flush with the stage area width, add a border all the way around, and round the corners to match the actual stage.
- Make the stage select state more apparent and consistent with the Sprite selected state
Currently, the stage preview within the Stage Info Area was not very noticeable, especially when no stage has been added and it appears white.  
In addition to the stage preview not standing out, there was some concern that the Stage's selected state was not very noticeable. We should continue to monitor this issue with these changes.
> Update Stage Select UI

- package.json
- src/playground/index.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/2199
Add the Intl polyfill, it is the same one used by scratch-www.
Safari 9 needs the polyfill.
Tested using Safari 9 iOS simulator
> Add intl polyfill for Safari 9

- src/lib/libraries/extensions/index.jsx
Make the micro:bit extension name match the official branding, and shorten the description on the extension library tile so it fits on one line.
> Fix micro:bit extension name and description

- src/containers/blocks.jsx
Fixes issue introduced by variable scoping work where renaming variables no longer worked.
Now both creating a new global variable and renaming a global variable should check for name conflicts with any other sprite.
Refactor variable prompt callback function to always pass the list of additional variable names. Scratch blocks will decide whether to use it or not based on whether the variable being created/renamed is global or not (respectively).
This PR is related to the following: LLK/scratch-blocks#1644
https://llk.github.io/scratch-gui/rename-var-bugfix-travis/
> Fix rename variable bug

- src/lib/libraries/backdrops.json
- src/lib/libraries/costumes.json
- src/lib/libraries/sounds.json
- src/lib/libraries/sprites.json
- Minor fixes / adjustments to the "bat" sprite and costumes
- Minor adjustments to the "jamie" (now called "jamal") sprite and costumes
- Minor adjustments (normalization) of "cat" assets
- Minor fix for first costume of "D-Money"
- Adds new sprites to the "basketball" theme
Mac
Windows
Chromebook
iPad
Android Tablet
> Updates to sprite, costume, and backdrop libraries

- test/smoke/browser.test.js
Safari 9 now loads, so we can remove the `.skip` in the browser integration test
> Do not skip safari 9 browser test because it works now

- src/components/gui/gui.css
Goes along with https://github.com/LLK/scratch-blocks/pull/1646
Matches the new width of the category menu that allows more of the translated category names to fit.
Increase the width of the add-extension button by .5rem
localization
Mac
Windows
Chromebook
iPad
Android Tablet
> Widen add-extension button to match category.

- src/components/connection-modal/error-step.jsx
- src/components/custom-procedures/custom-procedures.jsx
- partially resolves #2535 
- _‘block name’ default text is in scratch-blocks_
* Added localization for ‘Make a Block’
The changes in `error-step.jsx` were needed because the same id was defined in there and `unavailable_step.jsx`. The scripts to generate the json file for Transifex give an error if the same id is defined in two places. In error step it simply uses the id without redefining default value etc. The alternative would be to add a new messages.jsx file that has the definitions for shared text and include that in both places that use them.
localization
Current tests run, …
> Localize custom procedure modal title

- src/lib/libraries/extensions/index.jsx
Resolves GH-2621
- Change "video motion" to "video sensing" in the extension library
- Remove extensions that have an unclear launch date
- Minor re-ordering of the extension library thumbnails & clean-up
Mac
Windows
Chromebook
iPad
Android Tablet
> Change 'video motion' to 'video sensing' and minor clean-up to extension library

- src/playground/index.ejs
Add a meta tag to make sure google doesn’t try to autotranslate the editor:
https://support.google.com/webmasters/answer/79812?hl=en
This will also need to get added to the preview page (or anywhere we use gui), but we probably don't want to turn it off globally on www.
> Don’t let Google try to auto translate the GUI

- src/components/connection-modal/scanning-step.jsx
Resolves https://github.com/LLK/scratch-gui/issues/2652
It seems that the way react was recycling components was causing the render bug from #2652. I'm not 100% sure why, but just using a plain div fixed the issue...
> Prevent react recycling components causing safari render bug

- src/containers/blocks.jsx
- Resolves #2515
Call `updateToolbox` whenever the blocks container updates and is visible so that changes to dynamic menus (e.g. when a costume is renamed) are picked up. 
Update `setLocale` to call `updateToolbox` so that the toolbox refresh gets re-enabled in this updated workflow. This is needed for getting translated toolbox strings like 'Hello' and 'Hmmm...' to stay in sync with language changes.
/cc @gnarf 
Manual testing of different changes to dynamic menus, switching sprites, switching tabs, changing languages, etc.
Mac
Windows
Chromebook
iPad
Android Tablet
> Update Toolbox when blocks container updates and is visible.

- src/lib/libraries/extensions/index.jsx
This PR enables the EV3 and micro:bit extensions.
Waiting on final testing from @ericrosenbaum @BryceLTaylor.
> Enable EV3 and micro:bit extensions

- src/containers/project-loader.jsx
- Resolves an issue found during smoke testing where Safari 11.0 was not uploading projects.
Remove the use of .finally which is not supported by Safari or Edge.
> Fix project loader cleanup function. Safari does not support the use of .finally

- src/components/library/library.jsx
This replaces the event-based search analytics because that method does not allow us to get the advantages of more search-specific analytics.
> Use pageview with query param for tracking search usage

- src/components/language-selector/language-selector.jsx
Right to left (RTL) languages are not yet fully supported in the editor, so we don't want to give the impression they are by including them in the menu.
Translators can still load the language with the `?locale=he` URL argument.
Currently the excluded languages is just 'he', but I wanted to write it in such a way that it can be used for multiple languages later if we need it.
> [MASTER] Temporarily exclude RTL languages from the menu

- src/components/modal/modal.css
- Resolves #2700 
This PR adds `z-index: 1` to the `.header-item-help` class in modal.css
Without setting a z-index on the help item in the extension connection modal, Firefox does not allow users to click on the "help" link. Adding a z-index to match the working close button in the header fixes this issue, and does not break other browsers.
Mac
> Make extension help links clickable in modal

- src/components/monitor/list-monitor.jsx
- Resolves #2473
It makes button cursors change only when the monitor is draggable, which means it is in fullscreen.
It could confuse some users if their cursor changed on a button that doesn't do anything.
> Fix cursor in fullscreen

- src/components/asset-panel/selector.css
- src/components/sprite-selector/sprite-selector.css
- Resolves #2491
Changes brightness from 20% to 0% to make it dark enough to not see the text.
It could confuse users if the sprite is still faintly visible.
> Fix shadow placeholder color

- src/containers/stage.jsx
Resolves #1870 
Implements outstanding feature to pop dragging sprites to the front of the renderer draw list permanently, not just while it is being dragged. 
Use the `target.goToFront` to bring the sprite forward at the start of the drag. This works for both editor and player drag modes.
> Bring dragging sprites to front

- src/containers/blocks.jsx
Resolves LLK/scratch-blocks#1447
Resolves LLK/scratch-blocks#1574
Clear the workspace undo state when a workspace update has been emitted.
Keeping the old workspace undo state around causes weird behavior like blocks from the previous another sprite or project's workspace showing up (see issues linked above).
Manual testing with:
- switching sprites
- switching between the code, costumes, and sounds tabs, and 
- loading new projects with a file or through project ID in the hash
Mac
Windows
Chromebook
iPad
Android Tablet
> Clear the workspace undo when the workspace updates.

- src/lib/vm-listener-hoc.jsx
- Resolves https://github.com/LLK/scratch-vm/issues/306, depends on https://github.com/LLK/scratch-vm/pull/1387
So that the username can be shown when it is set!
---
/cc @rschamp this uses the same way of getting the username from the session as the backpack code, so hopefully this is right. I also checked that this will be exported to the gui npm package used by www, and it _seems_ like the right place for it?
> Add username setting to vm listener HOC

- src/components/asset-panel/selector.css
- Resolves issue where the bottom asset in the costume/sound list could not be reached because of the add button.
Pad bottom of the list to allow it to scroll enough to reach
> Pad bottom of costume/sound list to allow you to reach the bottom tile

- src/components/cards/card.css
- src/components/cards/cards.jsx
- src/lib/libraries/decks/index.jsx
Enforce this by using `slice` so that no more are ever shown, which would mess up the layout.
Also fixes the issue where the card text could push out when translated into other languages
- Resolves https://github.com/LLK/scratch-gui/issues/2526
- Resolves https://github.com/LLK/scratch-gui/issues/2719
Make the deck preview wider and more padded out from the edges. Also enforce a max width to force titles to wrap.
> Show only 2 other tutorials in last step of each tutorial.

- src/components/menu-bar/menu-bar.jsx
- src/containers/controls.jsx
- src/containers/turbo-mode.jsx
- src/lib/vm-listener-hoc.jsx
- src/reducers/gui.js
- src/reducers/vm-status.js
- Resolves https://github.com/LLK/scratch-gui/issues/1966
First commit hooks up the new turbo mode events from https://github.com/LLK/scratch-vm/pull/1413 (merged) to the vm listener, and moves the project run state listener out of the controls container to put both related status flags in a single reducer.
Second commit enables the turbo mode menu item, using a render function component as the project saver so it can wrap the menu item.
/cc @carljbowman I implemented the menu item as a simple on/off toggle, not sure if that is what we wanted or not? Here is what it looks like
> Turbo mode menu 

- src/components/backpack/backpack.jsx
- src/components/stage-selector/stage-selector.jsx
- src/containers/backpack.jsx
- src/containers/stage-selector.jsx
- src/lib/drop-area-hoc.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/2452
Extracts the logic for testing if an asset drag is occurring over your component and calling onDrop when it drops. Use this HOC for both the backpack and the stage container. 
So that asset dropping could work on the stage!
> Share costumes and sounds to stage

- src/containers/connection-modal.jsx
Resolves an issue that came up working with @ericrosenbaum about understanding device connection issues happening in the wild. 
Add events for:
1. **Connecting** - after the device list has been discovered and the connect button has been clicked on one of them. Doesn't include any device identifiers, only the extension id (microbit, ev3, etc.)
2. **Connected** - when the device has been connected. 
3. **Connection Error** - when an error was encountered during the connection process. Does not get triggered when scratch-link is missing, since that would be basically the same as the number of people who add the extension, which comes from extension library instrumentation.
4. **Help** - when …
> Instrument device connection events

- src/playground/player.jsx
- test/helpers/selenium-helper.js
- test/integration/examples.test.js
Resolves `/player.html#<project id>` not loading the project with id `<project id>`
Pass on uncaptured props from Player component to GUI
Passing on the props down from the HashParserHOC allows the HOC to load the project specified by the hash and give this information to the GUI.
I modified the integration tests to gather "performance" logs, which include which requests are made by the browser. This allows us to make sure that the project is actually being requested in the examples.
N/A
> Fix loading projects by hash on player example

- src/components/backpack/backpack.jsx
- src/components/sprite-selector/sprite-list.jsx
- src/components/stage-selector/stage-selector.jsx
- src/containers/backpack.jsx
- src/containers/stage-selector.jsx
- src/containers/target-pane.jsx
- src/lib/drop-area-hoc.jsx
Make it possible to drop backpack assets on sprite tiles and on the stage.
There is a note in the code about how this does not implement "new sprite from backpack costume", which we can think about later. 
This depends on the vm PR https://github.com/LLK/scratch-vm/pull/1399
It is also based on https://github.com/LLK/scratch-gui/pull/2727, so only the second commit is new here
> Add from backpack to sprite/stage tiles

- webpack.config.js
make development faster by always building assets for dist directory, even when run without NODE_ENV=production .
> build dist, even when run without NODE_ENV=production

- src/components/button/button.css
- src/components/camera-modal/camera-modal.css
- src/components/camera-modal/camera-modal.jsx
- src/components/connection-modal/connection-modal.css
- src/components/connection-modal/connection-modal.jsx
- src/components/connection-modal/error-step.jsx
- src/components/connection-modal/unavailable-step.jsx
- src/components/custom-procedures/custom-procedures.css
- src/components/custom-procedures/custom-procedures.jsx
- src/components/filter/filter.css
- src/components/modal/modal.css
- src/components/modal/modal.jsx
- src/components/prompt/prompt.css
- src/components/prompt/prompt.jsx
- src/components/record-modal/playback-step.jsx
- src/components/record-modal/record-modal.css
- src/components/record-modal/record-modal.jsx
- src/containers/custom-procedures.jsx
- src/containers/modal.jsx
Fixes #2756 
Libraries and many other modals share the Modal Component.
Connected the Modal container to redux to make it aware of the RTL state, and then made sure that all places that use the modal component import the container, not the component directly.
* Current tests still run
Testing: [Add `/?locale=he` to the URL]
Mac
Windows
Chromebook
iPad
Android Tablet
> Handle RTL for the Modal Component

- webpack.config.js
Reverts LLK/scratch-gui#2809, fixes #2823. Temporary fix until we can do the same thing as #2809 ergonomically.
> Revert "build dist, even when run without NODE_ENV=production"

- package.json
- src/components/menu-bar/menu-bar.css
- src/components/menu-bar/menu-bar.jsx
- src/containers/deletion-restorer.jsx
- src/containers/target-pane.jsx
- src/reducers/gui.js
- src/reducers/restore-deletion.js
Towards implementing 'undelete' functionality from 2.0.
- Remove 'Redo' item in the 'Edit' menu
- Replace 'Undo' item in the 'Edit' menu with 'Restore' which restores the last deleted sprite. Restore is disabled in the menu by default, and becomes enabled after a sprite gets deleted. When the option becomes enabled, it reads 'Restore sprite'. Clicking on the option should add the last deleted sprite to the project and then disable the 'Restore' option again, changing the text of the option back to 'Restore'
- Restoring costumes, sounds, or blocks
- Removal of the confirmation dialog when deleting a sprite (this confirmation is linked to deleting all things: sprites, costumes, sounds, so it has not yet been removed)
Depends on LLK/scratch-vm#1438, and tests will fail until that PR is …
> Restore deleted sprite.

- src/components/gui/gui.jsx
- src/containers/preview-modal.jsx
This PR resolves #2814.
This PR adds a `hideIntro` prop that can be passed to the GUI element to hide the "Welcome to Scratch 3.0" modal. This does not hide the unsupported browser modal.
As stated in #2814, this change is needed so that the scratch-www project page can opt to not show the intro modal when switching from community to project view.
Tested by making sure the intro modal still shows up when no `hideIntro` prop is passed to it.
Mac
Windows
Chromebook
iPad
Android Tablet
> Add hideIntro prop to GUI component

- src/containers/custom-procedures.jsx
- Resolves #2810 
This is a temporary fix for the custom procedure modal in RTL. The RTL position calculations have a bunch of special cases because the initial placement of the block in RTL depends on the size of the block, but the position is always reported as 0,0.
Try it: https://chrisgarrity.github.io/scratch-gui/feature/2810-custom-proc-rtl/?locale=he
Mac
Windows
Chromebook
iPad
Android Tablet
> Positioning custom-procedure blocks in RTL

- src/components/action-menu/action-menu.jsx
Resolves a recent (unfiled) regression where the file upload buttons in the action menus (e.g. for adding a new sprite/costume/sound/backdrop). The regression was introduced by [this change](https://github.com/LLK/scratch-gui/commit/67f4496947c143efa3e24f6214b36bfc651f25e3#diff-905aba88028780ed582fc4571ca6444fR145) which was fixing a different RTL bug.
Since the `mainTooltpId` is now being used as part of the action menu items, make sure it is generated in the constructor of the action menu component instead of within the render method. This fixes a regression caused by a recent change where the file upload buttons in the action menu stopped working.
Manually tested the file upload buttons in the action menus to ensure they work again. Also tested RTL to ensure there wasn't a regression …
> Fix file upload regression

- src/components/menu-bar/menu-bar.jsx
Disable sprite restoration because of validation issues found in smoke test.
> Disable sprite restoration.

- src/components/menu-bar/menu-bar.css
added a line to manu-bar css so as to prevent brokenness in nav bar in Japanese and Chinese languages.
issue #2716 
- Resolves #
added a line `white-space: nowrap;` to menu-bar-item class in menu-bar.css.
To prevent brokenness in nav bar in Japanese or Chinese language.
I did not add any automatic test case and only did visual check manually because I fixed only one style sheet file.
Mac
Windows
Chromebook
iPad
Android Tablet
> fix for issue #2716 (brokenness in nav bar in にほんご language)

- src/containers/sprite-selector-item.jsx
Fixes #2697
Make the `Are you sure you want to delete this?` message translateable
It was always in English.
Mac
Windows
Chromebook
iPad
Android Tablet
> Make delete message translateable

- src/components/cards/card.css
- src/components/cards/cards.jsx
- src/containers/cards.jsx
- src/reducers/cards.js
- Resolves #2758 
Don’t initialize cards position in the reducer - initial position needs to be set based on `isRtl` at runtime.
Make `NextPrevButtons` function RTL aware so that it puts the prev/next on the left or right based on the direction of the language. 
Rename prev/next icons to right/left arrows (otherwise in rtl 'next' is using `prevIcon` and it becomes confusing)
If both `x` and `y` are zero, assume that it's the first time and initialize the position. Otherwise use the x and y passed in because the user must have dragged the tutorial cards to a new position. It does mean that the user can't drag the tutorial to `0, 0`, but that seems unlikely to happen.
Try it: …
> Handle RTL for cards

- src/components/coming-soon/coming-soon.css
- src/components/menu-bar/menu-bar.css
- src/components/menu-bar/menu-bar.jsx
Note: the coming soon tooltip positions are calculated by react-tooltip, and they do not handle RTL.
- Resolves #2757
* The menus open to the left of the menubar item
* Tooltips open on the opposite side - however the tooltip offset is calculated by the react-tooltip library and it is not RTL aware.
Try it: 
https://chrisgarrity.github.io/scratch-gui/feature/2757-menubar/?locale=he
> Handle RTL in menubar

- src/containers/backpack.jsx
- src/containers/gui.jsx
- src/lib/backpack-api.js
- src/lib/project-loader-hoc.jsx
- src/lib/storage.js
- Resolves #2197 
Adds props for project and asset hosts. Also, fix path and redux store references for the backpack (found while testing configuration of project, asset and backpack hosts).
This allows end-to-end local development and staging of the GUI embedded into scratch-www, since we need to be able to configure the project and asset storage to point at the local or staging project and asset servers.
We don't have the infrastructure in this repo to test this yet.
N/A
> Add project and asset host props

- src/components/menu-bar/menu-bar.jsx
This reverts commit 1c20d6db08b2dc844754c7b2a30bc7ead20ac188, reversing
changes made to 2f1cce93ad503be253fb25c789c8cb86deb0c941.
Re-enables restore sprite option in edit menu bar.
> Revert "Merge pull request #2845 from kchadha/disable-sprite-restore"

- src/components/browser-modal/browser-modal.css
- src/components/browser-modal/browser-modal.jsx
- src/components/gui/gui.jsx
- src/components/import-modal/import-modal.css
- src/components/import-modal/import-modal.jsx
- src/components/preview-modal/preview-modal.css
- src/components/preview-modal/preview-modal.jsx
- src/components/webgl-modal/webgl-modal.css
- src/components/webgl-modal/webgl-modal.jsx
- src/containers/error-boundary.jsx
- src/containers/import-modal.jsx
- src/containers/preview-modal.jsx
- src/containers/webgl-modal.jsx
- Resolves #2759 
Wraps the modal content in a `<div dir=...` and sets the direction based on the `isRtl` state. Handles all the modals that use `ReactModal` directly not the `Modal` component.
Try it:
https://chrisgarrity.github.io/scratch-gui/feature/2759-modals/?locale=he
Manual Testing:
Mac
Windows
Chromebook
iPad
Android Tablet
> Handle RTL in modals
