LLK/scratch-gui

.travis.yml
The order shouldn't matter, so try doing NPM deploy before anything else in case it's being disrupted by previous deploy steps (like prune)
=> Do gh-pages deploy and cleanup last

src/components/language-selector/language-selector.css, src/components/language-selector/language-selector.jsx, src/components/menu-bar/menu-bar.css, src/components/menu-bar/menu-bar.jsx, src/css/units.css, test/integration/localization.test.js
- Resolves #2658 
Initial update of language selection menu to avoid the menu within a menu. The language list is still a `select`, so the list of languages is styled by the browser being used. At some point we probably want to replace the `select` to have a consistent look for the languages across platforms. 
/cc @carljbowman 
Also removes the coming soon wrapper as it's no longer needed.
Try it:
https://chrisgarrity.github.io/scratch-gui/issue/2658-lang-select/
Updated language integration test to use the new menu.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Update language selection menu

src/components/menu-bar/menu-bar.jsx, src/containers/sound-tab.jsx
Restoring the last deleted sound (no issue filed).
Update the restore function state when deleting a sound. This should change the menu option in the Edit menu to read `Restore Sound`. Using the option should restore the sound that was last deleted.
- restoring a sound does not navigate back to the sound pane of the target whose sound was restored.
- restoring a sound adds it to the end of the sprite's sounds list (this is consistent with 2.0).
Manually tested. You can test here: https://llk.github.io/scratch-gui/restore-sound/
LLK/scratch-vm#1503
Mac
Windows
Chromebook
iPad
Android Tablet
=> Restore the last deleted sound.

src/components/menu-bar/menu-bar.jsx, src/containers/costume-tab.jsx
Restoring the last deleted costume (no issue filed).
Update the restore function state when deleting a costume. This should change the menu option in the Edit menu to read `Restore Costume`. Using the option should restore the costume that was last deleted.
- restoring a costume does not navigate back to the sound pane of the target whose sound was restored.
- restoring a costume adds it to the end of the sprite's sounds list (this is consistent with 2.0).
Manually tested. You can test here: https://llk.github.io/scratch-gui/restore-costume/
LLK/scratch-vm#1511
Mac
Windows
Chromebook
iPad
Android Tablet
=> Restore deleted costume

README.md, webpack.config.js
added build mode 'dist' to npm build options, so you can build the dist directory in development by doing 
```
BUILD_MODE=dist npm run build
```
When developing using scratch-www and scratch-gui together, there is currently no build option in scratch-gui that builds the dist directory without fully building all production assets. This option greatly speeds up the development build process in that case.
I don't think this is specifically testable using browsers or the testing suite.
=> added build mode 'dist' to npm build options

src/containers/controls.jsx, src/containers/error-boundary.jsx, src/lib/vm-listener-hoc.jsx
- Add correct empty MapDispatchToProps to components to prevent dispatch being passed as prop
- remove `on…` VM listeners from props passed to wrapped component.
All the warnings in console had been bugging me so I fixed them
- Fewer warning show up in the console
- Normal tests run
Mac
Windows
Chromebook
iPad
Android Tablet
=> Fix warnings

src/containers/sprite-selector-item.jsx, test/integration/sounds.test.js, test/integration/sprites.test.js, test/unit/containers/sprite-selector-item.test.jsx
Remove the confirmation dialog that pops up when attempting to delete a sprite, costume, or sound.
Now that the ability to restore the last deleted item has been added, this confirmation is no longer necessary.
Updated existing tests to remove the confirmation dialog checks.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Remove confirmation dialog when deleting a sprite, costume, or sound.

src/containers/sprite-selector-item.jsx, test/unit/containers/sprite-selector-item.test.jsx
Fixes https://github.com/LLK/scratch-gui/issues/2762
Inject fonts before setting SVG as image source on thumbnails
This allows thumbnails to render Scratch's fonts correctly
Mac
Windows
Chromebook
iPad
Android Tablet
=> Inject fonts thumbnails

src/containers/paint-editor-wrapper.jsx
- Resolves https://github.com/LLK/scratch-paint/issues/614
Pass rtl prop to paint so it can handle RTL layout
- color picker should have text to the right
=> Pass RTL state to paint editor

src/components/menu-bar/menu-bar.jsx
#2818 
Make Scratch logo a link to https://scratch.mit.edu
It should be a link.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Make Scratch logo a link

src/components/connection-modal/connection-modal.css, src/components/modal/modal.css
- Resolves #2982
Adds direction dependent margins to the connection modal. There should be padding between the microbit icon and the title in the titlebar, and there should be padding between the searching for signal spinner and the text.
Current tests run.
https://chrisgarrity.github.io/scratch-gui/issue/2982-extension-padding/?locale=he
Mac
Windows
Chromebook
iPad
Android Tablet
=> Fix connection modal padding for RTL

src/lib/project-loader-hoc.jsx, src/reducers/project-id.js
Just use `ProjectLoaderHOC` to translate props to redux. Trying to be clever about using both props and redux state together was... not clever.
Resolves #3040
=> Don't load the default project on top of everything

README.md, src/components/gui/gui.jsx, src/components/menu-bar/menu-bar.css, src/components/menu-bar/menu-bar.jsx, src/components/menu-bar/project-title-input.css, src/components/menu-bar/project-title-input.jsx, src/components/prompt/prompt.jsx, src/containers/gui.jsx, src/containers/project-loader.jsx, src/containers/project-saver.jsx, src/css/colors.css, src/lib/project-loader-hoc.jsx, src/lib/titled-hoc.jsx, src/playground/index.jsx, src/playground/player.jsx, src/playground/render-gui.jsx, src/reducers/gui.js, src/reducers/project-title.js, test/integration/blocks.test.js, test/integration/examples.test.js
Big help from pairing with @LiFaytheGoblin!!
relies on https://github.com/LLK/scratch-www/pull/2052 and should only be merged after it.
https://github.com/LLK/scratch-gui/issues/2815
Note: we haven't implemented the css changes per @carljbowman's comments on #2815.
Makes project title editable in GUI editor. 
Uses new project title reducer to store and change project title. This is made available to the menu bar, where the project title input uses it to maintain state, and to project saver, which uses the title to determine the downloaded filename.
When run within www, title changes made in the GUI menu bar are updated in www and through it to the server.
Testing:
For testing, we should try unusual unicode characters.
https://github.com/LLK/scratch-www/pull/2052 in scratch-www should be …
=> make project title editable, both in standalone and www modes

src/components/question/icon--enter.svg, src/components/question/question.css, src/components/question/question.jsx
Resolves #3010 
1. Change Unicode Emoji to SVG
2. Add a brief hack to CSS (changes may be needed here)
Unicode emoji does not work well on some browsers.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Use SVG for ask/wait prompt

src/components/menu-bar/menu-bar.css, src/components/menu-bar/menu-bar.jsx, src/components/menu-bar/project-title-input.css, src/components/menu-bar/project-title-input.jsx
#2641 
I did some changes to flex box and items to make the title field shrink
If the title field doesn't shrink the login box will lead to a scrolling condition on smaller screens. Very ugly.
MacOS Chrome + Safari, resized screens. Works down to 980px. Npm test passes.
=> Make title field shrink for smaller screens

src/components/question/question.css
- Resolves #2817 
Adds styles for RTL to put the submit button on the left and set the padding, margins and positions correctly.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Restyle the question answer box for RTL

package.json
Diff is https://github.com/LLK/scratch-paint/pull/682/files
=> Update paint to version that fixes crash when drawing transparent shapes in bitmap

src/lib/app-state-hoc.jsx, src/lib/libraries/decks/index.jsx, src/lib/tutorial-from-url.js, src/reducers/gui.js
- Resolves #3138
Allows loading a tutorial card from the url using a query parameter.
Needed for the HoC submission.
Manually tested  with a local build:
- Load a new query parameter by appending `?tutorial={number}` to the base url. Valid tutorial IDs are numbers 1-15 corresponding to the tutorials listed in the tutorial library in order. This should bypass the preview modal and open up the correct tutorial as if it had been manually added from the library.
- Attempt to load an invalid tutorial ID -- this should result in normal loading of the preview modal instead of a tutorial deck.
- Load a tutorial and project together. The tutorial query string comes before the hash e.g. appending `?tutorial=13#123456789` to the base url should load project 123456789 with the 'Switch Costume' …
=> [Smoke] Allow loading tutorial using query parameters in URL.

test/integration/project-loading.test.js
Increases the timeout in a test  "Load a project by ID directly through url', which as been flaky
Increases the timeout from 2 seconds to 3.5 seconds while the project loads.
The test keeps failing by timing out, but the project loads, so it shouldn't.  It doesn't always fail, so I'm increasing the timeout.
=> Increase timeout in integration test for loading project with url

src/containers/sprite-selector-item.jsx
This (mostly) fixes https://github.com/LLK/scratch-gui/issues/3173 (https://llk.github.io/scratch-gui/develop/#105500895 runs super slow)
decodeText takes a substantial amount of time (making each frame take ~200ms in the problem project). We were caching to prevent too many calls to svgRenderer.loadString. Now include decodeText in the caching too.
Additionally, sprite selector items don't need to rerender every frame. dragPayload is giving a different object every frame, even though every property of the objects match. For now, ignore dragPayload in shouldComponentUpdate. https://github.com/LLK/scratch-gui/issues/3172 is filed as a separate bug to clean this up later.
Performance fix
Play geometry dash until you can finish all the levels. Perseverance is key.
Test that dragging still …
=> fixRepeatDecode

src/components/language-selector/language-selector.jsx
I left the ability to ignore languages in place so that we can continue to have languages that are available, but not in the menu for everyone.
=> Remove ‘he’ from the languages to ignore

src/components/library/library.jsx, src/components/tag-button/tag-button.jsx, src/containers/tag-button.jsx, src/lib/libraries/backdrop-tags.js, src/lib/libraries/sound-tags.js, src/lib/libraries/sprite-tags.js, src/lib/libraries/tag-messages.js
- Resolves #2501 
* convert all tags to have a `tag` field corresponding to the query parameter, and `intlLabel` field that defines the title message for `FormattedMessage`
* define all the tag messages in a shared file so they can be included in multiple places.
* convert the `TagButton` to use `tag` for the `onclick` handler value, and localize `intlLabel` for the title.
In the library I’ve continued to use `tag.toLowercase()` even though all the tags are currently defined as lowercase. It’s safer, but currently not strictly needed.
Current tests run, once there are translations for the labels should check that Library tags are translated (e.g., Italian), and still …
=> Localize library tags

src/containers/language-selector.jsx
#3049 
Sets the lang attribute of the document in the GUI
Setting the correct language is crucial for screen readers so they use the correct pronounciation
MacOS, Chrome, not tested with a screen reader
=> Set lang attribute for screen readers

package.json, src/components/alerts/alert.css, src/components/alerts/alert.jsx, src/components/alerts/alerts.jsx, src/containers/alert.jsx, src/containers/alerts.jsx, src/lib/vm-listener-hoc.jsx, src/reducers/alerts.js
This is progress towards: https://github.com/LLK/scratch-gui/issues/2956.
- Displays stacks of alerts vertically.
- Shows an icon in an alert if one is provided.
To improve on previous alerts that displayed directly on top of each other, and to add further customizability with optional icons.
- Is a prerequisite for this PR in scratch-vm: https://github.com/LLK/scratch-vm/pull/1607.
=> Show multiple alerts in a stack and allow for custom alert icons.

src/index.js
For use from `scratch-desktop` and maybe other places.
The `scratch-desktop` repository can use this component to more easily host the "whole" editor.
The main question I have is: is this the right component to use? If not, is there another that would make more sense or should we make a new editor-wrapper component?
Since this is just exposing existing code at the module boundary, there's no new code to test.
=> Expose AppStateHOC component

src/components/menu-bar/menu-bar.jsx
/fyi @thisandagain 
Hide the "Give Feedback" button if there's session info (i.e., we are in scratch-www vs. beta)
This makes the rendering of the GUI in the preview project page look closer to the final design
Mac
Windows
Chromebook
iPad
Android Tablet
=> Don't show the "Give Feedback" button if there is a session

src/components/gui/gui.jsx, src/components/menu-bar/menu-bar.jsx
Adds an `onShare` prop to the top level GUI component
Use that `onShare` prop to control whether the "Share" button is "coming soon" or not.
We want the preview project page to have an enabled (but initially nonfunctional) share button
Mac
Windows
Chromebook
iPad
Android Tablet
=> Add onShare prop to enable the share button

src/components/stage-selector/stage-selector.css
#3009
Just adds one line of code. Background color white will stop before border, so the border color is set correctly. 
Tested on MacOS Chrome
=> Made border color of stage selector be same as other border colors

src/lib/hash-parser-hoc.jsx, test/integration/project-loading.test.js
#2981 
Pass property hideModal when projectId is given
npm tests don't pass :/
tested in MacOS, Chrome
=> welcome modal doesn't appear when a project is loaded directly

src/components/preview-modal/preview-modal.jsx
#3252 
Change preview modal to use defineMessages
~~To fix mistakes I did in past PR~~
To make preview modal tooltips translatable by translators
=> Use defineMessages

src/containers/paint-editor-wrapper.jsx
Fixes https://github.com/LLK/scratch-gui/issues/3235
Move getCostume() out of mapStateToProps. mapStateToProps is called any time the state changes, and getCostume can be very expensive because it has to decode from storage. In addition, I added a shouldComponentUpdate to ignore the props that don't affect rendering.
Projects could run very slowly when the paint editor was open
Tested [Space Giraffe](https://llk.github.io/scratch-gui/develop/#247578672) and [Geometry Dash](https://llk.github.io/scratch-gui/develop/#105500895)
Mac
Windows
Chromebook
iPad
Android Tablet
=> Fix expensive operation in mapStateToProps

src/components/direction-picker/direction-picker.jsx, src/components/forms/label.css, src/components/forms/label.jsx, src/components/sprite-info/sprite-info.css, src/components/sprite-info/sprite-info.jsx, src/components/sprite-selector/sprite-selector.jsx, src/components/stage-selector/stage-selector.css, src/containers/direction-picker.jsx, src/lib/locale-utils.js, src/lib/rtl-locales.js, src/reducers/locales.js
- Resolves #2429 
Move the labels above the inputs for languages that don’t fit in the width of the sprite-info pane.
Examples,
Abkhaz, Catalan, Greek...
renamed the `rtl-locales` lib file as `locale-utils` as  it’s doing more than rtl now. RTL should probably move into the scratch-l10n repo, but should the `wide-locales` setting? That seems like something that is gui specific. I don’t like having to hard code the specific languages that don’t fit, but there didn’t seem to be a better way to handle it right now.
I left aligned the labels as it seemed to look better most of the time. They are middle aligned horizontally - does that make sense? /cc @carljbowman 
The translations of the sprite-info labels in some languages end up being too wide for the fixed width of the sprite-info pane. …
=> Fix sprite-info pane for ‘wide’ languages

src/components/monitor/list-monitor-scroller.jsx, src/components/monitor/list-monitor.jsx
Fixes #3258
Translate "empty" and "length".
It's always in English!
Mac
Windows
Chromebook
iPad
Android Tablet
=> Translate 2 strings on list monitor

src/containers/monitor-list.jsx, src/lib/monitor-adapter.js, src/lib/opcode-labels.js
- Resolves https://github.com/LLK/scratch-vm/issues/1279
A complete rewrite of OpcodeLabels. Instead of a function, it’s a class that maintains a current translator function, and updates the opcode labelFn for each opcode when a new translator function is set. The new function `getLabel` provides the original functionality, to return the object with `category` and `labelFn` based on the opcode.
Wrap MonitorList with the `InjectIntl` HOC so that it has access to the intl object. Then pass `intl.formatMessage` as the translator function to `OpcodeLabels`.
Monitors on the stage don't update language correctly when switching language. It seemed worth figuring out how to update the language using the GUI (react-intl) framework instead of ScratchBlocks.ScratchMsgs. It uses the same strategy as …
=> Update monitor labels on the stage when language changes

src/containers/blocks.jsx, src/lib/blocks.js, test/integration/blocks.test.js
Resolves https://github.com/LLK/scratch-gui/issues/1368
(we can add "add sound..." as a follow-up maybe)
Depends on https://github.com/LLK/scratch-blocks/pull/1731
- When the contents of the sounds menu are generated, append a 'record...' option
- Add a callback triggered by this option to make it switch to the sounds tab and open the sound recorder. 
We'd like to make it more obvious that you can record your own sound, and make the process accessible directly from the play sound blocks themselves (as in Scratch 2.0).
Added an integration test
Mac
Windows
Chromebook
iPad
Android Tablet
=> Open sound recorder from sound block menu

package.json, src/lib/detect-locale.js, src/lib/tutorial-from-url.js, test/unit/util/detect-locale.test.js, test/unit/util/tutorial-from-url.test.js
- Resolves #3167
Import the `query-string` package (a popular and battle-tested option) to safely parse query strings.
The code relying on regexes and direct string manipulation of the query string is brittle and has bugs.
Added new unit tests.
Manual test plan:
- Tutorial:
- http://localhost:8601/?tutorial=sdf
- doesn't crash anymore
- http://localhost:8601/?tutorial=1
- opens the first tutorial
- Locale:
- http://localhost:8601/?locale=fr
- loads the french version
- http://localhost:8601/?locale=
- doesn't crash
Mac
Windows
Chromebook
iPad
Android Tablet
=> Robust URL handling for tutorial and locale

src/components/menu-bar/menu-bar.jsx
by putting in an empty default onShare function, I had inadvertently made the button appear enabled in beta/standalone.
=> disable onShare button

src/components/language-selector/language-selector.css, src/components/menu-bar/menu-bar.css
- Resolves ##3301 
* Adjust language icon and caret in menu-bar
* add slight margin on left and and right (works for both LTR and RTL languages)
* remove unused style from `language-selector.css`
Align language icon with Scratch logo and tutorials icon
Current tests run
Mac
Windows
Chromebook
iPad
Android Tablet
=> Fix language selector alignment

src/components/cards/cards.jsx, src/lib/libraries/decks/index.jsx
Resolves GH-2743
This PR migrates tutorial videos away from YouTube and towards a custom solution that we can put behind our CDN moving forward. All videos have been migrated to the new platform and in the case of the "Getting Started" tutorial an initial set of Closed Captions have been loaded.
/cc @SpeakkVisually @ntlrsk @kosiecki
=> Migrate Videos from YouTube

src/components/gui/gui.jsx, src/components/menu-bar/menu-bar.jsx, src/playground/render-gui.jsx, test/integration/menu-bar.test.js
Resolves https://github.com/LLK/scratch-gui/issues/3322 (and related to https://github.com/LLK/scratch-www/issues/2168 )
sets and uses several variables:
```
canCreateNew
canRemix
canReport
canSave
canSaveAsCopy
canShare
```
Question: are there any booleans we should add? Do all of these make sense?
We want embedding environments to be able to clearly communicate to GUI which capabilities the user should have, rather than have GUI contain knowledge about what various session statuses mean it should enable
Added several tests, in new test file `integration/menu-bar.test.js`
Mac Chrome
=> use can__ boolean properties to explicitly set user capabilities

src/components/gui/gui.css, src/components/gui/gui.jsx, src/components/watermark/watermark.css, src/components/watermark/watermark.jsx, src/containers/sprite-selector-item.jsx, src/containers/watermark.jsx, src/lib/get-costume-url.js, test/unit/containers/sprite-selector-item.test.jsx, test/unit/util/get-costume-url.test.js
Resolves #2826.
Adds a translucent sprite/stage watermark to the blocks workspace to indicated the selected target. @paulkaplan, thanks for your help on this!
Refactors code to get the costume source url out of sprite-selector-item so that it can be shared with the new watermark container.
Changes can be tested at https://llk.github.io/scratch-gui/watermark
[ ] Test that watermark appears on the workspace
[ ] Test that the watermark updates when a different sprite (or the stage) is selected
[ ] Test that watermark updates when new backdrops / costumes are added
[ ] Test layout in RTL
[ ] Test changing costume in paint editor and returning to workspace
- In scratch 2.0 the watermark does not update if the current costume of the selected sprite is dynamically changed (e.g. `next costume` …
=> Add sprite/stage watermark to the blocks workspace.

src/containers/blocks.jsx, src/containers/connection-modal.jsx, src/lib/vm-listener-hoc.jsx
- Helps resolve https://github.com/LLK/scratch-vm/issues/1638
Handle two different types of peripheral errors in the GUI:
- **request**: trigger connection modal error pane
- **disconnect**: trigger top-level GUI alert
PR to land in VM: https://github.com/LLK/scratch-vm/pull/1654
=> Differentiate peripheral errors: request vs. disconnect

src/components/gui/gui.jsx, src/components/menu-bar/menu-bar.jsx, src/containers/sb-file-uploader.jsx, test/unit/containers/sb-file-uploader.test.jsx
Resolves https://github.com/LLK/scratch-gui/issues/3339 and https://github.com/LLK/scratch-gui/issues/3140
* Handles/shows title of a 2.0 project (and will work for 1.0 projects, and projects missing extension, if it needs to) when one is loaded in 3.0.
* calls the onUpdateProjectTitle passed to it from `MenuBar` with the new title, if it exists. This allows code that encloses or embeds GUI to be notified of the title change when a file is uploaded.
* sb2 file uploads were having titles ignored, for no good reason!
* uploading a Scratch file when editor is under preview/project page should update the title of the project!
None. Unclear how to test this well?
tested in Mac Chrome
=> sb-file-uploader gets title of any sb.* file; calls onUpdateProjectTitle

src/components/cards/cards.jsx, src/containers/cards.jsx, src/lib/libraries/decks/index.jsx, src/lib/libraries/decks/translate-video.js, test/unit/util/translate-video.test.js
- Resolves #3230 
* Look up video id based on locale.
* add japanese video ids
* add test
Show different videos for the tutorials if they have been created for the other language.
Added unit test for the new function
Manual testing: only English and Japanese tutorial videos are currently available.
You can try it on my branch: https://chrisgarrity.github.io/scratch-gui/feature/3230-translate-videos/
Mac
Windows
Chromebook
iPad
Android Tablet
=> Add video translation

src/components/gui/gui.css, src/components/watermark/watermark.css, src/lib/get-costume-url.js
Fix minor issues with watermark:
- Font wasn't actually getting injected into costumes because cachedUrl was getting replaced. This is no longer broken:
- Fix issue where watermark could be dragged.
=> Get costume url bugfix

src/lib/vm-listener-hoc.jsx
- Resolves #3666: Prevent multiple peripheral alerts after language has been switched
Remove "peripheral disconnect" event listener when the component unmounts.
=> Resolves #3336: Prevent multiple peripheral alerts after language switch

src/components/loader/loader.css
- Resolves #3311
This pull request flips the direction of the loading blocks on right-to-left languages
This makes the blocks not look strange, and also look more like the real RTL blocks.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Fix block direction in loading animation for RTL

src/components/menu-bar/menu-bar.jsx, src/containers/gui.jsx, src/containers/sb-file-uploader.jsx, src/lib/project-fetcher-hoc.jsx, src/lib/project-saver-hoc.jsx, src/lib/vm-manager-hoc.jsx, src/reducers/project-state.js, test/unit/reducers/project-state-reducer.test.js, test/unit/util/project-saver-hoc.test.jsx, test/unit/util/vm-manager-hoc.test.jsx
Needs https://github.com/LLK/scratch-www/pull/2197 to work
Handles several states in which the user should be able to create a new project:
1. standalone player/beta: file->new just replaces current project data with default data
2. in www, logged in, viewing your project: file->new saves your project, replaces current project data with default data, then saves that data and gets a new id, then informs containing code of the change
3. in www, logged in, viewing someone else’s project:  file->new replaces current project data with default data, then saves that data and gets a new id, then informs containing code of the change
4. in www, not logged in, viewing whatever project:  file->new replaces current project data with default data, then informs containing code of the change
5. in www, …
=> handle many modes of new project creation

src/components/gui/gui.jsx, src/components/menu-bar/menu-bar.jsx, src/containers/gui.jsx, src/playground/render-gui.jsx
Resolves https://github.com/LLK/scratch-gui/issues/3444
introduce the showComingSoon prop on GUI, which indicates whether to show "coming soon" tooltips on grayed-out menu options (and header menu bar items); if false, we simply hide them.
In Beta, plenty of stuff is "coming soon". But embedded in www -- or, for that matter, in other players -- we are now able to use the user's session status and project ownership to determine what menu items we do and do not enable.
None
Mac
Windows
Chromebook
iPad
Android Tablet
=> added showComingSoon flag prop for gui

src/lib/make-toolbox-xml.js, test/integration/blocks.test.js
Resolves https://github.com/LLK/scratch-gui/issues/3108
Add a space at the end of the first default input to the `join` block, so that the result it reports is "apple banana".
This makes the default behavior of the block more similar to the one in 2.0.
=> Add a space after ‘apple’ in the join block

src/containers/gui.jsx, src/lib/project-fetcher-hoc.jsx, src/lib/project-saver-hoc.jsx, src/lib/vm-manager-hoc.jsx, src/reducers/project-state.js, test/unit/reducers/project-state-reducer.test.js
Resolves https://github.com/LLK/scratch-gui/issues/3435
Uses project-state error state and string instead of vm-manager's error state; adds handling to project-fetcher-hoc
single central project error display system
Already put error state test into project-state-reducer.test.js
Mac
Windows
Chromebook
iPad
Android Tablet
=> use project state error for project state related errors

src/components/library/library.jsx, src/containers/tips-library.jsx, src/lib/libraries/decks/index.jsx, src/lib/libraries/tag-messages.js, src/lib/libraries/tutorial-tags.js
- Resolves https://github.com/LLK/scratch-gui/issues/3334
This also resolves an issue where you couldn't search translated libraries, so we were avoiding them. But they now work!
Add tutorial tags and fix the bug with translated library item search by using intl.formatMessage to figure out what the translation is and match against that. 
/cc @thisandagain 
Note some of the filters arent translated in this gif only because it hasn't gone up for translations, and so some of the new ones are using english default.
=> Add tutorial filters and tags, and fix translated search in libraries

package.json
The recent change to update the version of babel requires a corresponding version of babel/cli to run the script that extracts translations. (The cli dependency was included in scratch-l10n, but now gui requires a different version, so it's better to just add the dependency here)
=> Add @babel/cli for generating translation strings

package.json, src/components/asset-panel/selector.jsx, src/components/sprite-selector/sprite-list.jsx, src/components/target-pane/target-pane.jsx, src/containers/costume-tab.jsx, src/containers/record-modal.jsx, src/containers/sprite-selector-item.jsx, src/containers/stage-selector.jsx, src/containers/watermark.jsx, src/lib/backpack/costume-payload.js, src/lib/backpack/sound-payload.js, src/lib/backpack/sprite-payload.js, src/lib/file-uploader.js, src/lib/get-costume-url.js, src/lib/storage.js
Depends on https://github.com/LLK/scratch-vm/pull/1691, and tests will fail until that is merged and this PR is updated with a new version of VM.
Towards LLK/scratch-vm#1577
Stop storing and accessing assets on storage, and begin using assets stored directly on VM costumes and sounds.  Also get rid of lingering uses of `storage.cache`, which won't do anything anymore, now that we don't access assets from the storage cache.
One caveat is that we will continue caching the default project json and assets onto storage.builtinHelper in order for that to keep working offline.
See LLK/scratch-storage#50
_Please show how you have added tests to cover your …
=> Use assets stored in the vm instead of storage

src/components/cards/card.css, src/components/cards/cards.jsx, src/components/cards/icon--close.svg
Adjusted the hierarchy of these icons. Close icon is now smaller and less prominent.
- Resolves https://github.com/LLK/scratch-gui/issues/3511#event-1925001958
**Current icon hierarchy:**
**Updated hierarchy:**
Close icon was too prominent. 
Mac
Windows
Chromebook
iPad
Android Tablet
=> Update tutorial and close icons

src/lib/libraries/decks/index.jsx, src/lib/tutorial-from-url.js, test/unit/util/tutorial-from-url.test.js
To make URLs more friendly, use e.g., `tutorial=getting-started` instead of `tutorial=1`.  This will also help with some URL handling we're doing for the new project page.
=> [Develop] Use names for tutorial URL ids

src/lib/libraries/decks/index.jsx, src/lib/tutorial-from-url.js, test/unit/util/tutorial-from-url.test.js
To make URLs more friendly, use e.g., `tutorial=getting-started` instead of `tutorial=1`.  This will also help with some URL handling we're doing for the new project page.
See #3520 for review
=> [Smoke] Use names for tutorial URL ids

.npmignore
The package is too large to publish to NPM. These aren't necessary for other packages using scratch-gui as a module.
(does same as https://github.com/LLK/scratch-gui/pull/3528 , but to smoke branch)
- Resolves GUI not being published to NPM since 2018-10-23
Excludes the test and build directories from the package published to NPM
We can't publish to NPM currently because the archive is too large.
N/A
N/A
=> Don't publish playground or test files to npm

src/lib/app-state-hoc.jsx
Since https://github.com/LLK/scratch-gui/pull/3431 GUI includes its own Intl provider (react-intl supports nested intl providers) that works within the www intl provider.
This PR restores the app-state-hoc intl provider for the stand-alone gui so that IE can function enough to put up the unsupported browser.
This will permit adding localization to things outside what's exported by GUI. We should be very careful about adding localization to any GUI wrapper component because it will work in playground (because of this PR), but possibly break in www.
=> Restore IntlProvider for Internet Explorer

src/containers/tips-library.jsx, src/lib/libraries/decks/index.jsx
First of all, let me make clear that @paulkaplan bears no responsibility, moral, ethical, technical or otherwise, for the contents of this PR.
Also, thanks to @paulkaplan for writing the elegant and powerful code in this PR.
The new "Animate an Adventure Game" tutorial requires assets from a starter project. We will generally direct people to it using a URL that includes both the tutorial ID and starter project ID. But, because you can also get to the tutorial by opening it from the library, we need a way to direct people to the starter project. 
After considering several options, we decided to do the following: when you click on this particular tutorial, if your browser is already at a URL containing the starter project ID, open the tutorial as usual; if not, open a new browser window …
=> Hack to load a starter project for a specific tutorial

src/containers/gui.jsx, src/lib/storage.js
This change adds a way for a consumer of `scratch-gui` to customize the `scratch-storage` instance that the GUI creates and shares with the VM and the rest of the system. If the `onStorageInit` property is not provided, the default value makes everything work as it did before.
This allows `scratch-desktop` to inject its own "Helper" to handle loading bundled assets through Electron.
The existing tests verify that this change doesn't break current behavior.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Add a hook for custom storage init

package.json, src/containers/gui.jsx, src/lib/cloud-provider.js, src/lib/vm-listener-hoc.jsx, src/lib/vm-manager-hoc.jsx
Adds a cloud data provider which creates and manages a web socket connection to the cloud data host provided by `www`. The connection is created upon successfully loading a project. 
This is a work in progress towards adding cloud variables to Scratch 3.0. 
This PR does not include:
- re-attempting a connection upon error
- logic around whether or not the current state indicates that a cloud data connection should be opened (e.g. user info, project info, etc.)
- remix logic
- ability to create new cloud variables in a 3.0 project
- LLK/scratch-vm#1703
- LLK/scratch-www#2245
Cloud variables!
Manually tested sending and receiving updates to a 2.0 project containing cloud variables when viewing that project from the 3.0 project page.
Mac …
=> Cloud Data Provider

src/components/record-modal/recording-step.jsx
Resolves #2798 
Translate recording step.
It contains hard-coded English strings.
I tested eslint manually via `npm run test:lint` and I got no error.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Translate record modal

src/components/language-selector/language-selector.css, src/components/loader/loader.css, src/components/loader/loader.jsx, src/components/menu-bar/menu-bar.css, src/components/menu/menu.css
Changes a few CSS things, including:
- Making the font-size properties more specific to the element, avoiding the giant menu item problem (a result of having a font-size set for all `ul li` in www)
- Forcing a box-sizing property when using explicit width + padding, since www does not have the same global preference for box sizing
- Do not rely on browser stylesheets for styling something that isn't really an "h1", and avoid the collision with h1 styling that comes from www
- Do not rely on browser stylesheet for styling `select`s, this is basically our fault in GUI for not acknowledging the fact that select components act differently in different OSs (i.e. actually have a background/color in non-mac OS)
Non of this requires overrides, just a bit of extra specification on selectors. 
This …
=> Fix CSS issues that appear when integrated with WWW

src/lib/project-saver-hoc.jsx, src/reducers/project-state.js, test/unit/util/project-saver-hoc.test.jsx
Resolves https://github.com/LLK/scratch-gui/issues/3197
For remix project creation and save as a copy project creation, we need to add params to the POST request. 
The first version of this PR did this by passing an object of params to the scratch-storage library, and letting it assemble the request url.
The current version of this PR doesn't pass the object of params. Instead, it adds these params directly to the outgoing request body.
This requires scratch-projects PR https://github.com/LLK/scratch-projects/pull/83 .
=> send params in storage request body, so that remixing and saving as copy create links to original projects

src/components/custom-procedures/custom-procedures.css, src/components/gui/gui.css
Fix by disabling overflow scrolling when a modal is open (this prevents the scrolling input issue) and reducing the top margin on custom procedures because it is a taller modal than most
- Resolves https://github.com/LLK/scratch-gui/issues/3419
=> Fix custom procedure scroll issue

src/components/target-pane/target-pane.jsx, src/containers/target-pane.jsx, test/integration/sprites.test.js
Looks like I forgot to actually pass this function to the sprite library. My integration test was erroneously passing :(  Made the test fail, then fixed the issue.
I forgot that the integration test needs to try clicking, because finding text will find invisible text as well
Fixes the issue reported by @picklesrus where you would not get switched back to the code tab after adding a sprite from the library
=> Pass onActivateBlocksTab to sprite library to switch tabs after adding.

src/containers/language-selector.jsx, src/containers/sprite-selector-item.jsx
- Resolves an issue where we were causing re-renders to happen on components that did not need to rerender
Each commit fixes a different problem. one for the backpack / any droppable area, and one for the language selector
After
=> Fix a couple areas where we are rendering too much

src/components/stage/stage.css, src/components/stage/stage.jsx, src/containers/target-highlight.jsx, src/containers/target-pane.jsx, src/reducers/targets.js
- Resolves https://github.com/LLK/scratch-render/issues/127
Adds a new `highlightedTargetId` and `highlightedTargetTime` to the targets reducer, emit events from the target pane (when selecting a sprite) and show the highlight frame overlayed on the stage
This also seems like a good place to use the react `key` property to make sure a new dom element is used any time the time changes, so that even if you click repeatedly on a sprite, a new fade-out animation will start.
=> Add sprite target highlighter on sprite-tile click

src/components/language-selector/language-selector.jsx, src/containers/language-selector.jsx
- Resolves #3302 
Blur the language select when the user clicks outside the select so that arrow keys go to the stage instead of the select.
Language-select was keeping keyboard focus for arrow keys when it shouldn't
Current tests run 
Mac
Windows
Chromebook
iPad
Android Tablet
=> Blur language select focus when mouse leaves

package.json
Fix uploading images as sprites.
This version is a custom build of VM, which has only this change applied to the currently deployed version https://github.com/LLK/scratch-vm/pull/1719
This version should _not_ be pulled into `develop` or `smoke`. Instead we should merge https://github.com/LLK/scratch-vm/pull/1719 and let VM publish a new version on `latest`, and update to that version on `develop`/`smoke`.
=> Update to VM hotfix version

src/containers/sprite-selector-item.jsx
Looks like https://github.com/LLK/scratch-gui/pull/3491 should have changed this old prop name, `assetId`, to `asset`
=> correct wrong assetId prop name

src/components/backpack/backpack.css
The blend-mode property was being set on the whole thing, rather than the image only
=> Fix dropdowns on backpack items being transparent

src/containers/target-pane.jsx
This gets rid of a React console warning introduced by https://github.com/LLK/scratch-gui/pull/3596 .
Note that the proptypes inheritance that was put in place in `containers/target-pane.jsx` two years ago -- where the container duplicates its presentation component's proptypes -- is very confusing to me. I suspect this approach makes mistakes inevitable, and it seems to me to already include a dozen or two unused proptypes declarations.
=> don't require onActivatedBlocksTab prop in TargetPane container

src/components/sprite-selector-item/sprite-selector-item.css
Fixes an issue @kathymakes saw where dragging sprite tiles by clicking on the image itself does not work well in firefox, because despite draggable=false on the image, it still drags :( boo firefox. 
@picklesrus I also think this could fix the angle picker on firefox problem
=> Add pointer-events:none to sprite img to prevent dragging.

src/components/language-selector/language-selector.jsx, src/containers/language-selector.jsx
Reverts LLK/scratch-gui#3583
Fixes #3613 
On firefox the mouse is considered to have "left" the select element as soon as it is no longer over the select menubar item. It doesn't treat the options as being part of the select. So this change completely breaks the language selector on Firefox.
Having the language selector keep keyboard focus if you don't select a language (you have to click twice outside the menu to reset focus) seems better than not working at all on Firefox. The permanent solution is https://github.com/LLK/scratch-gui/issues/3595
=> Revert "Blur language select focus when mouse leaves"

src/components/menu-bar/menu-bar.jsx, src/reducers/project-state.js
- Resolves #3615 
Instead of using `canCreateNew` to decide whether or not to save current project when you click `File->New`, use `canSave && canCreateNew`.
Saving the current project is bad (or trying) when you do not own the current project!
Not sure how to test this?
=> when user clickes File->New, only save if user can save

src/lib/cloud-provider.js, test/unit/util/cloud-provider.test.js
Fixes an issue where you cant set a cloud variable to zero, it shows up as undefined in 2.0 client. 
Added a unit test and covered the other case (not used) where you might be trying to update the index zero of a list.
On https://github.com/LLK/scratch-gui/issues/3647
=> Fix problem with updating cloud vars to zero.

package.json, src/lib/make-toolbox-xml.js
Resolves https://github.com/LLK/scratch-gui/issues/3656
Depends on https://github.com/LLK/scratch-vm/pull/1730
Use the target id on the volume reporter block.
This is necessary to correctly show the sprite-specific volume monitor.
=> Use target id in volume reporter block

src/components/backpack/backpack.css, src/components/backpack/backpack.jsx, src/containers/backpack.jsx, src/lib/backpack-api.js
Load more than just the first page of backpack items! A "show more" button will be shown, using the same heuristic from the comments page (if you have loaded a whole "page" of results, assume there is another page after to load.
There is also a change to the way deleted/inserted items are handled: instead of trying to reload the whole backpack after each modification, just make the single modification to the list we know is needed. This prevents those operations from interfering with the pagination.
=> Add basic "show more" pagination for the backpack

src/components/sprite-selector-item/sprite-selector-item.css
- Resolves #3024
Z-index of the x-sprite on thumbnail was changed from 1 to 'auto' as the parent elements had 'auto' z-index.
Thermometer menu, if open should cover the x for deleting a sprite on the selected sprite.
Chrome:
Firefox:
Windows
=> Fixes Close button overlap issue

src/components/menu-bar/menu-bar.jsx, src/components/menu/menu.jsx, src/containers/sb-file-uploader.jsx, src/containers/sb3-downloader.jsx, test/integration/menu-bar.test.js
- Resolves #3617 
* removes save and save copy from beta
* better menu section style handling, so that there is still a menu divider
A disabled Save and Save copy make it seem like you can't save, and make users not realize that upload and download are how to "save"
=> removed save and save copy from beta; better menu section style handling

src/components/menu-bar/login-dropdown.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/3601
Define login dropdown messages in gui's `login-dropdown.jsx` file, so they will be translated in the gui context; then, when www passes its login component to gui via the `renderLogin()` function, they will (hopefully!) translate.
Need readable login text, not weird id strings!
=> define login dropdown messages, so www component will render with readable text

src/containers/backpack.jsx, src/lib/backpack/block-to-image.js, src/lib/backpack/jpeg-thumbnail.js
Fixes the issue @thisandagain saw with safari not serializing blocks sometimes, caused by html entities not serializing properly. 
Also made errors in image loading propagate back through the promise chain so it doesn't get stuck on "loading"
=> Strip nbsp to fix serializing svg on safari

src/components/sprite-selector/sprite-list.jsx, src/containers/stage-selector.jsx, src/containers/target-pane.jsx, src/lib/backpack-api.js
Allow the sprite selector items and the stage selector to receive drops from BACKPACK_CODE type draggables. Respond to the drops by adding the code to the target.
I also refactored and commented more on the manual fetching required for sprite arraybuffers and code json. I'm sure we will eventually want to add these types to storage, but not now :)
=> Allow code to be dragged directly to sprite tiles

src/css/z-index.css
Fixes issue reported by @carljbowman 
> Blocks that being dragged appear below the Add buttons (e.g. Add Extensions) and monitors
=> Layer extension button and monitors below block drag surface

src/containers/blocks.jsx
Wait for `vm.shareBlocksToTarget` before refreshing the workspace, so do not request a workspace refresh until after the sharing is completed.
@kchadha this does not strictly depend on https://github.com/LLK/scratch-vm/pull/1727, but will be needed once that is merged.
=> Fix adding extension blocks from the backpack

package.json, src/lib/backpack/code-payload.js, test/unit/util/code-payload.test.js
Converting string to b64 via window.btoa fails on characters outside codepoints 0-255, include the "cloud" in cloud variable names
Added a unit test that failed using the previous `btoa` implementation.
=> Fix backpack crashing the GUI when trying to store a cloud variable

src/lib/opcode-labels.js
Fixes a regression introduced by #3320 where the monitor labels for the `(current [v year])` block wasn't displaying.
The sensing_current block has its field values in all caps. The changes in #3320 were no longer calling toLowerCase on them before matching on it.
The monitor label for that block (with all its various arguments) is currently broken.
Mac
Windows
Chromebook
iPad
Android Tablet
cc/ @paulkaplan, @picklesrus
=> Fix monitor labels for (current [v year]) block.

src/components/gui/gui.jsx, src/playground/render-gui.jsx
This is a small change, but needed so that the consumer of the GUI can provide `backpackVisible` in a more granular way without needing to create new objects.
Will require a www update, shortly
=> Split up the backpack visible and backpack host options

src/index.js, src/lib/app-state-hoc.jsx, src/lib/tutorial-from-url.js, src/reducers/gui.js, test/integration/tutorials-shortcut.test.js, test/unit/util/tutorial-from-url.test.js
- Resolves #3643
Adds `?tutorial=all` as a recognized option. Gui opens without the preview modal, and with the Tutorials Library open.
Back button in the Tutorials Library takes you to the Editor (not back to referrer).
The 2018 Hour of Code banner needs a link to all tutorials.
- added unit test for detecting 'all' as a valid tutorial id
- added integration test that checks for skipping the preview modal and having a tutorial available when the gui is loaded.
I'm having trouble with my chrome driver, so hopefully the tests run on travis.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Start Gui with Tutorials Library open

src/components/menu-bar/community-button.css, src/components/menu-bar/community-button.jsx, src/components/menu-bar/menu-bar.css, src/components/menu-bar/menu-bar.jsx, src/components/menu-bar/share-button.css, src/components/menu-bar/share-button.jsx, src/containers/project-watcher.jsx, src/lib/project-saver-hoc.jsx
This mostly resolves https://github.com/LLK/scratch-www/issues/2278
This change makes it so that:
* clicking the Share button triggers a save; once the save completes, user is navigated to the project page
* clicking the See Community button triggers a save; once the save completes, user is navigated to the project page
* navigating away from your project in any other way triggers a save (though this may not complete; it's unclear how effective this is); and
* Share and Community buttons are hidden while project fetching, project loading, and project creation happen (they are shown when the project is showing normally, or when saving)
The biggest outstanding problems are:
* navigating away can't be totally stopped until the save request is sent. So clicking "My Stuff" or the Scratch logo …
=> automatically save on navigating from page; hide share and community buttons while creating

src/containers/project-watcher.jsx
Gets rid of console error: `mapDispatchToProps() in Connect(ProjectWatcher) must return a plain object. Instead received undefined.`
...which was an unintentional side effect of https://github.com/LLK/scratch-gui/pull/3638
=> fixed mapDispatchToProps error

src/containers/target-highlight.jsx, test/integration/stage-size.test.js
@ericrosenbaum fixes the crashing problem you found. The problem was that the highlight component gets rerendered when you switch stage mode, but the highlightedTargetId may not still be available.
The real change here is just checking that the target still exists.
Adds an integration test also, using the simplest repo I could find:
1. Click a sprite
2. Delete that sprite
3. Click "Small stage mode"
/cc @BryceLTaylor I think we may want to hotfix this to master
=> Prevent crash after deleting sprite that had been highlighted

src/lib/libraries/sprite-tags.js, src/lib/libraries/tag-messages.js, test/integration/costumes.test.js, test/integration/sprites.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/3726
Add a "Letters" filter to the sprite/costume libraries (they use the same tagging systems). 
Added integration tests to use the "Letters" filter in the sprite/costumes libraries.
=> Filter for letters in the sprite/costumes libraries

package.json, src/components/monitor/monitor.jsx, src/containers/list-monitor.jsx, src/containers/monitor.jsx, src/lib/opcode-labels.js
- Resolves LLK/scratch-vm#1221
Add ability to save and load monitors in 3.0 projects.
Monitors retain position and mode, and in the case of list monitors, height and width across save and load.
Make extension monitors the right color, and make the extension color the default color for monitors when a color is not specified.
Manual testing.
Test instructions in LLK/scratch-vm#1686.
Testing branch: https://llk.github.io/scratch-gui/monitors/
This PR is dependent on LLK/scratch-vm#1686. The VM PR should be merged first.
Mac
Windows
Chromebook
iPad
Android Tablet
cc/ @picklesrus
=> Monitor save load

src/lib/backpack/costume-payload.js
Fixes an issue where the backpack thumbnails did not show with the correct fonts.
The solution is to use the `getCostumeUrl` utility, which takes care of inlining font-faces, which is exactly what is needed for this! Thanks @kchadha @fsih for making that utility!
=> Fix missing fonts in backpack thumbnails

src/containers/gui.jsx, src/index.js, src/lib/app-state-hoc.jsx
Prerequisite for https://github.com/LLK/scratch-www/issues/2281
Moved the tutorial id handling into gui so it works when gui is embedded in www as well as standalone.
This seemed better than duplicating the query handling in www, in order to pass an id to gui.
Note, the `?tutorial=all` handling remains in app-state-hoc. Currently it’s only needed in standalone mode for Hour of Code. It’s easy to move into the gui container if we do want it in gui by default.
Question: are there going to be interactions with project save/new... that will lead to ignoring the query string, or otherwise not the results that users expect.
Support opening with a tutorial loaded in www.
Current tests pass - it didn't change functionality, just where it was included so it's available in www.
Try it: …
=> Handle ?tutorial= query in gui

src/components/gui/gui.jsx, src/components/prompt/prompt.css, src/components/prompt/prompt.jsx, src/containers/blocks.jsx, src/containers/gui.jsx, src/containers/prompt.jsx, src/lib/cloud-manager-hoc.jsx, src/lib/cloud-provider.js, src/lib/vm-manager-hoc.jsx, test/unit/util/cloud-manager-hoc.test.jsx
Towards having fully functional cloud variables in 3.0.
Adds the ability to create cloud variables in a 3.0 project.
- adds a cloud variable option to the variable modal
- refactors cloud data connection logic into a separate HOC. 
- There is still more logic to come (not in this PR) about checking whether the user is a scratcher and about handling the cases where the user is viewing someone else's cloud project in editor mode.
- Adding a tooltip for why the cloud option becomes disabled (e.g. notifying the user about the cloud variable limit)
- Adding alerts/info bubbles about cloud variable usage when creating the first cloud variable in a project (like in 2.0)
Cloud variables!
Manual testing:
On a local scratch environment (api, scratchr2, www, projects, assets), create a new account …
=> Create cloud vars

src/components/library-item/library-item.css
- Resolves #3738: Add RTL layout to new extension library
LTR:
RTL:
=> Resolves #3738: Add RTL layout to new extension library.

src/components/alerts/alert.css, src/components/alerts/alert.jsx, src/components/close-button/close-button.css, src/lib/alerts/index.jsx, src/lib/project-saver-hoc.jsx, src/reducers/alerts.js, src/reducers/project-state.js, test/unit/reducers/project-state-reducer.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/3324
- Resolves https://github.com/LLK/scratch-gui/issues/3686
- Partially addresses designs in https://github.com/LLK/scratch-gui/issues/2956
* introduces `savingError` and `creatingError` alerts
* when errors are encountered in saving or creating, uses these alerts instead of causing the editor to crash with a blue-screen-of-death
* improves alert appearance, css alignment
Mac
Windows
Chromebook
iPad
Android Tablet
=> saving, creation errors use alerts; alerts css improvements

src/components/library-item/library-item.css, src/components/library-item/library-item.jsx
- Resolves #3790: Tutorials library displays incorrectly when "music" filter is selected
=> Fixing library item height stretch only for extensions.

src/lib/cloud-provider.js, test/unit/util/cloud-provider.test.js
Fix an issue where the cloud data server sends multiple newline separated commands that each look like JSON, rather than a single JSON-parseable object
/cc @colbygk @kchadha
=> Support multiple commands from cloud data server

src/containers/gui.jsx, src/lib/app-state-hoc.jsx, src/lib/hash-parser-hoc.jsx, src/playground/render-gui.jsx, src/reducers/gui.js, src/reducers/modals.js
The use of an "override" prop that allowed the preview modal to be hidden without actually changing the redux state was causing a problem where the block editors where not closing when modals were opening. That is because it relied on the modal reducer being accurate.
I defaulted the preview state to false to make it simpler to consume the GUI, as www will not want the preview info to be true. I made it true in the playground instead.
This fixes https://github.com/LLK/scratch-gui/issues/3710
I can't write an integration test for that specific issue yet because it only happens when embedded, but the current integration tests ensure that the preview modal is still there in the playground the way we want. I confirmed the fix for #3710 by manually linking and testing.
=> Remove the hideIntro override and default preview modal to false

src/css/z-index.css
- Resolves https://github.com/LLK/scratch-gui/issues/3828
Make alerts appear below modals and fullscreen view:
Alerts feel out of place when they appear above modals and fullscreen.
Mac
Windows
Chromebook
iPad
Android Tablet
=> moved z-index of alerts down around modal, loader levels

src/containers/gui.jsx, src/lib/app-state-hoc.jsx, src/lib/query-parser-hoc.jsx, src/lib/tutorial-from-url.js, src/reducers/gui.js, test/unit/util/tutorial-from-url.test.js
Refactors query string handling into an HOC
Consolidates all the special handling of tutorial query strings into one place.
Easier to understand and maintain.
Updated the unit tests to reflect the refactored tutorial URL handling. Also manually checked.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Move URL query string handling into an HOC

src/lib/cloud-provider.js, src/playground/render-gui.jsx, test/unit/util/cloud-provider.test.js
Uses randomized duration between [0, 2^k-1] where k is the connection attempt number, maxed out at 5.
I had to rework the tests quite a bit to make this easy to test, to work around the timeouts and the randomization.
=> Add exponential backoff for cloud provider.

src/lib/opcode-labels.js, test/unit/util/opcode-labels.test.js
Fixes an issue found in bug hunt on 11/16/18:
@ericrosenbaum notes:
> Monitor label for “day or week” has no spaces - it shows up as “dayofweek”
Change default message (and description) of day of week option for the sensing_current block. This fixes the monitor label in English. @chrisgarrity, I was wondering if this will end up showing up as a changed string on transifex and if that's desired?
Monitor label was not user friendly before.
Added unit tests for the monitor label, the capitalization issue fixed in a previous PR, and the fact that unknown opcodes get their category set as "extension" and their label set as their opcode.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Fix monitor label for day of week block.

src/lib/alerts/index.jsx, src/lib/project-saver-hoc.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/3836
* avoid false success alerts:
* throws an error if saving assets or project encounters an error (previously, error was being intercepted and not passed on)
* call to display success alert comes *after* we dispatch success action itself, not before
* do not try to create or save twice in a row (avoids infinite loop of retries)
None currently
Mac
Windows
Chromebook
iPad
Android Tablet
=> avoid create/save/error loops

src/lib/cloud-manager-hoc.jsx, src/lib/cloud-provider.js, test/unit/util/cloud-manager-hoc.test.jsx, test/unit/util/cloud-provider.test.js
Make cloud manager hoc cloud connection logic more robust. Namely, this fixes an issue where we were opening a cloud provider connection twice when creating a new project through /preview/editor.
Fix a bug where regular messages getting sent from the cloud server were resulting in an uncaught json parse error because `str.split('\n')` returns `['actual stuff', '']` if str ends in `'\n'`. Calling `JSON.parse` on `''` throws an error.
There were bugs.
Added tests for the things that were previously failing. Both of these tests should fail on develop.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Cloud bugfixes

src/lib/cloud-provider.js, test/unit/util/cloud-provider.test.js
Allows renaming and deleting cloud variables and for those changes to persist on the cloud.
Exists in 2.0.
Added unit tests. Manually tested.
LLK/scratch-vm#1775
Mac
Windows
Chromebook
iPad
Android Tablet
=> Add rename and delete functionality for cloud variables

src/components/alerts/alert.css, src/components/close-button/close-button.css, src/lib/alerts/index.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/3847
- Resolves https://github.com/LLK/scratch-gui/issues/3845
* restore close button formatting
* restore close button to error alerts
=> restored close button styling; make close button appear on alert errors

src/containers/backdrop-library.jsx, test/integration/backdrops.test.js, test/integration/costumes.test.js
Expand on the backdrop integration test to make sure this is documented/tested behavior
- Resolves https://github.com/LLK/scratch-gui/issues/3500
Do not activate the backdrop (costumes) tab after selecting a backdrop from the library
I've expanded on the existing backdrop integration test by pulling it out into its own file and adding a few new assertions. 
1. If the stage wasn't the editing target, it becomes the editing target ("selected"). That is, the code on the workspace is the code that belongs to the stage, ditto for sounds/costumes. This is existing behavior that I assume we want to maintain, but wasn't mentioned …
=> Do not change to backdrops tab after adding a backdrop.

src/lib/project-saver-hoc.jsx
- Resolves https://github.com/LLK/scratch-www/issues/2348
We were trying to autosave when GUI unmounts. But it unmounts every time the language is switched. So let's not autosave when GUI unmounts.
Was causing "Saving" alert forever...
Mac
Windows
Chromebook
iPad
Android Tablet
=> do not attempt to autosave on gui unmounting

src/components/action-menu/action-menu.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/3269
Automatically blur the action menu buttons when clicked to prevent it from blocking keyboard events from going to the VM and from reacting to future enter keys.
Tested by doing the following in develop vs. this branch
1. Load the editor
2. Add a "forever =>  if "a" key pressed => rotate"
3. Use it to make sure it is working
4. Open the sprite library
5. Add a new sprite
6. Without clicking anywhere else, try using the "a" key to rotate, it should work. It doesn't work on develop.
=> Stop action menu focus stealing keyboard events from the VM

src/components/stage/stage.jsx, src/containers/stage.jsx
Quick fix for following up from https://github.com/LLK/scratch-gui/pull/3882, which left the translucent frame over the stage always.
=> Hide entire frame unless the VM has not started

src/components/alerts/alert.css, src/components/alerts/alert.jsx
- Resolves #3753: Add RTL to alerts
cc: @benjiwheeler 
- Might need some further tweaking for loading spinner since its margins do not show up for me correctly (on localhost:8601)
=> Adding RTL padding to reconnect button on alerts.

src/lib/vm-listener-hoc.jsx
- Resolves https://github.com/LLK/scratch-www/issues/2210
Prevent default behavior of arrows/spacebar when those keys are used against the document body (i.e. without an input or element focused. If an element is focused, all those keys will still do the thing they are meant to do).
This is needed to make the project page work as expected. In the future, investing in ways of making those accessibility features work would be good (as mentioned by @towerofnix in https://github.com/LLK/scratch-www/issues/2210) But for now, it is broken for everyone because it both sends events to the VM _and_ scrolls the page.
_Please show how you have added tests to …
=> Prevent arrow/space from scrolling the page

src/containers/blocks.jsx, src/lib/project-fetcher-hoc.jsx, src/lib/project-saver-hoc.jsx, src/lib/vm-listener-hoc.jsx, src/lib/vm-manager-hoc.jsx, src/reducers/gui.js, src/reducers/project-changed.js
Listen to the new project changed event from the VM and keep track of the state in Redux.  Update it as appropriate.
Known issue is that the project is marked as "changed" immediately after it's loaded. This is due to asynchronous event emitting while the project data is loaded, and needs an update to the VM to fix.
/cc @benjiwheeler @kchadha
=> Track "project changed" state in Redux

src/components/alerts/alert.css, src/components/alerts/alert.jsx, src/components/alerts/alerts.jsx, src/containers/alert.jsx, src/lib/alerts/index.jsx, src/lib/project-saver-hoc.jsx, src/reducers/alerts.js
Add the download and retry buttons to the `saveError` alert
I do not like how the alert component is hyper specialized for two distinct use cases. It would be much better to refactor the alerts so that the alerter can just fill the alert with whatever they want. But I do not feel comfortable making that refactor because I know @benjiwheeler and @evhan55  have done most of the work in that area, so I don't think it would be good for me to do that refactoring right now.
To that end, I just followed the pattern and added `showDownload` and `showSaveNow` flags and added the required dispatchers for the actions.
=> Add download and retry saving to saving error alert.

package.json, src/lib/cloud-manager-hoc.jsx, src/lib/cloud-provider.js, test/unit/util/cloud-manager-hoc.test.jsx, test/unit/util/cloud-provider.test.js
- Connect to cloud if the project has cloud data instead of on every new project.
- Listens to a new event from scratch-vm indicating an update to the project's `hasCloudData` status.
- Remove `ack` handler in the cloud-provider since it is not used in the vm anymore.
- Queue messages to send in the cloud provider if the connection is not ready yet. This is needed since creating the first cloud variable triggers initiating the connection for the first time.
Reducing unnecessary cloud variable connections.
LLK/scratch-vm#1778
Added unit tests for projectHasCloudData prop in cloud-manager-hoc. 
Updated existing tests to account for refactors described above.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Connect to cloud based on hasCloudData

src/lib/data-uri-to-blob.js, src/lib/project-saver-hoc.jsx
This PR relies on https://github.com/LLK/scratch-www/pull/2365 for functionality, but will not break anything without it.
After saving a project, collect a snapshot of the renderer, blobify it and send it up to the onUpdateProjectThumbnail callback.
The structure of this is particularly defensive as to not block any of the project saving process or throw up errors when we do not want them to.
=> Send snapshots from the renderer to be saved as project thumbnails

src/containers/blocks.jsx
It was causing a bug where switching tabs and adding a sprite would make the workspace blocks not work. Needs investigation.
/cc @rschamp 
/ht @BryceLTaylor for finding this issue. We need to figure out how to write an integration test for this.
=> Remove setTimeout for reattaching workspace block listener.

package.json
We discussed doing this to avoid errors a while back. Seems worth doing now.
Delete existing translations before building new ones, to avoid errors.
Existing translations can sometimes cause errors. They're obsolete if we're building new translations, so let's delete them upfront.
None
n/a
=> delete existing translations before building translations, to avoid errors

src/reducers/project-state.js, test/unit/reducers/project-state-reducer.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/3659
project state reducer will now initiate a save before creating a copy
bring into line with spec!
added tests to project state. reducer test file
Mac
Windows
Chromebook
iPad
Android Tablet
=> save before saving as a copy

package.json, src/lib/cloud-provider.js
Limit sending cloud variable messages to the rate of 10 msgs/sec.
Limit getting bumped off by the cloud data server for sending messages too fast.
Manually tested and compared against scratch.ly
Mac
Windows
Chromebook
iPad
Android Tablet
=> Cloud Variable Rate Limit

src/playground/index.jsx
Resolves https://github.com/LLK/scratch-gui/issues/3919 by including a Promise.finally polyfill. I will also add that polyfill in www to fix it there as well.
Tested using Sauce to load Edge 15/16.
=> Include polyfill for promise.finally so Edge can load projects

src/components/gui/gui.jsx, src/components/stage-wrapper/stage-wrapper.jsx
- Resolves an issue where the ask/answer button was in the wrong place, because there was not a parent with dir="..." set. 
Add dir="..." to the stage wrapper.
Tested by embedding in www and using the ask block
Before
After
=> Fix stage wrapper not setting dir="ltr/rtl" property, buttons look wrong

src/lib/cloud-manager-hoc.jsx, test/unit/util/cloud-manager-hoc.test.jsx
Use new `hasCloudPermission` flag in determining `canUseCloud` this affects opening a connection to the cloud data server when viewing a cloud project and also whether or not the cloud variable option is visible in the variable modal.
Only users with cloud permissions should be able to interact with cloud data.
- LLK/scratch-www#2378
Added / updated unit tests. Manually tested along with LLK/scratch-www#2378.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Has cloud permission

src/lib/default-project/project-data.js
This will help with https://github.com/LLK/scratch-vm/issues/1635
Set the default project's videoState to 'on'
[Currently the default videoState in the VM is 'on',](https://github.com/LLK/scratch-vm/blob/develop/src/sprites/rendered-target.js#L154) which is helpful for making sure adding a video extension enables the camera by default. Setting the project default to 'on' in the GUI will make sure this default isn't overwritten for default SB3 projects. This change won't automatically turn on the video device, an extension will still need to be added for the video to turn on.
=> Update videoState to match default in rendered-target

src/containers/blocks.jsx
- Resolves #3251
Fix catching/logging of workspace update errors being caught from scratch-blocks.
Some existing projects were failing to load with a BSOD because of any error thrown from scratch-blocks which uses the `throw 'Some error string'` construct instead of `throw Error('some error string)'`.
An example project that was failing to load before but succeeds now is:
55574144
Tested with project mentioned above. It fails to load on develop but succeeds with these changes.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Fix error logging when workspace fails to update 

src/containers/blocks.jsx
Only show cloud variable option in variable modal, not list modal as well.
Variable and list modals after change:
Tested manually with local environment (need to have a Scratcher user).
Mac
Windows
Chromebook
iPad
Android Tablet
=> Do not show cloud variable option in list modal.

src/reducers/project-state.js
- Resolves https://github.com/LLK/scratch-gui/issues/3892
Changes `project-state`'s `SET_PROJECT_ID` action so that if in LoadingState.SHOWING_WITHOUT_ID, don't transition to default project
We were transitioning from state with uploaded project, where `projectId`=== `null` and `loadingState`===`SHOWING_WITHOUT_ID`, to setting `projectId` to default project. We shouldn't do that! 
Tests forthcoming...
Mac
Windows
Chromebook
iPad
Android Tablet
=> if in LoadingState.SHOWING_WITHOUT_ID, don't transition to default project

src/lib/vm-listener-hoc.jsx, test/unit/util/vm-listener-hoc.test.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/3968
Uses the publicly emitted PROJECT_START event from the VM to call a passed in onGreenFlag prop
Consumer of GUI wants to know when the green flag has been clicked, see https://github.com/LLK/scratch-www/issues/1858
Added a new unit test for the vm-listener-hoc just to test this!
Won't work until https://github.com/LLK/scratch-vm/pull/1825 is merged, but won't break without it.
=> Bind vm project_start event to passed in onGreenFlag prop

src/lib/project-saver-hoc.jsx, test/unit/util/project-saver-hoc.test.jsx
With https://github.com/LLK/scratch-www/pull/2408 , resolves https://github.com/LLK/scratch-www/issues/2328
calls `onRemixing()` prop function when starting to remix and stopping remixing
allows www project page to show remixing state
Added 2 tests for calling `onRemixing(true)` and `onRemixing(false)`
Mac
Windows
Chromebook
iPad
Android Tablet
=> handle the onRemixing prop from www

src/components/library-item/library-item.css, src/components/library-item/library-item.jsx, src/components/library/library.jsx, src/containers/tips-library.jsx, src/lib/libraries/decks/index.jsx
- Resolves #3957: Add EV3 and WeDo video tutorials that can load by URL only
http://localhost:8601/?tutorial=wedo
http://localhost:8601/?tutorial=ev3
=> Hidden tutorial library items for LEGO WeDo 2.0 and EV3

package.json
Part of resolving https://github.com/LLK/scratch-www/issues/1858
Use latest scratch-vm
scratch-vm has support for a callback `PROJECT_START`, which we need to count project views
=> update the scratch-vm we use in package.json

src/components/gui/gui.jsx, src/components/loader/loader.jsx, src/lib/alerts/index.jsx, src/lib/project-saver-hoc.jsx, src/reducers/project-state.js, test/unit/reducers/alerts-reducer.test.js, test/unit/util/project-saver-hoc.test.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/3545
- Resolves https://github.com/LLK/scratch-gui/issues/3846
* use blue creating screen for new projects
* new `getIsAnyCreatingNewState` function in `project-state` reducer lets us show this screen while in several states: fetching, loading, and creating (on the server)
* revised alert text for copy, remix
* saving messages don't dismiss alerts
since there is a project state, `SHOWING_WITHOUT_ID`, between loading the new project and creating it on the server, there is a flicker in the blue screen animation where it unmounts and remounts
* Clarify UX of creating stages
* don't abruptly dismiss alerts with menu bar saving messages
Should stuff like this be tested?
Mac
Windows …
=> use blue creating screen for new projects; revised alert text for copy/remix

src/lib/project-saver-hoc.jsx, test/integration/sounds.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/3684
project-saver-hoc now listens for window unload events, and before proceeding with browsing away from the page, checks if the project is dirty and prompts the user if it is.
Issue: since `projectChanged` is sometimes set to true when the vm is loaded -- a know issue, I believe -- this PR so far behaves wrong if you are looking at a project which you do not own; in that case, `projectChanged` seems to be always true, making it prompt you every time you navigate away from such a page, which is annoying.
Also, it's unclear to me whether I should delete the other window unload code in `playground/render-gui.jsx`. It seems to work fine with or without that code, possibly because it's being overridden by the listening in project-saver. …
=> warn user if they leave project that's not saved

src/components/alerts/inline-message.css
- Resolves https://github.com/LLK/scratch-gui/issues/3987
Use the correct font family declaration in the CSS, for platforms missing Helvetica Neue
=> Use the correct font fallbacks for navbar save messages

src/lib/vm-listener-hoc.jsx
We are emitting targets update because the event is disabled in player mode, but gets re-enabled and re-emitted when switching back. The API on that function was changed to allow events to be marked "not project changes"
- Resolves https://github.com/LLK/scratch-gui/issues/3967
Use the new flag in emitTargetsUpdate to prevent `projectChanged` state
=> Fix an issue where switching player to editor mode caused "Save Now".

src/components/menu-bar/menu-bar.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/3986
For some reason I didn't commit the part that wrapped this in `this.props.canSave`. Sorry @benjiwheeler
=> Only show the `SaveStatus` component for people who can save

src/components/custom-procedures/custom-procedures.css, src/components/prompt/prompt.css
/cc @kchadha 
Fixes https://github.com/LLK/scratch-gui/issues/3736, the issue where the variable modal checkboxes/radios have the wrong padding.
=> Force margin on inputs which is reset by normalizer in www

src/components/menu-bar/menu-bar.jsx
- Resolves an issue reported by @kathymakes that the scratch logo should not open a new tab, to try to keep from opening many instances of scratch (is that right @carljbowman?)
Make it navigate in the same tab.
=> Do not open a new tab when clicking scratch logo

package.json, test/integration/sprites.test.js
Pull in latest changes from scratch-vm including bugfix for #3608 and unskip integration test for that bug which was previously failing.
=> Unskip integration test for #3608.

src/lib/project-fetcher-hoc.jsx, src/reducers/project-state.js, test/integration/project-loading.test.js
- Partially addresses https://github.com/LLK/scratch-gui/issues/3411
when project state is some form of `showing`, and previous state was some form of `loading` or `creatingNew`, switch tab to code tab.
User should experience a clean slate with new or uploaded projects.
Added a test to project-loading-test.
Mac
Windows
Chromebook
iPad
Android Tablet
=> after loading project, switch to code tab

src/lib/project-fetcher-hoc.jsx, test/integration/project-loading.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/3363
Make the `null` response from storage throw so the error can be caught and the error screen shown
To make errors visible
Added an integration test for this where we try to load project id=999999999999999999 and watch it fail.
=> Show error screen when project cannot be loaded

src/lib/libraries/decks/index.jsx
Update the video to show in the WeDo tutorial. The resources team consolidated two videos into one, so we can display the same video on the [landing page](https://github.com/LLK/scratch-www/blob/develop/src/views/wedo2/wedo2.jsx#L57) and here in the GUI.
=> Update WeDo tutorial video

README.md
Resolves #4006
Makes the git url in the README consistent. Now they are both the https one.
To be consistent.
=> Make the git links in the README consistent

src/containers/stage.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/3207
Micromanage the browser default, so that we can still prevent preventDefault action for touch devices (stop scrolling the body), but we also want to get blurring the active element.
https://github.com/LLK/scratch-gui/issues/3207
Tested on desktop, safari, chrome, android and ios tablets.
=> Make mousedown on the stage blur inputs, with @picklesrus

src/components/menu-bar/menu-bar.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/3995
Show the title editing field only if you can save the project in general.
Admins were seeing title editing field, which they really don't want to see for miscellaneous projects.
Better to see info on the author.
None -- I started to make a `unit/components/menu-bar.test.jsx`, but gave up. I guess there's a reason there's no menu bar unit tests...
To test manually, view a project you don't own in editor as an admin. You should see the author info. View a project as its owner. You should see the editable title. View a project by someone else, as a regular user. You should see the author field.
=> admins will see author credits, not title editing field, in editor

src/components/menu-bar/menu-bar.jsx
Fixes #3742.
Only displays this particular `<MenuSection>` if it has the conditions to present at least one item.
This visually makes there only be one separator between "New" and "Load your computer" when there is no content in the `<MenuSection>` between them.
No new unit tests. I couldn't see a very significant visual difference here myself, but I noticed that the empty `<MenuSection>` element was no longer present when I viewed the React devtools console.
To make sure it works in the case that those conditions *are* true, I used the React devtools to enable various combinations of the relevant properties on `<MenuBar>`, and the section did show as expected.
=> Fix empty <MenuSection>

src/components/alerts/alert.css, src/components/alerts/alert.jsx, src/components/alerts/alerts.css, src/components/alerts/alerts.jsx, src/components/alerts/inline-message.jsx, src/components/gui/gui.css, src/components/spinner/spinner.css, src/components/spinner/spinner.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/3686 and ttps://github.com/LLK/scratch-gui/issues/3941
Various changes to alert styling:
* font size bigger
* better, bigger padding within alerts
* alert width adjusts naturally from 200px to 448px as content demands
* text aligned to left, not center; everything aligns to vertical middle
* spinner color from white to green
=> revised alerts and spinner styling

src/components/cards/cards.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/2154
Make the card dynamically lay out so that it doesn't ever lay out off the bottom of the screen.
We previously used a fixed height, but now that we are using the tutorials more, it seems to fall off the bottom of the screen for many, many people.
Tested on various screen sizes.
/cc @ericrosenbaum @thisandagain
=> Try to always keep the tutorial in view despite screen height

src/components/backpack/backpack.css, src/components/sprite-selector/sprite-selector.css
- Resolves https://github.com/LLK/scratch-gui/issues/3073
Give a max-width to sprite/backpack tiles to prevent long name issues like the one in #3073
=> Give max-width to sprite tiles to prevent long names issue

src/components/menu-bar/menu-bar.jsx, src/containers/sb-file-uploader.jsx
close file menu on uploading sb file; don't close file menu twice.
- Resolves https://github.com/LLK/scratch-gui/issues/1771
=> close file menu on uploading sb file; don't close file menu twice

src/containers/sprite-library.jsx, src/containers/target-pane.jsx, src/lib/file-uploader.js, src/lib/randomize-sprite-position.js
Resolves #2072
Randomize sprite positions when added from image file or from library (through 'choose from library' and 'surprise'). 
Should not randomize positions of sprites that are added from an actual .sprite2 or .sprite3 file. 
Manually tested. Also wrote integration tests that I did not end up checking in because they can fail sometimes...
Mac
Windows
Chromebook
iPad
Android Tablet
=> Randomize Sprite Positions

src/lib/app-state-hoc.jsx
- Resolves an issue @cwillisf found that you could not pass showPreviewInfo={false} to the app state hoc to prevent the preview info from being shown. 
This does not effect www, which does not use the app-state-hoc. 
@cwillisf no tutorial ID changes were required, because the default redux state is false for preview info, and the new stuff in query-parser-hoc just makes sure that if there is a tutorial in the url that the preview gets closed, which we always want.
Will eventually rip out all preview-info related code.
=> Actually use the showPreviewInfo prop to show the preview modal

src/components/menu-bar/menu-bar.jsx, test/integration/project-loading.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/3744
don't warn user with a confirm about leaving project, if user could choose to save the project, or project will autosave, or project is already saved.
Prompt was sometimes unnecessary and confusing.
none.
Mac
Windows
Chromebook
iPad
Android Tablet
=> only prompt user to save if project has changed and won’t autosave

src/lib/storage.js, test/integration/examples.test.js
This should have happened a while ago, but the Fastly config needed to be updated. It's updated now.
- Needed for https://github.com/LLK/scratch-projects/issues/102
Update storage to use the 3.0 GET route, rather than legacy
This route is simpler, and we can discern whether someone is requesting for 3.0 or 2.0 with this change.
They have been amended to support this change
N/A
=> Use 3.0 routes for GETs

src/lib/project-saver-hoc.jsx
Helps to address https://github.com/LLK/scratch-www/issues/2484 by getting project thumbnail immediately upon project creation
Also see https://github.com/LLK/scratch-www/issues/2484 
Asks the vm renderer to `draw()` when requesting project thumbnail, so it is done immediately
This will make it not wait until the user has hit the green flag to produce a thumbnail image and send it to the server
none
**NOTE:** since we cannot produce thumbnails locally, we will have to carefully check after deploy to staging to ensure that this works and doesn't break anything
Mac
Windows
Chromebook
iPad
Android Tablet
=> render vm when requesting project thumbnail, so it is set immediately

src/containers/costume-library.jsx, src/containers/costume-tab.jsx
With https://github.com/LLK/scratch-vm/pull/1849, fixes https://github.com/LLK/scratch-vm/issues/1773
https://github.com/LLK/scratch-vm/pull/1849 should go in first.
Load costumes from library as if they are from scratch 2
Some library sprites need the fixes that are only applied to scratch 2 svgs
To test, load abby sprite and abby-d costume, and make sure that abby-d looks the same on the stage whether you upload as sprite or as costume.
How it should NOT look
All costumes that appear cut-off in the costume library should appear whole when shown on stage. For instance, shark 2 c.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Call add costume from library to fix bounding box issues with some library sprites

src/containers/sb-file-uploader.jsx, src/lib/vm-manager-hoc.jsx, src/reducers/project-state.js, test/unit/reducers/project-state-reducer.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/4120
* adds several states to `project-state` reducer to handle file upload
* introduces ability to indicate that a project load failed, and then to return to normal state with currently showing project; we should discuss this
* refactors `sb-file-uploader` so that it syncs with `project-state` state machine
Note that the titles still aren't set right; we could add that here or do it as a follow on. But, at least now the old project's title isn't overwritten.
Basic functionality: uploading a project saves current project first
The original project is indeed saved correctly:
Uploading a second project file, with no page reload (so keeping the same `FileReader` object), works correctly:
trying to upload an invalid file fails without …
=> When user uploads project file, project will auto-save before loading

src/containers/stage.jsx
Resolves #1317.
Avoids an error that gets thrown on some specific cases of Firefox (mainly non-Windows, as far as I can tell).
Helps keep the console clean. Also means the code past this `if` block can always run on any click (not just left).
Linux Firefox and Chromium.
=> Fix "TouchEvent is not defined" error

src/lib/libraries/costumes.json, src/lib/libraries/sounds.json, src/lib/libraries/sprites.json
Various regression fixes to the sprite and costume libraries:
- Banana: update costume
- Devin: use vector version 
- Dot: fix tags
- Dragonfly: fix tags
- Frog: fix tags
- Hare: update costume
- Penguin: fix tags
- Polar bear: fix tags
- Zebra: re-added
=> Sprite and costume library fixes

src/components/crash-message/crash-message.jsx, src/containers/error-boundary.jsx
/cc @rschamp @colbygk this does two things:
1. Show the relevant error ID to the user if Raven is available.
2. Report react errors to raven in the error boundary.
I will need to add this to the error boundary in www as well.
=> Show error ID if available from Raven and report react errors

src/lib/vm-manager-hoc.jsx
They were not being marked as clean when loaded from the server, causing remixes that included only minimal (or no) changes to take a very long time as it waited for hundreds of network requests to resolve. Mark them as clean when loaded from the server so we know they do not need to be resaved.
Discussed this with @rschamp , but @benjiwheeler it would be great to get some eyes on testing this locally with some larger projects. I tested remixing and saving, modifying costumes and resaving and seeing only a single asset trying to get saved. 
/cc @rschamp
=> Make remixing/saving faster by marking all assets as clean to start.

src/lib/font-loader-hoc.jsx, src/lib/vm-manager-hoc.jsx, src/reducers/fonts-loaded.js, src/reducers/gui.js, src/reducers/project-state.js
- Resolves https://github.com/LLK/scratch-gui/issues/4159
instead of maintaining the state of font loading in the `font-loader-hoc`, put it into redux.
We need font loading state to be shared across project page and editor, so that fonts are not loaded a second time.
The second font load was triggering a second vm load of the project data.
none... not obvious what we would test
Mac
Windows
Chromebook
iPad
Android Tablet
=> refactored font loading state to be in redux

src/containers/error-boundary.jsx, src/lib/analytics.js
/cc @colbygk @rschamp 
Use the new Sentry API using the `window.Sentry` object provided by www. This is a bit of a hack until www builds gui and they can share the same Sentry object.
Also consume the GA_ID provided to the window by www
=> Use new sentry API provided by www, and use analytics ID from www

src/containers/blocks.jsx, src/containers/error-boundary.jsx, src/containers/paint-editor-wrapper.jsx, src/containers/sound-editor.jsx, src/lib/project-fetcher-hoc.jsx, src/reducers/modals.js
/cc @thisandagain @rschamp 
Removes all the `pageview` analytics calls except the search query one for the libraries, and removes the error logging to GA. 
There are still a fair number of individual events I we need to look at to decide whether they should be kept or not
=> Reduce analytics events

src/containers/modal.jsx, test/helpers/selenium-helper.js, test/integration/sprites.test.js
- Resolves https://github.com/LLK/scratch-www/issues/2129
Currently, on modal mount, we adjust the `window.history`. If `history.state === null`, we push a new history entry; if it's not null, we just replace history.
The problem with this is that if we've already navigated within the single page application, say from the project page to editor, then `history.state` is not null; so we just replace history when the library modal is open. Then if the user hits the back button, the browser navigates back to the previous `history` entry -- in this case, the project page.
This change instead checks `history.state === null || history.state !== this.id`, which is more permissive; if the `history.state` entry exists but is not the same as the current view, we push, instead of replacing.
Browsing …
=> On modal mount, push history if current history state doesn't match this modal's id

package.json, src/components/monitor/monitor.jsx, src/containers/monitor.jsx, src/lib/download-text.js, src/lib/import-csv.js, src/lib/variable-utils.js
- Resolves https://github.com/LLK/scratch-gui/issues/2054
This PR implements the import and export context menu items for lists with the same functionality as 2.0
- import csv, allow user to choose the column if there is more than one (bonus, tsv, since the parser module autodetects delimiter)
- export txt file, newline delimited (include both kinds of line endings for windows users)
There are some regression tests covering the context menu for the other variable types, so i'm confident this doesn't introduce regressions, but it is hard to make selenium test for this, I'll give it a try.
I know this is additional functionality so close to launch, so I'd be fine holding this if @kchadha you …
=> Implement list import and export from files

package.json
Closes #4173
updates to the newer version of scratch-l10n
=> chore(package): update scratch-l10n to version 3.1.20181220222259

src/components/gui/gui.jsx, src/components/loader/loader.css, src/components/stage-wrapper/stage-wrapper.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/2134
Use the loading animation in player mode as well as editor mode.
The lack of loading animation makes the project page view feel like it isn't working.
Here is what it currently looks like
With this change it looks like this
I simply passed in the loading prop to the stage wrapper so that it can be shown in player only mode.
I also changed the CSS for the loading animation so that it is position absolute instead of fixed, so that it can be contained within the stage size in player mode (but is still full screen in editor mode, which I made sure to test)
/cc @thisandagain @rschamp  I made this …
=> Use the loading screen in player mode

src/components/webgl-modal/webgl-modal.jsx
Resolves #4201 
Changes the link from wikipedia to WebGL official website
It's not user-friendly
=> Change WebGL link

package.json
/cc @rschamp, pinned to the most recent working version (this version has been published for several months)
=> Pin eslint-plugin-react because v7.12 has a bug causing erroneous fails

src/lib/font-loader-hoc.jsx
A problem where the Avast SafePrice chrome extension caused all projects not to load.  We were iterating over all fonts in the document and waiting for them to load, which meant we were waiting for the extension fonts to load. They were not loading properly (there was a network error), so the project never loaded either.
Only load fonts from the list in the scratch-render-fonts repo.
=> Stop waiting for non scratch fonts to load.

src/components/browser-modal/browser-modal.jsx, src/lib/supported-browser.js
- Resolves #2370 
Remove the case of Vivaldi in the blocking browsers logic
Because there is no reason to block Vivaldi, as it's always based on a recent version of Chromium, and Scratch supports Chromium.
No test coverage but the change is trivial.
=> Remove Vivaldi block

src/components/backpack/backpack.css, src/components/blocks/blocks.css, src/components/sprite-selector/sprite-list.jsx, src/components/sprite-selector/sprite-selector.css, src/components/sprite-selector/sprite-selector.jsx, src/components/stage-selector/stage-selector.css, src/css/colors.css
Fixes usability issue where the drop area was too small, and you couldn't see it.
- Resolves #4254 
Highlight the drop area, and fix its size.
Move the highlight color to a css variable.
As a follow up, we could include this highlight on the costumes/sounds list when dragging out of the backpack, but so far people have not complained about that and would be a higher risk change.
=> Make the sprite drop area from the backpack highlight and large

src/components/sound-editor/sound-editor.css
On Mac Safari, sound editor undo/redo buttons render incorrectly, resolves #3778 
Sets margin to 0px for undo/redo buttons. For some reason, Safari gives a default margin of 2px for these buttons, so this change fixes that.
None
Mac
=> Fix sound editor button spacing

src/lib/project-saver-hoc.jsx
Resolves an issue where projects are getting saved in a state where they reference an asset that hasn't been stored on the asset server.
Serialize the project state before attempting to store assets. The project isn't stored until all assets were successfully stored, but this ensures that updates being made to the assets during the auto-save project don't result in a project getting saved that references an asset that isn't on the server yet.
On production, updating a costume (constantly) in the middle of an auto save can result in a BSOD after reloading the project (the project got stored on the project server in a broken state).
This should no longer happen.
Thanks to @paulkaplan, @picklesrus and @thisandagain.
=> Save project state before storing assets instead of after.

src/components/browser-modal/browser-modal.jsx, src/lib/supported-browser.js
Many people who were seeing crashes on the site were using very old versions of browsers that we support
In addition to excluding certain browsers, it checks the browser version to ensure that it meets the minimum specified in the FAQ.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Check for minimum versions of recommended browsers

package.json
Reverts LLK/scratch-gui#4289
On the older chromebooks this caused the sonic project level to be completely blank.
=> Revert "Update scratch-render to the latest version 🚀"

src/containers/blocks.jsx
Fixes the `Cannot read property 'getWorkspace' of null` errors in the console. I was starting to write up an issue documenting why it was happening, and instead convinced myself that it would be better to fix it in blocks than elsewhere.
Check for a non-null flyout in addition to an editing target before trying to update toolbox values.
The `onTargetsUpdate` is actually a 'debounced' method that runs every 100 milliseconds to ensure that blocks in the toolbox get updated values when necessary (e.g. goto). If a project with two sprites is running (e.g. forever, turn 15 degrees on one sprite), and you switch sprites, and immediately click `see project page`, the debounced method runs after the project page has removed the toolbox. …
=> check for non-null flyout

src/containers/gui.jsx, src/reducers/project-state.js
- Resolves https://github.com/LLK/scratch-www/issues/2628
Adds `getIsLoaded` to the project state reducer, and uses that method to set `isProjectLoaded` in GUI. Calls the `onProjectLoaded` callback when the state becomes true.
www needs to know when a project finishes loading so that remixing can be disabled while the project is in a state that cannot be remixed.
- Should have no impact on standalone gui (tests should run)
Mac
Windows
Chromebook
iPad
Android Tablet
=> add support for onProjectLoaded

src/containers/gui.jsx, src/lib/project-fetcher-hoc.jsx, src/reducers/project-state.js
Follow up to resolving https://github.com/LLK/scratch-www/issues/2628
https://github.com/LLK/scratch-gui/pull/4312 had a function name conflict with the existing code. This change fixes that by renaming the conflicting function, and removes redundant code.
=> resolve name conflict by renaming onProjectLoaded in project-fetcher-hoc

src/components/stage/stage.css, src/components/stage/stage.jsx, src/containers/green-flag-overlay.jsx
Resolves #4229 (can't click anywhere on the stage to start the project after it loads).
Move the onClick handler to the overlay wrapper so that the whole stage is clickable to start the project instead of just the green flag button
User requests
manual testing
Mac
Windows
Chromebook
iPad
Android Tablet
=> Make whole stage clickable for green flag overlay

src/components/gui/gui.jsx, src/components/loader/loader.css, src/components/loader/loader.jsx, src/components/stage-wrapper/stage-wrapper.jsx, src/containers/gui.jsx
Allow the loader component to display over the whole screen when in fullscreen mode. 
Also /cc @chrisgarrity this incidentally fixes an issue where the "ask" bubble went the wrong direction in RTL, which was caused by a mismatch between props passed in editor vs. player mode to the same StageWrapper component we were working on.
=> Show loading screen in fullscreen mode

src/lib/backpack/sound-payload.js
Allow putting mp3 sounds in the backpack. We were previously ignoring them completely.
MP3 Sounds exist.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Allow putting mp3 sounds in the backpack.

webpack.config.js
Fixes an issue where the vms vernier dependency was not being built for es5 the way that www is expecting.
Use our babel presets to transpile it. 
/cc @ericrosenbaum
=> Build vernier module using babel preset to make sure it works for www

src/containers/sound-editor.jsx
There was a useability issue discovered in testing where trying to trim a sound to be of zero length would fail, but just leave the trimmers active. Clear them out, since the trim is invalid.
Repro by trying to trim a sound down to a single sample then keep trimming. The "save" button now always clears the trim handles.
/cc @ericrosenbaum
=> Clear trim handles if trim cannot be completed.

src/components/context-menu/context-menu.css, src/components/context-menu/context-menu.jsx, src/components/sprite-selector-item/sprite-selector-item.jsx
Resolves #4345 
* Adds BorderedMenuItem, which has a border at the top and becomes red when hovered
* Use it for Delete menu (also reorder it)
Some people accidentally delete sprites because there was no difference between this and the others
* Lint passed
* Checked on browser
Mac
Windows
Chromebook
iPad
Android Tablet
=> Adds BorderedMenuItem and use it for delete menu

src/containers/costume-tab.jsx, src/containers/sound-tab.jsx, src/containers/target-pane.jsx, src/lib/sortable-hoc.jsx
Fixes an issue where you could not drop a sprite from the backpack if there were no sprites in the list. Same applied for sounds if there were no sounds.
This is used because the sortable drop is also used for general dropping as well as sorting drop, so you need to be able to drop into a sortable list that does not contain any items.
Make the corresponding reorder code be more careful to check if there is a newIndex.
- Resolves https://github.com/LLK/scratch-gui/issues/4350
=> Fix issue where you couldn't add sprites from backpack when there are no sprites 

src/components/asset-panel/selector.css, src/components/backpack/backpack.css, src/components/sprite-selector-item/sprite-selector-item.css, src/components/sprite-selector-item/sprite-selector-item.jsx, test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
This PR introduces a couple of layout/css tricks in order to vastly improve the layout+paint+composition performance of the editor while a typical projects is running. The main improvement is to apply the same layout trick that is used in the sprite library to allow the sprite selector images to change frequently without causing a layout of the target pane as a whole. That makes it so much less layout/painting has to happen:
This improves the composition time by almost a half on both low-power machines (chromebook composition time goes from 20ms to 10ms) and high-power machines (my laptop goes from 5ms to 2.5ms).
I see an almost 50% improvement in frame times on the low-power chromebook using the "Birds" project (id=198711193) which was chosen from the front page.
Prior to this change, …
=> Improve layout/paint performance in editor while running a project

src/components/sprite-selector-item/sprite-selector-item.jsx, test/integration/sprites.test.js, test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
This fixes a bug I introduced in https://github.com/LLK/scratch-gui/pull/4362, by putting an absolutely positioned image above the "close" button that deletes sprites. 
I fixed the issue and added an integration test. Previous integration tests only tested the right-click -> delete sprite for some reason.
=> Fix delete button on sprite tiles

src/components/backpack/backpack.css
The layout perf fixed introduced an issue where the backpack items could squash instead of scrolling, because we removed the min-width, and width is just a suggestion in flex :) 
Added flex-shrink to really, really demand that the width be the width. 
/cc @BryceLTaylor
=> Fix backpack squishing

src/containers/costume-tab.jsx, src/containers/sound-tab.jsx, src/containers/target-pane.jsx, src/lib/sortable-hoc.jsx
Fixes an issue where reordering sounds could crash because the drop was being picked up by the target pane. This was because I didn't correctly split the cases where the drop occurred outside the container and the case where there were no items in the list to drop onto. Now those are handled separately. 
I reverted the previous fix and introduced a better one, with @picklesrus help. 
/cc @kchadha because you reviewed the first version.
=> Fix sound reorder crash

src/components/context-menu/context-menu.css, src/components/context-menu/context-menu.jsx, src/components/sprite-selector-item/sprite-selector-item.jsx
Reverts the reversion LLK/scratch-gui#4374 , and adds updated styling
Resolves https://github.com/LLK/scratch-gui/issues/4345
Adds BorderedMenuItem, which has a border at the top and becomes red when hovered
Use it for Delete menu (also reorder it)
Some people accidentally delete sprites because there was no difference between this and the others
=> Add BorderedMenuItem and use it for delete menu, with updated style

src/containers/blocks.jsx, src/lib/vm-listener-hoc.jsx
There is a new runtime/vm event 'PERIPHERAL_DISCONNECT' that signals intentional peripheral disconnects as opposed to peripheral errors.  This is now the event we want to use for the extension connection status icon in the blocks pane.
This PR needs https://github.com/LLK/scratch-vm/pull/1763 to land first.
=> Peripheral disconnect status using new runtime/vm event

src/lib/libraries/extensions/index.jsx
Note that the extension name appears in the extension library and in the connection modal.
=> Update WeDo 2.0 extension name

src/components/green-flag/green-flag.css, src/components/icon-button/icon-button.css, src/components/stop-all/stop-all.css, src/css/colors.css
See #4382 for more info about why, and what we need to follow up on it
Improves performance of hovering over random elements, particularly on low-power machines. 
(simulated chromebook with 4x cpu slowdown)
=> Remove scale transition from green flag, stop and sound editor buttons

src/components/asset-panel/selector.css, src/components/sprite-selector-item/sprite-selector-item.css
Also use white as the background since it gives the same impact and will not look bad if the filter isn't applied or takes a while to be applied
This is one of the things that appears much more on slower machines, since the background color is not transitioned but the filter is.
Resolves https://github.com/LLK/scratch-gui/issues/2512
=> Remove transition on sprite tiles to make placeholder not flash black.

src/components/audio-trimmer/audio-trimmer.css, src/components/audio-trimmer/audio-trimmer.jsx, src/components/waveform/waveform.jsx, test/unit/components/__snapshots__/sound-editor.test.jsx.snap
Optimize the waveform render and the playhead animation to improve FPS while playing a sound, as well as overall usability of the sound editor when dealing with larger sounds.
The individual commits give more info on the specific optimizations, but TL;DR don't render so many points, don't render so often, and when you render don't cause a layout or composite.
This does cause a visual change in the waveform display, but only for sounds that are longer than anything we have in the library. It starts skipping points conservatively, at the point where there are more svg path data points than pixels :) 
Here is the display with a long sound on develop, I could only get 10fps while playing the sound
Smooth as butter at 60fps with these optimizations. Shows the difference in the waveform also
=> Improve sound editor performance with longer sounds

src/lib/vm-listener-hoc.jsx, test/unit/util/vm-listener-hoc.test.jsx
Partially resolves issue where trying to record a sound while a project was running would result in choppy recordings.
it is still possible to get the VM to absorb so much CPU time that the recording is choppy, but this removes a common cause of choppy recordings.
Do not dispatch the targetsUpdate event when the sound recorder is up.
Anything that consumes CPU time while making a recording can lead to choppy recordings, this is a simple way to prevent one such thing.
Added a unit test for the vm-listener to cover the targetsUpdate dispatch functionality, and add another test for the new …
=> Disable target updates while sound recording

src/reducers/targets.js
This fixes the root cause of #2858, which is caused because we are rendering the sound editor based on the GUI editing target data, but retrieving the sound based on the vms editing target data. The throttle of the redux action was causing those to get out of sync while a project was running.
The throttle is not needed because the vm runtime already batches those updates at 30 fps. The updates that come from top-level actions like switching sprites go out immediately.
This is also a minor performance boost, because there was a few ms being spent in setting and checking timers that were not needed.
/cc @picklesrus I'm glad we had just been talking about this, because i'm much more confident that this can be safely removed. 
@ericrosenbaum tagging you to just test the functionality since …
=> Remove the redux throttle for targets update.

src/components/meter/meter.css, src/components/meter/meter.jsx
Improves the performance of recording a sound by optimizing how the browser repaints the audio meter.
No visual change here, just reorganizing the markup.
This is in attempt to reduce choppiness of recorded sounds by making the UI update as fast possible.
=> Move the mask on the audio meter outside the SVG for repaint performance

src/components/sprite-selector/sprite-list.jsx, src/containers/sprite-selector-item.jsx, src/containers/stage-selector.jsx, src/containers/watermark.jsx, src/lib/backpack/sprite-payload.js, src/lib/throttled-property-hoc.jsx, test/unit/util/throttled-property-hoc.test.jsx
Greatly improves performance of projects, specifically on low-power machines.
This is a more specific follow up to #4387, after talking to people about ux implications
Throttle updates to sprite list costumes to 500ms. Does not throttle any other sprite info/list property. Also throttle the watermark updates.
Introduces a new HOC to handle this specific behavior, where we want to throttle updates on a specific prop.
Costume updates come in too quickly and are not very useful.
@carljbowman this avoids the UX problems identified in our group meeting. Specifically:
- it always allows updates to all the sprite info values, so interacting with the …
=> Throttle costume and watermark updates

src/components/audio-trimmer/audio-trimmer.css, src/components/audio-trimmer/audio-trimmer.jsx
Fixes an issue where the playhead caused scrollbars to appear while playing a sound in the sound editor.
/cc @picklesrus
=> Add container with overflow hidden to prevent scrollbars from playhead

src/components/library-item/library-item.css, src/components/library-item/library-item.jsx, src/components/library/library.jsx, src/containers/library-item.jsx, src/containers/sprite-library.jsx, test/integration/costumes.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/4050
We currently manage the entire state of all of the library items (including the current costume shown when cycling through sprite costumes to animate sprites) at the level of the overall sprite-library container.
This PR takes that state management and moves the costume handling down to the individual library-item.
There are a few problems with this approach that we should be aware of:
* previously, the library-item code was agnostic as to whether or not it was showing sprites, vs. another type of library item; the sprite-library . This puts explicit costume handling into the library-item code.
* I renamed the "costumes" prop to "icons" to be more general; but, no other library item is handling these. It might make sense to just …
=> Sprite library animations no longer update the entire library state on every costume change

src/lib/get-costume-url.js
Part of https://github.com/LLK/scratch-gui/issues/4386, but this does not address the size-1 cache issue where the cache is invalidated any time there is more than 1 sprite. But that can be handled separately.
The `fontInliner` function from the `scratch-svg-renderer` was changed recently to work entirely on strings, so we can use that instead of parsing/loading/possibly drawing/stringifying the entire SVG. And `scratch-svg-renderer` already exports that function publicly, so just use it!
Using the 4x CPU slowdown in chrome dev tools, on a simple costume that just has a single text element the getCostumeUrl time goes from 10ms to 1ms, very …
=> Use fontInliner instead of entire SVGRenderer for showing costume tiles.

src/components/sprite-info/sprite-info.jsx, src/containers/target-pane.jsx
For projects with large numbers of sprites, the way we use object spread in mapStateToProps for targetPane is causing both a lot of garbage collection and a lot of extra work because of the way object spread is transpiled to vanilla JS.
It was costing almost 10ms (about 100% of the frame budget for GUI updates) on [this project](https://scratch.mit.edu/projects/247892564/).
=> Move rounding into sprite info to improve performance

src/containers/blocks.jsx
Resolves an issue where the toolbox was being repopulated twice when switching languages, as well as on initial mount (since setLocale is called in componentDidMount)
This change removes the explicit `updateToolbox` call from `setLocale`, since it is called in the `componentDidUpdate` that happens as a result of calling `vm.refreshWorkspace`. Use the utility for waiting until the toolbox update has gone through in order to make sure to turn back on block recycling _after_ the toolbox update.
It gets rid of a 100+ms of load time when loading the editor/"see inside"/switching languages. 
@chrisgarrity I remember you saw an issue before where the …
=> Avoid double toolbox update on mount and when setting language

src/css/z-index.css
- Resolves https://github.com/LLK/scratch-www/issues/2587 and https://github.com/LLK/scratch-gui/issues/4428
Changed menu-bar z-index so that the menu, and the drop down menus that are nested in the menu bar are above almost everything. The only things that cover the menu are the loading animation (in editor mode) or modals.
This does mean that dragging blocks are under the menus, as shown in the animated gif below.
* monitors should not be above the user profile menu
* alerts should not block menus from being used
Mac
Windows
Chromebook
iPad
Android Tablet
=> Menus should be over most things

test/integration/project-loading.test.js
Update the integration test that ensures that an alert shows when you try to leave a project that has changes. This test has been updated to create a different change in the project. It was previously clicking the 'move' block to introduce a project change, but this not actually a change which should introduce a project changed state (consistent with Scratch 2.0 behavior). The new functionality is a better test and makes sure that tests will work when introducing the changes from LLK/scratch-vm#1962.
cc/ @chrisgarrity, @paulkaplan
=> Update project changes test 

src/containers/blocks.jsx, test/integration/localization.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/4476
1. Make sure to load the initial locale into scratch blocks messages before rendering toolbox.
2. Mark the `locale` as a required prop, since it is being used on mount. This works because it is passed in from mapStateToProps, and the reducer has a default value (en).
3. Add an integration test to make sure this is working.
The toolbox was not being refreshed correctly if the initial locale was not english. Make sure to load the initial locale so that the toolbox does not have to first be generated in english, then again in your language.
_Please show how you have added tests to cover your …
=> [master] Hotfix/toolbox language

src/containers/costume-tab.jsx
Since the common use-case is download/edit/re-upload, and we do not want to explode the storage size of assets (which are considerably larger with fonts inlined), just do what scratch2 did and do not inline the fonts. This is not ideal if kids want to use the costumes for other purposes, but until we can create a way to strip inlined fonts before uploading to the asset server, this is the conservative way to go.
And, the code is simpler :) 
=> Export costumes without inlined fonts for now

test/integration/localization.test.js
Previous hotfix was tested independently, but didn't realize that the other localization test would cause this one to fail because of the beforeunload callback being reattached by switching languages.
=> Remove beforeunload callback that was breaking tests

src/reducers/mode.js, test/unit/reducers/mode-reducer.test.js
Retains the entire state upon a `SET_FULL_SCREEN` or `SET_PLAYER` redux action.
In some cases, these were dropping `showBranding` and I would get a missing prop showBranding (requires a boolean but got undefined)
I have added a test file for the mode reducer.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Retain showBranding mode property after SET_FULL_SCREEN action is dispatched

src/components/blocks/blocks.css, src/css/z-index.css
Resolving various gui and www z-index issues
Override the z-index for the blocks drag layer. At 1000, it will be over everything in the gui other than the navbar itself (monitors on the stage, tutorials, alerts, dropdown menus, etc.)
Ideally any block being dragged is over the rest of the UI. It returns to its normal layer when dropped.
No functional changes.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Move blocks z-index up to match gui

src/lib/file-uploader.js
- Resolves an issue where sprites uploaded from 
Don't do that!
The default for sprites is NOT draggable. They can still be dragged in the editor, but cannot be dragged in the player.
=> Make uploaded sprites not draggable

src/containers/blocks.jsx
This fixes the issue where you could not see any new variables or custom block callers, as well as fixing the issue where the toolbox did not update from then on.
- Resolves https://github.com/LLK/scratch-gui/issues/4459
- Resolves https://github.com/LLK/scratch-gui/issues/4271 (note the call block will only appear in the toolbox if you drag the define stack out of the backpack, not if you drag a call block out of the backpack, because in the latter case there is no definition. The toolbox only shows _defined_ custom blocks, and I do not think we have well-defined behavior in the situation of an undefined custom block.)
Call update toolbox after doing the workspace refresh.
_Explain why …
=> Call updateToolbox after adding new blocks from the backpack.

src/containers/blocks.jsx, src/playground/player.css, src/playground/player.jsx, test/integration/blocks.test.js
- Resolves a regression where the toolbox would not show variables after toggling between player and editor mode more than once
Make sure to always enqueue a toolbox update after calling refresh workspace. This is because any time we are consuming a new workspace from the VM, we might have new variables that are not currently being shown, and those are not in the toolbox XML. So we need to make sure a refresh happens. 
This is not a reversion of the performance improvement that removed the explicit `updateToolbox`, because that was causing it to happen twice: once sync and once async. This makes it always async, so it is safe to call `requestUpdateToolbox` after calling `refreshWorkspace`, …
=> Fix "See Inside" not showing variables

src/lib/make-toolbox-xml.js, test/integration/blocks.test.js
Related to LLK/scratch-vm#1077 and LLK/scratch-vm#1973
Thanks to @picklesrus for pairing on this!
Fixes a recent issue related to LLK/scratch-vm#1077 introduced by the changes in #4449, where adding an xml-unsafe character to a costume or sound name breaks the toolbox (see gif below).
Added test to ensure that you can still get to the sounds tab after renaming the first costume to an XML unsafe character.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Escape special characters in toolbox xml

test/helpers/selenium-helper.js, test/integration/examples.test.js, test/integration/project-loading.test.js
This is a test cleanup PR that tries to use a dynamic instead of a fixed wait for project loader tests. Instead of waiting a fixed time, use the [`until.stalenessOf`](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/until.html#stalenessOf) webdriver method to wait until the loader element is removed.
/cc @BryceLTaylor @rschamp
=> Wait until loader becomes stale to continue in project loader tests

src/components/loader/loader.jsx
Improve loading performance.
Render Loader once on when added to DOM.
Changing the state of Loader in Mount makes it render twice before it is drawn on screen. Set the messageNumber in the constructor and we can remove the second render.
Loader's impact is pretty small. A lot of the changes for making gui faster are pretty small. So it adds up.
I'll probably link to a composite branch's data.
Pending ...
Pending ...
Mac
Windows
Chromebook
iPad
Android Tablet
=> Set an initial message number to skip rendering a second time

src/lib/default-project/index.js
Improve loading performance.
Evaluate text-encoding for platforms that need it.
Most platforms provide TextEncoder. The provided TextEncoder is normally implemented natively and so much faster. Also text-encoding is about 610KB (unminified + unzipped), not evaluating it saves a small bit of performance and memory.
This is a small improvement a I'll probably produce a table with a build including multiple other changes.
Pending ...
Mac
Windows
Chromebook
iPad
Android Tablet
=> require text-encoding only if it is needed

src/lib/blocks.js
Fixes #4397.
Sorts the variable options in the "(attribute) of (sprite)" block:
Also sorts variables on the stage (i.e. "for all sprite" variables) when the stage is selected:
To make the "of" block considerably more useful in projects where there are lots of variables; and to make it more consistent with other blocks that have variable dropdowns.
No new unit tests. Tested manually.
=> Sort variable options in "of" block

.travis.yml
It doesn't affect greenkeeper subdirectories, which are the ones that cause the most issues. And now the prune step itself is breaking builds. So until it works better, remove this step.
=> Remove prune step from deployment for now

src/components/monitor-list/monitor-list.jsx, src/components/monitor/slider-monitor.jsx, src/containers/monitor.jsx, test/unit/components/monitor-list.test.jsx
- Resolves the issue where we are not allowing non-discrete sliders to have 1/100th step size like scratch 2. This is the GUI side of https://github.com/LLK/scratch-vm/issues/1971. This will only allow scratch2 imported projects to work correctly, but does not include the implementation of setting the `isDiscrete` flag, that will be handled in https://github.com/LLK/scratch-gui/pull/4436 after this goes in.
Use the `isDiscrete` flag to allow toggling between a step size of 1 (the current default) and a decimal step size of 0.01 (the scratch2 default when `isDiscrete=false`). 
Added an enzyme unit test to make sure that the …
=> Support isDiscrete sliders

src/components/stage/stage.css, src/css/z-index.css
- Resolves https://github.com/LLK/scratch-gui/issues/4269
Puts the question component on the correct z-index, above the monitors.
Test by showing a monitor and using the `ask` block.
=> Put the ask blocks text input above the monitors on the stage.

src/containers/costume-tab.jsx, src/containers/sound-tab.jsx, src/containers/stage-selector.jsx, src/containers/target-pane.jsx, src/lib/alerts/index.jsx, src/lib/file-uploader.js, src/reducers/alerts.js, test/unit/reducers/alerts-reducer.test.js
- Resolves a UX issue with importing where importing multiple files, or importing gifs, would leave the editor in a loading state for an indeterminate amount of time depending on the files, but gave no indication that something was happening. After chatting with @carljbowman, we decided the existing alert system with a spinner would be a good first step.
With sprites
With costumes
Make the file uploader return information about which file has been processed, and use that to decide when to close the alert. Add an HOC for the show/close to avoid code repetition.
---
@carljbowman just an FYI, this only creates a single alert that is closed after all files have been processed, instead of the …
=> Show an "Importing..." alert during file import

src/lib/file-uploader.js, src/lib/gif-decoder.js
Because the `onFrame` callback could do async work, it was possible for onDone to try to submit the costumes before the onFrame had produced any. This was subject to browsers different timing treatments of setTimeout vs. promise resolution. This makes the gif-decoder use the same style of progress API as the file uploader
Resolves the issue where single frame gifs could not be loaded on safari/firefox
Thanks for the help finding this issue and fixing it @picklesrus
=> Fix loading single frame gifs by removing onDone in favor of indices

src/containers/stage.jsx
https://github.com/LLK/scratch-vm/issues/1992#issuecomment-461877798
Implements the first suggestion in the above comment.
Extract the draggable's art a little later.
As it is when the gui is fullscreen or player only or the target is not draggable the function returns before setting that a drag is starting. So each mouse movement during a drag in fullscreen or player only and targets that are not draggable extract for every mouse movement.
That looks like this in a chrome devtools performance flame chart:
Depending on the system performing this work this can become very laggy.
By reordering the extraction until later we can change this to either never perform the readPixels work or for draggable targets, do it once at the beginning of the drag. (A further improvement will be to not …
=> Mouse move drag perf

src/containers/blocks.jsx, test/integration/blocks.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/4561
Make sure to enqueue a toolbox update any time the workspace is refreshed, so that the toolbox can continue updating.
Added an integration test for this case.
---
/cc @picklesrus sigh... I think this basically brings us full-circle toolbox update-wise, with the one benefit that because we are enqueuing instead of updating directly, we avoid a couple cases of double updating, because refreshing the workspace apparently cannot happen without a corresponding toolbox update because it then forever disables the toolbox from refreshing. …
=> Request a toolbox refresh after switching between tabs to fix #4561

src/lib/project-saver-hoc.jsx, test/unit/util/project-saver-hoc.test.jsx
@rschamp this is the result of what we were working on to allow consumers of the GUI to get a function that can be called to retrieve a stage snapshot.
Has a default prop value, so if nothing is passed in nothing should be wrong
=> Add a way for GUI consumer to retrieve snapshots of the stage

webpack.config.js
Resolves an issue where es6 source files make it into built GUI preventing www from building correctly.
Run the 'pify' package (introduced as a dependency of scratch-parser in LLK/scratch-parser#52) through the babel loader.
=> Run pify package through babel loader.

src/components/alerts/inline-message.css, src/components/menu-bar/author-info.css
- Resolves #4559 
use 'flex-end' & 'flex-start' instead of 'end' & 'start'
solved warnings
Mac
Windows
Chromebook
iPad
Android Tablet
=> fix(css): fix css value has mixed support warning

src/containers/stage.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/1350
Make the color picker on the stage work the same way the costume editor one does: show the picker on _either_  mouse down or mouse move, then submit the color on mouse up. This allows it to work on touch, where you can touch down to see the loupe and drag around to pick your color.
The touching color block couldn't be used on touch!
----
A lot of this change is just moving blocks of code around.
This PR can be tested on touch devices at https://llk.github.io/scratch-gui/touch-picker/
=> Make the stage color picker work with touch.

src/components/context-menu/context-menu.css, src/components/context-menu/context-menu.jsx, src/components/monitor/monitor.jsx, src/components/slider-prompt/slider-prompt.css, src/components/slider-prompt/slider-prompt.jsx, src/components/sprite-selector-item/sprite-selector-item.jsx, src/containers/monitor.jsx, src/containers/slider-prompt.jsx, test/integration/blocks.test.js, test/unit/containers/slider-prompt.test.jsx
Resolves #2053
See also: #4436 
Added slider-prompt
Added "change slider range" context menu for sliders
Decimal support:
Added a checkbox to handle integers as float
(For example, range between `0` and `100` is usually step=1, but some want to make the step 0.01)
Check the checkbox automatically when one of the range is decimal, and vise versa
Everyone wanted it! (see the Suggestions forum)
=> Slider range change with decimal value support

src/components/slider-prompt/slider-prompt.jsx, src/containers/slider-prompt.jsx
It is not reliably selecting the input and is making it hard to type into.
Fixes the issue @BryceLTaylor found testing the new slider range feature
/cc @apple502j might be interesting to you. Using select can sometimes be helpful, but it can interfere with typing. For example, if you click to the left of the number, it selects the whole thing but places the cursor on the beginning which is very strange.
=> Remove focus selecting in slider prompt

src/components/library/library.jsx, src/containers/backdrop-library.jsx, src/containers/blocks.jsx, src/containers/controls.jsx, src/containers/costume-library.jsx, src/containers/extension-library.jsx, src/containers/sb-file-uploader.jsx, src/containers/sound-library.jsx, src/containers/sprite-library.jsx
/cc @thisandagain @rschamp 
Per discussion offline, these were causing too much traffic for not enough usefulness. Leaving stuff having to do with tips library/tutorial card navigation as well as hardware extension connectivity, as those help us find issues with Scratch.
=> Remove most of the GA events

src/components/library-item/library-item.css, src/components/library-item/library-item.jsx, src/lib/libraries/extensions/index.jsx
- Resolves #4620: Allow extension tiles to display both internet and bluetooth requirement icons
Make it possible to show both bluetooth and wifi icons in extension library item tiles.
Some extensions require both things.
=> Allow for both bluetooth and internet connection icons in extensions

webpack.config.js
Part of #4598 
Allows consumers of gui (desktop, android, etc) to rebuild gui with a relative path for static assets. Default is an absolute path as that is what is required for www.
The default will build for www. With no changes to the build process it worked for my local www, and running gui locally (localhost:8601)
The android prototype npm linked to my local scratch-gui, all assets were fine after building gui with:
```
STATIC_PATH=static BUILD_MODE=dist npm run watch
```
Assets checked:
- UI elements (icons etc)
- tutorial animated gifs (including spanish)
- icons on blocks
- icons on extension blocks
- library images (including sprite costume animation)
/cc …
=> Set static asset path (publicPath) with environment var

src/lib/project-saver-hoc.jsx, src/lib/save-project-to-server.js
- Resolves https://github.com/LLK/scratch-gui/issues/4606
Move the current save code to a helper that can be eventually moved to WWW, and allow a GUI consumer to pass in a `onUpdateProjectData` method to handle project JSON saves.
See linked issue.
=> Move project saving to server to helper, allow external save action

webpack.config.js
Use babel on the @vernier/godirect dependency of VM (used by the Vernier Force and Acceleration extension). That module uses a conditional `require` for `text-encoding`, as a polyfill for MS Edge, but it does not include `text-encoding` in its `package.json` (e.g. [here](https://github.com/VernierST/godirect-js/blob/80a5ceffdc670be8eade16e6ac3067e2b6fd3105/src/Device.js#L24)). As a result (I think), we need to run it through babel in order to make sure it works on Edge in our code.
=> Add vernier module to webpack config

.travis.yml
They take up so much space and time, but aren't really looked at very much
/fyi @LLK/scratch-team
=> Exclude greenkeeper builds from gh-pages

src/lib/blocks.js
Faster Blocks rendering.
Use Intl.Collator in place of localeCompare.
Blocks compares strings in sensing_of and data category's variables list with localeCompare. localeCompare needs to do or have done some kind of work that is like creating a Collator to do the comparison. Collator takes the same options and lets us cache its internal contents. We can use the same collator and compare strings faster.
In the cases of the sensing_of block and the data category variable list we can make the list sorting much faster.
I did some quick performance benchmarks for this PR in Chrome on a 2017 15" MBP. I measured  sensing_of in 173918262 with about 40 variables on the first library sprite. Rendering the workspace for that sprite spends **79ms over 6 sort operations** for sensing_of. This PR …
=> use Collator.compare in place of localeCompare

src/lib/vm-listener-hoc.jsx
Faster project loading.
Make VMListenerHOC aware of the scratchGui.projectChanged state and only call onProjectChanged when the project is in the unchanged state.
Dispatching a message through redux makes it reconsider all currently listening components. Dispatching for each block, while loading, can mean dispatching and reconsidering thousands of times if not more while deserializing a project or creating a sprite from the backpack. While dispatching is pretty quick doing this for every block ends up taking a lot of time.
Here is some data testing the effected deserialization performance while loading 173918262.
|  device | before (ms) | after (ms) | difference (ms) | change (%) |
| --- | --- | --- | --- | --- |
|  chrome | 283 | 59 | 224 | 79.12% |
|  firefox | 496 | 137 | 359 | 72.35% …
=> dispatch projectChange redux action when project has not changed

package.json
Update to the latest release of scratch-l10n.
Due to translation errors l10n had not built for several weeks. This fixes translations and bring in updates.
I'll check that the tests pass then merge.
=> update scratch-l10n to latest

src/containers/sb-file-uploader.jsx
- Resolves https://github.com/LLK/scratch-www/issues/2769
https://github.com/LLK/scratch-gui/issues/4708 , which points out a problem that makes this fix not totally testable in playground/standalone mode
Previously, in `sb-file-uploader.js`, on uploading a project we would push to `window.history`  to clear the hash portion of the URI. This was a holdover from when Scratch 3.0 was only usable in playground mode; we would want to clear the hash project number from the URI to reflect the fact that it was no longer relevant.
We are not using hash project numbers in the URI format on the Scratch website, and even. in playground mode, we are not emphasizing them. Further, it appears that the `window.history` state management in gui's `hash-parser-hoc.js` should handle removing the hash …
=> Keep URI correct when uploading project while signed out

src/containers/blocks.jsx
Adds support for buttons used in future extensions to be able to call into the scratch blocks functions for creating variables, lists and custom procedures.
Related to LLK/scratch-vm#2083
=> Register callback keys for buttons used in future extensions.

src/components/connection-modal/connection-modal.jsx, src/containers/connection-modal.jsx
This is really a developer ergonomics improvement, but it does make loading hardware extensions more robust. Thanks to @rschamp for the idea. 
Basically, during development, you may want to load an extension from a saved file, which will work if the extension is loaded in the VM, even if it is not in the GUI extension library. Previously, with hardware extensions, this would cause a crash when you tried to connect to the device, because GUI expected the metadata used to render the connection modal to exist. This PR allows you to use the hardware extension (with various icons missing from the connection modal).
=> Prevent crash on load hardware ext without assets

package.json
/cc @BryceLTaylor 
we were seeing new errors when saving project assets like this:
=> Revert storage update due to asset saving errors

src/containers/backpack.jsx
This prevents assets from existing in the backpack server without also existing in the asset server. Credit to @kchadha for coming up with this fix.
A proposed change to prevent https://github.com/LLK/scratch-gui/issues/4649 from continuing in the future. 
Makes sure to save any unsaved assets to the asset server prior to saving them to the backpack.
This makes it impossible to have an asset saved to the backpack that is not also saved to the asset server (the canonical asset storage location)
This only needs to be done for costumes and sounds, since the other types of backpack assets do not exist in the asset server.
---
/cc @kchadha this is one …
=> Make sure to save assets before sending them to the backpack

src/components/menu-bar/menu-bar.jsx, src/containers/sb-file-uploader.jsx, src/lib/shared-messages.js, src/reducers/project-state.js, test/integration/menu-bar.test.js, test/unit/reducers/project-state-reducer.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/3509
* for logged in users, uploading a project gives it the same project id as the current project, rather than creating a new project id.
* confirm logic for upload is now: show confirm dialog if user owns current project, or project has been changed since it was opened.
* removed related code from `project-state.js` that will no longer be used
* sets the project filename from the upload file name (did not require code changes)
* confirms after showing the upload dialog (did not require code changes)
* shuts file menu if the confirm is cancelled
* changes “Creating project” to “Loading project” for the blue screen
* we plan to replace the browser `confirm()` with a custom modal
1. The new confirm logic will *not* confirm if you do the …
=> upload in current project id, rather than creating new project id

src/components/menu-bar/menu-bar.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/4604
Instead of auto-saving whenever a logged in user clicks the `Share` or `See project page` buttons, before sharing or navigating to the project page, only auto-save if the project has changed.
It's slow to auto-save unnecessarily. This is part of the larger effort to make saving happen at the right times, and only at the right times.
No tests written yet; should write some
Mac
Windows
Chromebook
iPad
Android Tablet
=> Share, See-project-page buttons will only save if project has changed

src/containers/sb-file-uploader.jsx
Fix to https://github.com/LLK/scratch-gui/pull/4700
Does NOT show user a "Replace contents of the current project?" modal if they are logged in, viewing someone else's project, and do File->Load from your computer.
This restores current functionality, rather than introducing a change to it like https://github.com/LLK/scratch-gui/pull/4700 did.
We found this message very confusing, since your upload does NOT replace the project at the id you're looking at when you do File->Load from your computer. (And it shouldn't!)
=> removed confirm prompt if you are editing someone else's project and then do file -> upload

src/components/menu-bar/confirm-replace-hoc.jsx, src/components/menu-bar/menu-bar.jsx
Less time rendering on project change and unchange.
Move projectChanged out of MenuBar into a parent component and pass MenuBar a function to test what the projectChanged logic was doing.
MenuBar uses projectChanged in some event handling behaviour. So when projectChanged changes, MenuBar renders leading to its tree being reconsidered when the nothing has changed.
Another possible implementation would be use a shouldComponentUpdate lifecycle handle. I figured the approach in this PR would be more robust (create less bugs).
These values are the amount of time spent deserializing scratch blocks from an sb3 project (173918262). The change (%) doesn't represent this very well since its over deserializing a projects blocks, when the change specifically applies to the first block being …
=> Move projectChanged into HOC wrapping MenuBar, to avoid unnecessary renders

src/lib/project-saver-hoc.jsx, test/unit/util/project-saver-hoc.test.jsx
Add an `onSetProjectSaver` prop that can be passed in from the GUI consumer to receive a trigger for saving the project. Uses the same implementation as `onSetProjectThumbnailer` which does the same thing for getting a thumbnail externally.
It is called with `null` on unmount to prevent the consumer from holding on to a dead component reference.
Allow code using the GUI to force a save at a specific moment.
Added a unit test similar to the `onSetProjectThumbnailer` prop.
=> Allow GUI consumer to receive a function for triggering saves.

src/components/menu-bar/menu-bar.jsx, src/containers/menu-bar-hoc.jsx, test/unit/containers/menu-bar-hoc.test.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/4783
* moves remaining `projectChanged` checking from `menu-bar` to new `confirm-replace-hoc` function, called `shouldSaveBeforeTransition`
* renames `confirm-replace-hoc` to `menu-bar-hoc`, since its purpose has expanded
Added tests to cover both this change, and the previous change that introduced the `confirm-replace-hoc`, https://github.com/LLK/scratch-gui/pull/4676
=> Fix auto-save when clicking See Project Page

src/lib/blocks.js
Faster initial render of ScratchBlocks.
Always return true from `ScratchBlocks.utils.is3dSupported`.
The browsers that Scratch supports will always support 3D CSS Transform.
This change provides a minor performance improvement but one that can accumulate with other changes to reduce style and layout recalculations.
Mac
=> replace Blocks.utils.is3dSupported with constant value function

src/containers/blocks.jsx
Faster loading.
Check if toolbox needs to be updated with new XML during updateToolbox.
src/containers/Blocks.jsx:updateToolbox may be called when the xml hasn't changed. Calling this.ScratchBlocks.updateToolbox with the unchanged XML does a lot of work for no change.
|  device | before (ms) | after (ms) | difference (ms) | change (%) |
| --- | --- | --- | --- | --- |
|  chrome | 117 | 1 | 116 | 99.15% |
|  firefox | 143 | 1 | 142 | 99.30% |
|  safari | 99 | 1 | 98 | 98.79% |
|  chromebook | 425 | 2 | 422 | 99.43% |
=> render only new toolbox xmls

src/components/gui/gui.jsx, src/containers/gui.jsx
Faster project load time when loading a project by id.
Related https://github.com/LLK/scratch-gui/pull/4722.
- Create the scratch renderer earlier in the GUI container/HOC stack
- Delay evaluating and rendering the GUI component until after project assets have been fetched
When loading a project by id scratch needs to load a data file and then load assets referenced by that data file. Since these requests work asynchronously outside the javascript event loop, they make events to announce to javascript when they have completed some work. GUI does a lot of work that first blocks the data request from being sent and then blocks the response events from being emitted. Delaying this GUI work until the data and assets have loaded significantly improves load time.
This PR follows #4722 by …
=> Delay loading and rendering gui

test/helpers/selenium-helper.js
Should help debug multiple issues with the GUI integration tests such as #4653
For each call to Selenium's `wait` method, set a timeout which is shorter than the overall Jasmine timeout and also include a custom message to help indicate which call timed out.
Without these changes every timeout displays the same message with the same call stack -- a call stack which doesn't include any of our test files:
```
Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
at node_modules/jest-jasmine2/build/queue_runner.js:64:21
at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
at ontimeout (timers.js:498:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)
```
The new message for a …
=> add timeouts & messages to all driver.wait calls

src/components/cards/card.css, src/components/cards/cards.jsx
- Resolves #4766: Clicking "shrink" on tutorial window should pause the video
To access the `Wistia` API object on the `window`, we need to switch the video embed from an iframe (which prevents access to its window for security reasons), to the inline-embedding style that Wistia suggests. (https://wistia.com/support/embed-and-share/video-on-your-website). Wistia video player API docs for reference: https://wistia.com/support/developers/player-api.
This also required upgrading the VideoStep React component from a functional one to a normal one, to handle the video-pausing in `componentDidUpdate`.
=> Pause video on tutorial window shrink

test/helpers/selenium-helper.js, test/integration/examples.test.js, test/integration/menu-bar.test.js, test/integration/project-loading.test.js
This should make the integration tests more stable.  This makes sure elements are visible on the page during integration tests before moving on in the tests.
Makes the FindByXpath function in Selenium helpers wait until element is visible before returning.  This replaces the WaitUntilGone method that was used in some tests. 
FindByXpath is ultimately used by all of the other ways of finding elements in Selenium helpers so this should effect most of the tests.  This should specifically make it so elements that tare hidden by the loading screen are revealed before they are clicked in tests.
After the changes the WaitUntilGone function was causing tests to fail.  Since it was supposed to solve the same problem, I removed that function from the rest of the tests.  All the tests passed locally …
=> Stabilize integration tests

src/containers/blocks.jsx
Reverts LLK/scratch-gui#4677
This may be causing a bug where after switching languages, the "Say" block contains an updated default message but when you run the block it still says "hello".
=> Revert "render only new toolbox xmls"

src/components/gui/gui.jsx, src/containers/gui.jsx
Reverts LLK/scratch-gui#4800
This causes a strange issue where the loading screen is not rendered correctly when on the project page. I will investigate more.
=> Revert "Delay loading and rendering gui"

src/components/cards/card.css, src/components/cards/cards.jsx
Reverts LLK/scratch-gui#4835
Most of the changes that #4835 introduced worked great!
However, there was one detail in that Tutorial PR that I didn’t catch in testing:
* open a tutorial with a video
* click “Tutorials” in the menu bar at the top of the page
* pick another tutorial
* ...the previous video is still there!
So we’re having to revert this change.
=> Revert "Pause video on tutorial window shrink"

test/integration/examples.test.js, test/integration/project-loading.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/4882
Might also resolve https://github.com/LLK/scratch-gui/issues/4879
* turns off two project loading tests that sometimes fail due to network speed
* fixes one test that was advancing before sound asset actually added to project, by waiting to see that it shows up in the sounds asset list
* removes unnecessary and kludgey Promise waits
Trying to get tests to help, not hurt us!
=> fixed project loading tests

src/containers/backdrop-library.jsx, src/containers/stage-selector.jsx, test/integration/backdrops.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/4797
Make the new backdrop buttons for surprise and library NOT select the stage, but let the others (file and paint) still select the stage and switch to the costumes tab.
See linked issue: https://github.com/LLK/scratch-gui/issues/4797#issuecomment-492358850
Added integration tests in `backdrop.test.js` to ensure that the 4 buttons all do the correct thing w/r/t adding a backdrop.
Mac
Windows
Chromebook
iPad
Android Tablet
=> Make surprise and library backdrop additions NOT select the stage

src/components/cards/card.css, src/components/cards/cards.jsx, src/containers/cards.jsx, src/containers/tips-library.jsx, test/unit/components/cards.test.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/4895
Pass in a `showVideos` flag that controls whether to show videos steps or instead show a "title card" consisting of the deck image and name. This is controlled by the `notScratchDesktop()` utility function from the container.
Added a `cards` unit test to test whether Video or Image steps are shown based on varying that flag.
Tested the scratchDesktop flag compatibility manually, by using the `isScratchDesktop=true` url param.
=> Use a "title card" instead of video if using Scratch Desktop

src/components/library/library.css, src/components/library/library.jsx, src/components/spinner/spinner.css, src/components/spinner/spinner.jsx
Resolves an issue where there was no feedback when clicking the "add a sprite/costume/sound/backdrop" buttons because the libraries are waiting to render all their content before showing up. Instead of that, show a spinner and then load the data. 
This is particularly noticeable on the costumes library, and particularly particularly noticeable on low-power devices. 
This also sets up future improvements where the library content (json, etc.) could be loaded async instead of bundled with the app, saving on package size.
=> Show libraries before loading their content

src/lib/libraries/costumes.json, src/lib/libraries/sprites.json
Updates to the sprite and costume libraries, from @kosiecki17: 
Sprite library changes:
- Andie - remove extra arms from andie-d costume
- Ben - remove cleats and pads, add sounds
- Jordyn - remove cleats and pads, add sounds
- Globe - new design
- Sun - new design
- Wizard girl - bring back a 2.0 sprite, add a sound
The costume library should reflect all the costumes changed and added above.
=> Updates to sprite and costume libraries

test/integration/examples.test.js
Helps temporarily address https://github.com/LLK/scratch-gui/issues/4902 by skipping the "change categories" test in examples.test.js .
=> skip example change categories test

src/containers/gui.jsx
Add a callback for when the VM is available so it can be configured by a VM consumer, similar to the way `storage` can be configured.
=> Add VM init callback

src/components/cards/card.css, src/components/cards/cards.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/4927
Use the react `key` property on the image to make sure it does not recycle the image DOM node, instead creating a new one. 
If we allow react to recycle the img node and just change its `src` property, the previous image will show until the new image is loaded. This makes it look like the image "lags behind" the tutorial step.
I needed to ensure a consistent min-height in order to prevent the card from collapsing each time the image is replaced.
Tested manually by using a slow connection and stepping through the cards.
=> Prevent previous tutorial images from hanging around on next/prev

src/components/loupe/loupe.jsx, src/components/sprite-selector/sprite-list.jsx
Updated linter caught this missing prop type! Hooray!
This was the goal of unpinning the linter deps, so yay it worked! See https://github.com/LLK/scratch-gui/pull/4786 for the history of that issue.
=> Fix PropType on Loupe component

src/components/sprite-selector-item/sprite-selector-item.css, src/components/sprite-selector-item/sprite-selector-item.jsx, src/components/sprite-selector/sprite-selector.css, src/containers/sprite-selector-item.jsx, src/lib/drag-recognizer.js, test/unit/util/drag-recognizer.test.js
Resolves a long standing issue where you could not scroll vertically in the sprites box (or costumes/sounds lists) on touch devices. This fixes that problem by deciding whether to trigger a scroll based on both distance and angle. That is the same strategy used by the blocks to decide whether to scroll or pop a block out of the blocks palette. 
The first commit shows this work dropped into the existing mouse/touch handlers. 
The next commit refactored that into a `DragRecognizer`, so that I could add tests for it. 
The final commit fixes a related issue where the context menu would come up after trying to drag the tile. The drag recognizer makes it easy to prevent this, so I figured I should include that fix here.
/cc @carljbowman This actually feels pretty great! I'm surprised at how …
=> Allow vertical scrolling of sprite tile pane on touch devices

src/components/cards/cards.jsx
- Resolves https://github.com/llk/scratch-gui/issues
Be defensive about nested property access on the wistia API object. It may not have been loaded yet.
You could cause the editor to crash if you have a slow connection and click the "next" button before the wistia api has loaded
Tested manually by using the "fast 3g" network setting, opening a tutorial with a video, and clicking next before the video has loaded.
/cc @evhan55
=> Prevent crash when wistia API takes a while to load

src/components/library/library.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/4939
Use a unique property of the data, either name (if a string) or rawUrl, as the `key` property of the array of library items. We are using `index` right now, which forces react to re-write the `src` property of images instead of just re-arranging the already rendered images. This causes the lag-behind issue of #4939 and also just makes it slower to show in general. 
Can no longer reproduce 4939, which is most easily reproduced by:
1. Open the costumes library and allow it to load.
2. Click the "Letters" tag on the right. 
3. You should see the names of the tiles change, but …
=> Fix library images lagging behind filter changes

src/lib/project-saver-hoc.jsx, src/lib/save-project-to-server.js
This patches an issue where we are not correctly handling non-200 (i.e. failures) when saving assets and saving projects.
The assets part of this is also https://github.com/LLK/scratch-storage/issues/100, but we are able to detect it here by inspecting the JSON response, which should have `status: 'ok'` but instead has a different JSON body. I think it is an open question how storage should handle network responses like this, but we can at least prevent further damage this way.
Incidentally, we were doing the same thing when trying to save projects – ignoring non-200 responses. It is important to note that, per the `xhr` docs (and it is the same with fetch) that error responses do not trigger an `error` in the promise chain or an `error` param in the callback, that only happens when …
=> Correctly fail on non-200 responses when saving

src/lib/define-dynamic-block.js, test/unit/util/define-dynamic-block.test.js
Towards LLK/scratch-vm#2120.
Depends on LLK/scratch-vm#2163.
Add support for creating custom context menu items for dynamic extension blocks. This includes support for built in functionality like opening a custom procedure edit modal as well as a callback completely controlled by the extension.
Currently the custom context menu is registered as a ScratchBlocks extension when initializing the block. This throws an error which we are currently catching and ignoring, but in the future, we need to handle registering the context menu callbacks only once.
Extensionification project!
Together with LLK/scratch-vm#2163, adds a custom context menu item to the core example extension.
=> Add support for custom context menu items for dynamic extension blocks.

src/containers/blocks.jsx, src/lib/define-dynamic-block.js, test/unit/util/define-dynamic-block.test.js
Towards LLK/scratch-vm#2120
Add a callback to update a dynamic extension block on the workspace. This callback gets passed into the vm so that the extension definition can control when a block gets updated (e.g. renaming a variable, editing a custom procedure, changing the shape of the control_stop block).
This is a feature needed for #2120, especially to support the blocks mentioned above.
Added a unit test for the function which mocks scratch-blocks specific functionality.
- Depends on LLK/scratch-vm#TBD
=> Add callback to update dynamic block on workspace.

package.json
Fixes a regression where loading project 167167477 then switching to the costume tab crashes the paint editor
=> Revert to last good scratch-svg-renderer

.browserslistrc, webpack.config.js
Apparently this is the recommendation for loaders that look at the `browsers` option.
I saw this warning while trying to re-enable Greenkeeper.
=> Move browsers options to .browserslistrc

package-lock.json
PR https://github.com/LLK/scratch-gui/pull/5003 left the package lock in a bad state. Reverting to the May version of svg-renderer
=> fix package-lock (revert svg-renderer) version

src/components/gui/gui.jsx, src/components/menu-bar/menu-bar.jsx, src/containers/sb-file-uploader.jsx
In some uses of gui (e.g. ChromeOS/Android), the app will handle changing language and file management. So the menu should be customizable to show or hide the language and file menus along with allowing a gui consumer to provide an alternate logo.
Adds `canChangeLanguage`, `canManageFiles` and `logo` props to the gui and menubar. The menus default to `true`, and the default scratch-logo is shown if no logo is provided.
Current tests pass. The current menu bar integration test will use the default config. Is there a good way to add a test for the options to hide the menus?
Mac
Windows
Chromebook
iPad
Android Tablet
=> Customize menubar

src/components/menu/menu.jsx
File menu issue that only appears when running gui in www with a logged in users
Check for null child before adding it to a menu section
=> Check for null child before cloning menu item

src/components/delete-button/delete-button.css
Delete button was too easy to hit.
Remove width/height on container to remove additional (invisible) touch slop. Left the container so that we can add it back (perhaps smaller) if we decide it's necessary,.
=> Remove touch slop

src/containers/blocks.jsx, src/lib/define-dynamic-block.js, test/unit/util/define-dynamic-block.test.js
Towards LLK/scratch-vm#2120
Adds support for the variable renaming context menu on a variable reporter block.
- fills in `RENAME_A_VARIABLE` built-in context menu callback, which opens the appropriate rename variable modal and passes back information to the VM extension callback for the context menu item.
- Updates the code in domToMutation which dynamically updates the layout of the block. Ensures that that shadow blocks (and any other blocks plugged into inputs) on updated dynamic blocks stay connected after layout update.
- Adds support for number arguments on dynamic extension blocks (this is for list blocks which use a `math_number` shadow block.
- Adds support for non-droppable menus in dynamic extension blocks
- This PR depends on LLK/scratch-vm#2242
=> Support for variables extension - Variable Renaming Context Menu

src/containers/audio-selector.jsx
@ericrosenbaum @BryceLTaylor this fixes the issue we found where the trim handles wouldn't update if your selection started at zero. This was happening because the audio-selector was using whether or not trimstart changed to update its internal state, but it should check both start and end.
=> Do not update trimmers only if both have not changed

src/containers/audio-trimmer.jsx
Fixes an issue where dragging the trim handles in the sound recorder would drag the image instead on Firefox. 
/cc @ericrosenbaum @BryceLTaylor
=> Prevent default when dragging trim handles to prevent image drag

package-lock.json, package.json, test/.eslintrc.js, test/helpers/selenium-helper.js, test/unit/containers/slider-prompt.test.jsx, test/unit/util/drag-recognizer.test.js, test/unit/util/project-saver-hoc.test.jsx
This is follow up from https://github.com/LLK/scratch-gui/pull/5049, so that kind of mistake will cause linting to fail.
Adding this caught a couple of important things:
- The sound integration tests had a `.only` in them on the version of the code I had at the time
- The project-saver-hoc tests had two tests with the same description, causing possible confusion if that test broke
=> Add Jest-specific linting rules

src/components/delete-button/delete-button.css, src/components/delete-button/delete-button.jsx, src/components/sprite-selector-item/sprite-selector-item.jsx, src/containers/delete-button.jsx, test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap, test/unit/components/sprite-selector-item.test.jsx
- Follow up to #4911
The default outline on focusing the button was ugly.
Change the focus outline to a border that matches other elements. If the element is focused (e.g. through tabbing) and the user presses space or enter, the button is activated deleting the current item.
Don’t allow the image to be dragged.
Looks better and is accessible.
No changes
Mac
Windows
Chromebook
iPad
Android Tablet
=> Make delete button accessible

src/lib/vm-listener-hoc.jsx, test/unit/util/vm-listener-hoc.test.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/4742
Separate the flag that controls if the GUI should update its internal targets list (which shouldn't happen during sound recording for performance reasons) from the flag that controls if GUI should update its internal "does the project need saving" flag, which _should_ happen during sound recording. We were recycling the flag, but the sound editor performance optimization was added later and the implications of that were not obvious.
I made the variable name for the old flag more explicit, to make the code more understandable, and 
added more unit tests to make the behavior more explicit
=> Fix saving after recording a sound

src/lib/drag-recognizer.js, test/unit/util/drag-recognizer.test.js
Fixes #5031, which is happening because the gestureInProgress call is still returning true after a drag ends.
- Resolves https://github.com/LLK/scratch-gui/issues/5031
Make sure not to call the dragEnd callback until the drag recognizer is reset. This was causing the `preventContextMenu` to remain true longer than it should, causing the linked issue.
=> Fix issue where context menu wouldn't come back after dragging

src/components/blocks/blocks.css
- Resolves https://github.com/LLK/scratch-gui/issues/1307
- Fixes https://github.com/LLK/scratch-gui/issues/2755
Instead of using `pointer-events: none` on the blocks drag layer, set its width/height to 1 (setting to zero makes it disappear) and allow overflow. This allows hover events to fall through (used for sharing blocks to other sprites) but keep the click behavior where the drag layer handles the click on duplicate and drag. 
This is hard to explain, but here goes:
- After duplicating blocks, you then need to click to drop the blocks.
- If you click on a stack to insert the duplicated blocks into a stack, it should attach the blocks but not …
=> Fix duplicate running blocks by removing pointer-events: none

src/lib/download-blob.js
- Helps to resolve import issues with the Android version of Scratch
Adds the mime-type to the download link.
Current tests are ok
Mac
Windows
Chromebook
iPad
Android Tablet
=> Get the mime-type for the file from the blob

src/components/blocks/blocks.css
Reverts LLK/scratch-gui#5078
This breaks dragging blocks on chrome on windows :( :( :(
=> Revert "Fix duplicate running blocks by removing pointer-events: none"

src/containers/target-pane.jsx
This is a partial fix for the issue where importing non-sprite zips as sprites causes the import spinner to show up forever. I broke this out from https://github.com/LLK/scratch-gui/pull/5090 since I wanted to fix the functionality in the current system (where there is no error alert) before introducing new functionality (a dismissable error alert). 
Like in other situations where file parsing fails, just close the importing alert.
Resolves #4639
=> Close importing after failing to import

src/lib/libraries/decks/translate-video.js
Portuguese (Brazilian) videos were not appearing when language was switched to Portuguese (Brazilian), though they were appearing for Italian and Portuguese
Changes Portuguese (Brazilian) locale to 'pt-br', was mistakenly written as 'pt-BR'.
=> Fixed Portuguese (Brazilian) locale for tutorial videos

package-lock.json, package.json
Closes #5139 
Update scratch-render.
=> Greenkeeper/scratch render 0.1.0 prerelease.20190830194018

src/lib/vm-listener-hoc.jsx, test/unit/util/vm-listener-hoc.test.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/4244
Instead of sending both `key` and `keyCode` (which the VM ignores), send `keyCode` as `key` when the `key` is the string `"Dead"`. That is what happens when you keyup on a bluetooth keyboard in safari. The keycode information is still valid, but for some reason the `key` property is not.
Keypressed block would remain true forever when using iOS Safari and a bluetooth keyboard.
Added unit tests for the keyup/keydown listeners of the vm-listener-hoc, including this new special behavior
Note: needs to be tested on iOS Safari + …
=> Fix bluetooth keyboards with iOS keypress blocks

src/components/asset-panel/selector.css
Resolves LLK/scratch-gui#3278.
Uses the `.list-area:after` pseudoelement to add padding to the end of the scroll area. See [this StackOverflow post](https://stackoverflow.com/a/22040425/4633828) for my reference; I had to add `flex-shrink: 0` so that the element wouldn't just get squished when it's meant to grow the scroll area.
This makes it easy to drag and select the bottom tile in asset pickers.
I considered reusing the `$fade-out-distance` variable but decided against it because I saw there was already a `padding-bottom: 70px` property, which was meant to fix this issue itself but apparently no longer works (or never did in the first place). I used that value instead.
I tried putting a `margin-bottom` on `.list-area > :last-item` as well, but that didn't seem to have any effect. In …
=> Use list-area:after to pad scroll area

src/containers/blocks.jsx, test/integration/blocks.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/1452
Make the toolbox use the _last_ costume/sound/backdrop instead of the first one, so that when you add a new asset, it is automatically available in the blocks to use right away.
See discussion in https://github.com/LLK/scratch-gui/issues/1452
Updated the selenium tests that were specifically introduced to document this behavior
=> Default blocks to last asset instead of first

.travis.yml, package.json
Google Chrome doesn't install on Travis trusty anymore for some reason. Bump to xenial so we have Google Chrome.
Also use a method I discovered for keeping the installed version of chromedriver up to date, so whenever chrome is updated, chromedriver will also update on the VM.
Also un-hack the integration tests so that it matters when they fail again.
=> Use not broken Travis VM distribution

src/components/record-modal/record-modal.css, src/containers/recording-step.jsx, src/lib/audio/audio-recorder.js
Helps with https://github.com/LLK/scratch-gui/issues/1735
Use an 8x larger buffer size for script processor node, which allows the browser much more leeway in terms of how quickly it needs to run the script processor node before buffers start getting dropped. This does not impact the smoothness of the visualization, which is run at RAF framerate using a separate analyzer path. 
I had to change the `stop` function, which previously was relying on the buffer size being 1024 implicitly (it would submit RMS chunks depending on the script processor buffer length). Instead use the other RMS utility by switching around the order of operations.
By using a …
=> Use a larger buffer size for recording to prevent glitching

src/components/monitor/monitor.jsx, src/lib/blocks.js, src/lib/define-dynamic-block.js, src/lib/monitor-adapter.js, src/lib/opcode-labels.js, test/unit/components/monitor-list.test.jsx, test/unit/util/define-dynamic-block.test.js, test/unit/util/opcode-labels.test.js
Add support for monitors in variables extension. Monitor info now uses color directly instead of using a category string to look up the appropriate color. This also means that the VM can then use the block instance color for the monitor color. Additionally add support for enabling a monitor for a variable/list that was just created using the modal.
Update tests that were previously broken. Update monitor related tests to account for new changes.
- This PR depends on LLK/scratch-vm#2262
=> Variables Extension Monitors

test/integration/blocks.test.js
- Resolves https://github.com/LLK/scratch-gui/issues/5177
Skip a test that seems to be passing locally but isn't running on travis. It may be due to the unicode characters in the search, that might have changed in chrome/chromedriver recently.
=> Skip flakey test

src/lib/libraries/backdrops.json, src/lib/libraries/costumes.json, src/lib/libraries/sprites.json
The Android Studio svg to xml code can't interpret the svgs exported by our paint editor. This should fix the watermelon-a and basketball-1 costumes on android.
=> Reupdate watermelon a and basketball background with asset exported from sketch

.travis.yml
This flag essentially configures how much memory Node can use. If it’s too low, then Node processes may hang as Node spends time garbage collecting. Increasing it allows more memory to be used before garbage collection is necessary.  Travis VMs have 7.5GB of memory, so set the limit to just below that to avoid running out of memory completely.
Resolves #5186. @fsih saw a webpack build hang until increasing this limit there. So increase it now to avoid this failure in the future.
Also I reordered the variables to be alphabetical just so there was some system there.
=> Allow Node to use more memory for old space

src/components/sound-editor/sound-editor.jsx, src/containers/sound-editor.jsx, src/lib/audio/audio-effects.js, src/lib/audio/effects/volume-effect.js
Resolves https://github.com/LLK/scratch-gui/issues/5142
Before applying the "louder" effect in the sound editor, measure the RMS of the sound. If any part of it is above a threshold, do not apply any gain.
You can try out this change here:
https://ericrosenbaum.github.io/scratch-gui/limit-louder-rms/
**Questions**
- How does the threshold feel? Should it be higher or lower?
- ~~How does it feel for the effect to simply stop working above the threshold? Should we disable the button in that case (not clear exactly how this would work)?~~ **UPDATE** I'm now disabling the button when the sound or selected region of the sound is too loud. This also prevents the issue with the undo stack when you were able to press the button with no result.
- The RMS limit is checked *before* applying the …
=> Limit louder effect with a max RMS

.travis.yml
These builds make our gh-pages branch too large for GitHub to handle. Thanks to @fsih for deleting all those builds. This will keep them from re-populating.
@fsih I'm never sure who to assign for this type of change, so I assigned you since we talked about it. Here's the relevant part of Travis' docs. https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on
=> Don’t push tags to gh-pages

src/components/sound-editor/sound-editor.jsx, src/containers/sound-editor.jsx, src/lib/audio/effects/volume-effect.js
Reverts LLK/scratch-gui#5149
Turns out this causes the softer button to max out the volume louder :(
=> Revert "Limit louder effect with a max RMS"

.circleci/config.yml, package-lock.json, package.json
This adds a config for CircleCI. When this PR is merged, nothing special will happen until I enable CircleCI on this repo, which I will do as soon as it's merged. After that, the CircleCI config will take effect, running tests at the same time as Travis.  This will just be for trial purposes, making sure that CircleCI works at least as well as Travis, and to get a feel for the types of failures/annoyances we will face if we switch to CircleCI.
=> Add config for CircleCI

src/components/sound-editor/sound-editor.jsx, src/containers/sound-editor.jsx, src/lib/audio/effects/volume-effect.js
resolves https://github.com/LLK/scratch-gui/issues/5142
Before applying the "louder" effect in the sound editor, measure the RMS of the sound. If any part of the selected region (or the whole sound, if nothing is selected) is above a threshold, disable the louder button.
It's easy to press the louder button repeatedly and create badly distorted sounds. This limitation does not completely prevent the distortion, but reduces how bad you can quickly make it.
The previous attempt at this fix (https://github.com/LLK/scratch-gui/pull/5149) also included a "hard limiter" on the volume effect, but this version removes it. 
The hard limiter was meant to make the distortion caused by the louder button more consistent: without it, audio samples can get beyond their normal range of -1 to 1, and the …
=> Limit louder effect with a max RMS (w/o waveshaper)

src/lib/define-dynamic-block.js
Fixes an issue where attempting to renaming a variable to an existing name (and clicking okay in the resulting alert that pops up) throws an error.
=> Handle name being null in rename callback. 

src/lib/backpack/jpeg-thumbnail.js
Note: paired with @kchadha 
- Resolves https://github.com/LLK/scratch-gui/issues/5195
Instead of drawing the image at its native resolution, just as a jpeg, make the image smaller (chosen somewhat arbitrarily to be 3x the max displayed size of 32px (3x bc that is now a common pixel density for HD screens). 
So instead of causing the thumbnail to be 200% the size of the original backdrop, the thumbnail is now 5% the size of the original. :) 
@kchadha and I made this test harness on glitch to do some prototyping, but there are no additional automated tests here.
https://glitch.com/~jpeg-thumbnail-test
=> Draw backpack thumbnails smaller

src/components/library-item/library-item.css
Resolves https://github.com/LLK/scratch-gui/issues/5240
* alters the css of the extension modal tiles' description to have smaller line-height, and greater padding-top to compensate.
Before:
After:
n/a
Mac
Windows
Chromebook
iPad
Android Tablet
=> Fix extension modal tiles' description line height

src/components/monitor/monitor.css
Fixes #4823.
Changes the whitespace CSS on the element from `nowrap` to `pre`.
We want to display the whitespace in lists exactly as it was added!
Tested manually:
Note that `white-space: pre` prevents the text from wrapping, just as we want ([until this is fixed](https://github.com/LLK/scratch-gui/issues/2744)). (We'd want `white-space: pre-wrap` to wrap it.)
Linux Firefox, Chromium.
=> Always display whitespace in list monitors

test/helpers/selenium-helper.js
Add `--autoplay-policy=no-user-gesture-required` to the flags passed to the Chrome instance used by Selenium.
Running integration tests currently floods the console with messages like this, at least on Windows:
```
[1030/101911.880:INFO:CONSOLE(294404)] "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu", source: file:///E:/GitHub/scratch-gui/build/lib.min.js (294404)
```
Any other messages printed to the console get lost in the flood.
If we adjust our AudioContext handling we may want to back out this change since this might make it more difficult to test autoplay behavior.
Note that this change will cause local tests to make noise again. If that's not desirable I can look for another way to solve this …
=> tests: set --autoplay-policy=no-user-gesture-required

webpack.config.js
Files like src/lib/libraries/sprites.json were being used by
packages like scratch-desktop in order to fetch all the library
assets for offline access. We stopped publishing src in #5263 to
stop bloating the dist with copies of src files. Explicitly
exporting the files that are needed by other repos is a better
long-term plan.
The files are now published to dist/libraries/*.json. Once this is
merged those repos that use the src/ path need to change it to e.g.
`require('scratch-gui/dist/libraries/backdrops.json')`
I did wonder whether these files should be copied into /dist vs.
copying them into the root of the package. Any thoughts @rschamp @chrisgarrity ?
=> Include library JSON files in package distribution

src/lib/libraries/decks/translate-image.js
Changes translate-images.js file so that the Spanish tutorial images load for Latinamerican Spanish
This change would mean that Latinamerican Spanish has tutorial images for all tutorials
=> Make Spanish tutorial images also load for Latinamerican Spanish

package-lock.json, package.json
Brought this out briefly for HOC release, but it is ok to go back in
=> Bring back in renderer update with mipmap change

src/lib/project-saver-hoc.jsx
ProjectSaverHOC has been using the wrong call signature for `doneUpdatingProject`.
I didn't look for an issue, since this doesn't fix any behaviour.
The call signature for `doneUpdatingProject` expects a single argument, the `loadingState`. However in the `mapDispatchToProps` it was being called with two arguments, but in a way that was actually logically correct. This change reduces it to one argument to match the function definition and usage.
Relevant code sections:
- `project-saver-hoc.jsx:updateProjectToStorage` uses `this.props.onUpdatedProject` with just a loading state
- `project-saver-hoc.jsx:mapDispatchToProps` defines `onUpdatedProject` as a function with two arguments and passes both to `doneUpdatingProject`
- `project-state.js:doneUpdatingProject` defines …
=> Fix `doneUpdatingProject` call signature

src/containers/sound-editor.jsx, src/lib/audio/audio-util.js, test/__mocks__/audio-effects.js, test/unit/containers/sound-editor.test.jsx, test/unit/util/audio-util.test.js
Add a step to the sound editor to downsample the sound if needed in order to be saved. This augments the previous behavior where it just refused to edit sounds that were too long.
In addition to the downsampler, which just reuses some code that @ericrosenbaum had already made for matching sample rates, this required changing the main entry point function for updating sounds from synchronous to asynchronous, since the resampling process is async.
This change allows for 2x longer sounds to be edited with the sound editor. This includes things like making background music quieter (thanks @zoebentley for example projects with this), muting bad words in songs and otherwise trimming and editing imported songs.
Due …
=> Implement sound downsampler to try to allow more sounds to be edited

src/lib/titled-hoc.jsx, test/helpers/selenium-helper.js, test/integration/project-state.test.js
https://github.com/LLK/scratch-gui/pull/5168 was originally intended to resolve https://github.com/LLK/scratch-gui/issues/3433 and https://github.com/LLK/scratch-desktop/issues/71 , but then it was narrowed in scope to a general refactor of project title handling.
This change should resolve https://github.com/LLK/scratch-gui/issues/3433 and https://github.com/LLK/scratch-desktop/issues/71 .
When project state transitions into `isShowingWithoutId` being true, set the project title to the default title, and call GUI's owner's `onUpdateProjectTitle` function.
In standalone and desktop modes, File->New was not resetting title.
We don't have good testing for this functionality yet. What would it look like?
=> reset title on transitioning to isShowingWithoutId

src/containers/library-item.jsx
- Resolves https://github.com/LLK/scratch-gui/issues/5084
Updates the `library-item` which was expecting library items to have the `baseLayerMD5` property to now use either `baseLayerMD5` or `md5ext`, which is what is what the libraries json will have once we start using the new library generator that works on 3.0 projects. 
This _does not_ update the library JSON files, as there are other blockers for that.
See https://github.com/LLK/scratch-gui/issues/5084 for more
Manually tested that costumes rotate correctly using the existing format, so this can be merged right away. Also tested …
=> Update library-item to handle 3.0 or 2.0 library formats

src/lib/supported-browser.js
This modal may be preventing the crawler from correctly indexing pages, because it takes over the whole screen.
(note: I would have used `bowser.googlebot` but it doesn't actually work consistently, since the googlebot smartphone does not appear to bowser as googlebot, and reports itself as using chrome 41, even though they changed it to being up-to-date with current chrome. But googlebot is still in the ua, so I used that)
/cc @rschamp we can chat about this when you have a moment. I noticed that even with our previous fix for correctly canonical ref google still isn't indexing project pages, and it looks from the search console tools that this full screen unsupported modal may be the answer. The reason it comes up is that the crawler has a "quota" for network requests and starts …
=> Do not show unsupported browser modal for googlebot

src/lib/cloud-manager-hoc.jsx, test/unit/util/cloud-manager-hoc.test.jsx
* removes `shouldNotModifyCloudData` function and replaces it with prop `canModifyCloudData` (with opposite boolean value)
* Sets prop defaults so that code which renders GUI (such as www's embed view) can safely omit most props, and trust GUI to still render as expected
=> simplify props of cloud-manager-hoc

package-lock.json, package.json
- Resolves https://sentry.io/organizations/scratch-foundation/issues/1334444995/?project=1357122&query=is%3Aunresolved&statsPeriod=14d
Rolling this back because it introduced a crash on ipads when opening the eyedropper tool
Rolls back a fix to stacking buttons in the paint UI
Mac
Windows
Chromebook
iPad
Android Tablet
=> Revert "Greenkeeper/scratch paint 0.2.0 prerelease.20200129174741"

package-lock.json
Fixes https://github.com/LLK/scratch-gui/pull/5433 which didn't include package-lock update
=> Resync package-lock for scratch-paint

test/integration/blocks.test.js
- Resolves  https://github.com/LLK/scratch-gui/issues/5429
Skips the flaky test
The test is flaky, so we're going to take it out until we can figure out how to make it pass
=> Skip blocks “renaming costume wtih special character” test

README.md
Because there are some very large files in the repository history
Workaround for #5140
Add a note to the README about cloning with minimum depth
So people don't have to wait such a long time to clone the repository
=> Add note about cloning to README

package.json
Commits to gh-pages "fail" on CircleCI since there's no config on the branch. Skip these commits using a tag I can't write here because I do want CI to run on this commit :)
/fyi @chrisgarrity @paulkaplan @ericrosenbaum
=> Ignore commits on the gh-pages branch for CI

src/lib/libraries/backdrops.json
Some SVG backdrops display thumbnails incorrectly after being saved in the 3.0 paint editor. This change reverts these to the 2.0 SVG versions.
=> Use 2.0 versions of some svg backdrops

test/integration/blocks.test.js
* Resolves flakiness in the two tests mentioned here: https://github.com/LLK/scratch-gui/pull/5178
* Resolves flakiness in https://github.com/LLK/scratch-gui/issues/5429
* Resolves flakiness in https://github.com/LLK/scratch-gui/issues/5177
* adds findByXpath to wait for updated or new items to appear
* adds an ENTER keypress
both are intended to allow callbacks to be called before we unmount the Costumes or Sounds tab.
=> unflakify four blocks integration tests

src/reducers/project-state.js, test/unit/reducers/project-state-reducer.test.js, test/unit/util/project-saver-hoc.test.jsx
Resolves https://github.com/LLK/scratch-gui/issues/5361
Adds unit tests for many project state reducer action creator functions.
Also refactors the project state reducer's `onLoadedProject()` function to be clearer, and to specifically handle failures to load the default project by switching to an error state.
(This relates to the project state reducer's handling of success and failure in loading the default project. Since we get that project data locally, and not from the server, loading it into the VM should always succeed. If it fails, we should switch to an error state.)
This change doesn't make a change to actual behavior, only to the project state reducer's API for clarity and consistency.
=> refactor onLoadedProject() creator to handle success==false consistently; add tests of project state action creators

package.json, src/components/mystery-mode/mystery-mode.css, src/containers/stage.jsx
<details>
<summary>This makes mystery mode significantly more mysterious.</summary>
If merging this, you'll probably want to create your own totally-normal renderer branch.
</details>
https://www.youtube.com/watch?v=fq3abPnEEGE
Linux
Mac
Windows
Chromebook
iPad
Android Tablet
=> Enhance mysterious atmosphere

package-lock.json, package.json
This is the correct version of scratch-blocks to bring in the kurdish update.
=> Greenkeeper/scratch blocks 0.1.0 prerelease.1585138708

src/containers/stage.jsx
See [this comment](https://github.com/LLK/scratch-gui/pull/5532#issuecomment-603422282)
This PR ensures that mystery mode is disabled when not in editor mode.
Things were getting a bit too shadowy.
Linux
Mac
Windows
Chromebook
iPad
Android Tablet
=> Demystify non-editor mode

src/components/gui/gui.css, src/components/gui/gui.jsx, src/components/menu-bar/menu-bar.jsx, src/components/stage/stage.jsx, src/containers/stage.jsx, src/lib/rubber-canvas-frag.glsl, src/lib/rubber-canvas-vert.glsl, src/lib/rubber-canvas.js, src/reducers/gui.js, src/reducers/wobbly-dragging.js
Since 2006, Linux users have been enjoying wobbly windows through the [Compiz compositing window manager](https://www.youtube.com/watch?v=USedxVrU2Ko).
As I was once a Compiz user myself, I was surprised to find this vital\* and extremely useful\* behavior has been missing from Scratch for its entire existence!
As such, I have decided to implement this feature\* in Scratch:
This should greatly\* increase\* the productivity of the average Scratcher.\*
Linux
Mac
Windows
Chromebook
iPad
Android Tablet
My Android Phone
\* *These statements have not been evaluated by the Food and Drug Administration.*
=> Make sprites wobbly when dragged

test/helpers/selenium-helper.js, test/integration/blocks.test.js
Resolves #5429 
Resolves #5480
Resolves #5015
Resolves #4903
This PR adds a new method to `SeleniumHelper` named `clickBlocksCategory`. This function does the following:
- Waits for the `div class="blocks_blocks"` element to appear
- Sleeps for 100ms, because block category elements are rapidly created and deleted, and clicking on one as soon as it is created could result in a `StaleElementReferenceError`.
- Clicks the category.
- Waits 500ms for the scrolling animation to finish.
All block category switches in `blocks.test.js` now use this method.
This should make tests less flaky.
=> Add clickBlocksCategory integration test helper function

src/lib/download-blob.js
This allows exporting of projects/sprites/costumes/sounds in iOS Safari.
iOS safari does not support the `download` attribute on `<a>` elements, so we need to read the blob as a data-uri and assign that to a popup window. This prevents the situation where trying to export closes the project, possibly losing work. It is not a great experience on iOS, though. It opens a new tab, but the file name is always "unknown". It does allow the user to download sprite/project files to the local "Files" app. For costumes/sprites, it just shows the asset in a new tab, using the menu at the top/right allows the user to download the image/sound.
Apparently iOS13 will have support for downloading files, so we should keep an eye on this in the fall, but it looks like it will just automatically switch over …
=> Allow some kind of downloading to work on iOS Safari

src/components/stage/stage.css
Resolves #5706 (also reported [in this Bugs and Glitches forum thread](https://scratch.mit.edu/discuss/topic/343753/))
This change removes the `align-items: center` directive from the `stage-overlay-content` wrapper, as the wrapper's child element is a `DOMElementRenderer`, which is not `display: flex`, and non-flexbox elements do weird things with `align-items`.
Another solution would be to change the `DOMElementRenderer` to wrap the rendered element in a `<Box>` instead of a `<div>`, but the scope of that change seems bigger even though the `DOMElementRenderer` is only used for the stage.
This removes the white line from the bottom of the stage:
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/25993062/68047588-22860780-fcb5-11e9-93de-7d4a419c5ff0.png …
=> Don't align-items: center in stage-overlay-content

src/lib/project-saver-hoc.jsx
Make offline telemetry system record `projectDidSave` for autosaves/manual "Save Now" button pushes. Right now `projectDidSave` is only emitted for file export, because that is currently the only way to save in the desktop editor. But as we improve the different ways "offline" apps can save projects, we want to make sure we get the relevant telemetry. 
We talked about whether to have separate events for autosaving, etc. but want to keep the event space small, and this shouldn't impact the current telemetry from scratch-desktop, which won't be using this code path for now anyway.
I also made the `reportTelemetry` function more defensive and wrapped it in a try/catch because it is not essential to the saving process, so if it fails it should not stop the promise chain that saving …
=> Emit projectDidSave for all types of saves, not just file exports

src/components/library/library.jsx, src/components/scratch-image/scratch-image.jsx, src/containers/library-item.jsx
Resolves a problem specific to the scratch-desktop branch in which the library icons for sprites would not correctly animate even in the presence of multiple costumes.
Two changes:
- if a library item (or sub-item) contains both `assetId` and `dataFormat` properties, use those to determine the icon. Prefer that over options which require splitting on `.`
- if a library item (or sub-item) has a property called `md5ext` use that (higher priority than existing code which used `md5` or `baseLayerMD5`).
An animated library item may now have `assetId` and `dataFormat` properties. The new library generation code provides these properties and they align better to the way `scratch-storage` works.
Also, a library item may now contain a property called `md5ext`, which is just a renamed version of …
=> fix costume animation in sprite library

src/components/gui/gui.jsx, src/components/telemetry-modal/telemetry-modal.jsx
This supports work toward LLK/scratch-desktop#97
The GUI now supports passing in an external handler for displaying a privacy policy. If this handler is provided, it overrides the behavior of the privacy policy link in the telemetry opt-in/out dialog.
Bonus fix: if no handler is provided, the telemetry opt-in/out dialog now loads the web-based privacy policy in a new window or tab instead of the current one.
The `scratch-desktop` privacy policy is displayed by a separate Electron window rather than being loaded from the web. Since `scratch-gui` doesn't have access to that information, passing in a handler allows the functionality to be delegated to `scratch-desktop`-specific code.
I tested this locally in the context of Electron. Should we have automated tests for this?
=> add hook on telemetry dialog for displaying privacy policy

src/lib/drop-area-hoc.jsx
Resolves #5642
This PR omits `componentRef` from the props that `DropAreaHOC` passes into its wrapped component.
If `DropAreaHOC` passes the `componentRef` prop into its wrapped component, this could potentially "clobber" alternative values of `componentRef` if the wrapped component is not expected to have a `componentRef` property.
This happened in the `StageSelector` component, [which sets the `componentRef` of its child `Box` component and *then* sets all of the `Box`'s remaining props to its own props](https://github.com/LLK/scratch-gui/blob/f7853a935400464f8097d8c9815108cfc6a41510/src/components/stage-selector/stage-selector.jsx#L72). Because the wrapped `StageSelector` gained a `componentRef` prop out of nowhere, it was overwriting the `Box`'s `componentRef`, breaking the …
=> Omit componentRef from DropAreaHOC's passed props

.travis.yml
* chromedriver will no longer work on node 8
* paper.js has a problem with node 12
* node 10 is just right ;)
=> use node 10 for travis builds

src/components/alerts/alert.css, src/components/gui/gui.css
Resolves #4428 
Add pointer-events to alert container CSS
Container caught the onclick event and didn't pass to things under it, therefore it blocked menu items.
To test this, go to Sound tab, upload a non-music file (such as text), and cause forever Importing. (this bug is documented #4639 )
Try changing tabs, selecting menu items, and else. All should work fine.
*This is one of my progress for adding "Record Project Video".*
=> Add pointer-events to alert container CSS

src/components/stage/stage.css
Resolves #5703
This PR removes the `box-sizing: content-box !important;` CSS rule from the blue box that appears around sprites when they are clicked.
`box-sizing: content-box` means that the `width` and `height` of an element will *not* include that element's border. The default used in scratch-gui, `box-sizing: border-box`, *does* include that element's border in the width and height.
The `target-highlight.jsx` code [already includes the blue box's border when calculating its width and height](https://github.com/LLK/scratch-gui/blob/develop/src/containers/target-highlight.jsx#L54-L55), so by setting `box-sizing` to `content-box`, we are adding the border size twice: once in `target-highlight.jsx` and once in the CSS. This makes the box appear 4 pixels too large in each dimension.
Tested …
=> Remove box-sizing: content-box from sprite highlight box CSS

src/containers/blocks.jsx
- A step towards https://github.com/LLK/scratch-gui/issues/2174
This PR goes along with https://github.com/LLK/scratch-vm/pull/2442, which allows a target to be passed to `getBlocksXML`.
It changes `getToolboxXML` to now pass that target in.
This is necessary for the VM to generate a different toolbox depending on which target is selected, to e.g. show/hide certain blocks on the stage/sprites.
Tested manually
Linux
Mac
Windows
Chromebook
iPad
Android Tablet
=> Pass current editing target to getBlocksXML

src/containers/stage.jsx
- Resolves #5509
This PR calls `renderer.draw()` immediately after calling `postSpriteInfo` in `Stage.onStartDrag` and `Stage.onStopDrag`.
This removes the one-frame delay between when a sprite starts/stops dragging and when the "dragged sprite" overlay appears:
Before | After
-- | -
Tested manually
Linux
Mac
Windows
Chromebook
iPad
Android Tablet
=> Call renderer.draw immediately on drag start/stop

src/css/colors.css
- Resolves #5734
This PR adds an alpha value of 1 to the CSS `hsla()` color used for highlighted sprite pane tiles.
Edge can't parse `hsla()` color values without an alpha value.
Tested manually
Linux
Mac
Windows
Chromebook
iPad
Android Tablet
- Add more sprites and test that when you drag assets and blocks over the sprite pane, those sprites' tiles:
- Now turn blue on Edge
- Still turn blue on other browsers
=> Fix sprite tile highlight color on Edge

src/components/gui/gui.css, src/components/gui/gui.jsx, src/components/stage-wrapper/stage-wrapper.css, src/components/stage-wrapper/stage-wrapper.jsx, src/components/stage/stage.css, src/components/stage/stage.jsx, src/containers/green-flag-overlay.jsx
- Resolves #5507
There are a lot of changes in this PR, but I'll try to cover most:
- Replace hack introduced in https://github.com/LLK/scratch-gui/pull/2354 with proper flexbox solution
- Move full-screen wrapper duties from `Stage` to `StageWrapper`
- Properly position and size elements overlaid onto the stage
- Make the `Stage` component into a `React.Fragment` instead of a `<div>`
- Remove `left: 50%; marginLeft: stageDimensions.width * -0.5` hack (introduced in #3205) from `stageBottomWrapper`
- Remove some obsolete CSS
- Remove unnecessary `isStarted` prop from `GreenFlagOverlay`
This fixes a lot of positioning and sizing bugs in stage overlays (for variables, the color picker, dragged sprites, etc), mostly related to the one-pixel stage border resulting in some hard-to-see layout …
=> Refactor stage layout

src/lib/download-blob.js
resolves https://github.com/LLK/scratch-gui/issues/1783
When saving to a local file (file -> save to your computer), wait briefly before removing the download link. This prevents the crash on iOS 13, and the file downloads with a correct filename and extension.
Not 100% sure why this works, but it probably prevents a race condition in iOS Safari.
No tests
Mac
Windows
Chromebook
iOS
Android Tablet
=> Prevent crash when saving locally on iOS 13 safari

package.json, webpack.config.js
Currently, webpack progress output is enabled at all times. This change enables progress output only when the "CI" environment variable is empty or unset, effectively disabling progress output on continuous integration build servers.
The webpack progress plugin output is huge and can cause performance problems when trying to scroll through a CI build log.
CI log size:
| | Before this change | After this change |
-- | -- | --
Number of lines | About 11k | About 2k
File size | About 2 MB | About 289 KB
Local output (with the "CI" variable unset) should remain unchanged.
Tested locally by running the build with and without the "CI" environment variable set. See also the CI build attached to this PR ;)
NA
=> disable webpack progress plugin on CI

src/lib/analytics.js
Resolves https://github.com/LLK/scratch-gui/issues/5775
Call `GoogleAnalytics.initialize(...)` only if either `process.env.GA_ID` or `window.GA_ID` is set.
It turns out that `GoogleAnalytics.initialize(...)` causes the download of `https://www.google-analytics.com/analytics.js` even if passed a null or undefined GA_ID. Skipping the call means we don't download that file in cases where we don't need it. In particular, we shouldn't try to download that file in Scratch Desktop since a) we should assume that the Internet is not available and b) we don't intend to use Google Analytics in Scratch Desktop.
We don't have automated tests for our usage of GA, but I've tested this locally in the context of Scratch Desktop. I'm unsure of how best to test this in the context of scratch-www or …
=> initialize Google Analytics only if GA_ID is set

src/containers/stage.jsx
Resolves https://github.com/LLK/scratch-render/issues/294
Resolves #2388
Resolves #1782
~~Resolves (no longer does) #1894~~
Resolves https://github.com/LLK/scratch-render/issues/657
This PR updates the GUI to use the new `extractDrawableScreenSpace` method introduced in https://github.com/LLK/scratch-render/pull/568. In addition, it moves the "drag offset" math into the `Stage` container instead of leaving it to `extractDrawable`.
This resolves the four bugs mentioned above.
Tested manually
Linux
Mac
Windows
Chromebook
iPad
Android Tablet
Android Phone
=> Extract dragged sprites' drawables in screen space

src/lib/backpack/jpeg-thumbnail.js
Resolves #5972
If the sprite height/width is less than one, use 96(maxDimension)x96 white square as the backpack thumbnail
drawImage fails if the image is too small. I did not compare width===0 because it's possible that very-small-but-positive numbers (like 0.01) can cause this as well, and I heard some implementations floor instead of round.
Manually tested using http://localhost:8601/?token=X-TOKEN-HERE&backpack_host=https://backpack.scratch.mit.edu&username=apple502j
(by the way, why is it JPEG instead of PNG?)
=> Fix backpacking zero-height/width costumes

src/containers/blocks.jsx, src/containers/target-pane.jsx, src/lib/layout-constants.js, src/reducers/gui.js, src/reducers/workspace-metrics.js, test/unit/reducers/workspace-metrics-reducer.test.js
Resolves LLK/scratch-vm#1739. Hopefully resolves #4270, too, but I can't test that to be certain (I don't know how to use the backpack while offline).
*(Tangentially related to #4400; I noticed while testing the repros I described [here](https://github.com/LLK/scratch-gui/issues/4400#issuecomment-462994133) that switching the sprite no longer messed with the workspace scroll while zoomed in, and it still does in scratch-gui/develop. There's still lag, presumably from generating the menu item elements, though. /cc @kchadha)*
Takes `workspaceMetrics`, previously stored in the `<Blocks>` container's state, and changes it to be stored in global state via a reducer. Changes the `<TargetPane>` container so that, when it handles dropped blocks, it repositions them to fit within the viewport of …
=> Position blocks added from "share the love" within the viewport

src/containers/costume-tab.jsx, src/containers/sound-tab.jsx
Resolves #5876 
Add assets to editingTarget at the time it started uploading, not when `addCostume`/`addSound` is called. There are still some functions that use the old behavior, but I don't expect adding such assets (like adding blank costume) will be long enough for the user to switch sprites.
Previously if you switch sprites while adding assets it would add some of the assets to the new sprite instead of the previously selected one.
Tested on Firefox 77, Windows 10
To test this,
1) Import a GIF file via costumes tab
2) Switch sprites
3) Check that all imported GIFs are still in the previous sprite
4) Import sounds (multiple preferably, to lag it a bit) via sounds tab
5) Switch sprites
6) Check that all imported sounds are still in the previous sprite
=> Add assets to editingTarget at the time it started uploading

src/containers/sound-editor.jsx, test/unit/containers/sound-editor.test.jsx
Resolves #6027 
If the stage is fullscreen mode, sound editor now ignores all keyboard shortcut.
It does not make sense that a hidden component catches keyboard event and plays sound, etc.
=> Ignore sound editor keyboard shortcut on fullscreen stage

src/containers/stage.jsx
Resolves https://github.com/LLK/scratch-gui/issues/5776
Resolves #5781
This PR changes the `Stage` component's `onStartDrag` handler to only `Renderer.pick` drawables that are currently draggable, instead of `pick`ing all drawables then checking if each is draggable as it currently does.
Currently, `Renderer.pick()` is called every time you click and drag the mouse on the stage. Projects which make use of a "dragging" action do this a lot.
`Renderer.pick()` can be expensive, especially if they trigger a silhouette update on a pen skin (which calls `gl.readPixels` and massively impacts performance), and `onStartDrag` seems to be called every frame the mouse is down. By only `pick`ing draggable targets, performance can be improved, especially for mouse-controlled projects which make use of …
=> Only call Renderer.pick() on draggable targets in Stage.onStartDrag

src/containers/sound-tab.jsx, src/lib/file-uploader.js
Resolves #4639 
Close importing when sound is invalid
Because sound importing didn't have it
manually tested it with random txt file
=> Close Importing when the sound is invalid

src/components/monitor/monitor.css
- Resolves #4073
variable monitor changes for Flexible Box.
The vertical alignment of the number in monitors is center when variable name is Japanese.
The vertical alignment of the number in monitors is offset when variable name is Japanese.
Sorry, I can't test cloud variable.
Please tell me that how to test cloud variable.
Mac Chrome and Safari and Firefox
=> Fix number in a variable monitor is vertically misaligned.
